### ISSUE TITLE
starlette update breaks routing

### ISSUE THREAD

**Issue by medecau** [tiangolo/fastapi#10]
[starlette 0.9.11](https://pypi.org/project/starlette/0.9.11/) breaks fastapi routing
I'm currently working around this by enforcing starlette==0.9.10

**Comment by tiangolo** [comment]
Thanks for the report! I'll check it as soon as I get to my laptop.

**Comment by tiangolo** [comment]
It should now be fixed in the latest version `0.1.18`. The change is only pinning the dependencies so FastAPI is not broken, it should work now.

The next step will be to actually update FastAPI's code to be compatible with the latest changes in Starlette.
