### ISSUE TITLE
[FEATURE] Add chat integration to the docs website

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/fastapi#1001]
### Is your feature request related to a problem

Is your feature request related to a problem? Nope.

Tom Christie shared the idea of having the Gitter chat integrated into the docs website, he implemented it for Starlette.

We should have something similar.

Here's his PR: https://github.com/encode/starlette/pull/834

### The solution you would like

Copy Tom's code :man_shrugging:  and integrate FastAPI's Gitter chat into the docs website.

### Describe alternatives you've considered

Not doing it. Here's my small rant:

So, a chat system has some problems, it's a bit chaotic, all the conversations are mixed in the same sequence/thread, some get lost and never answered, can't be searched easily as GitHub issues or StackOverflow questions, so many questions are asked again and again.

I can't make sure personally that all the questions are answered in the chat (even if after a long time), that I can with GitHub issues, even if it takes me a year.

And as it's very easy to ask a question there, many people ask in the chat even before searching in Google or the docs. And many times the questions are not very "well-formed" (e.g. not having a clear example of what the person is trying to achieve) and it takes several turns back and forth just to clarify the question itself. And all that that consumes time and effort from the people that are there to help, that could have been avoided or invested in helping someone with a more difficult question that doesn't have an answer with a Google search.

But...

There's a lot of people in the chat, they end up there, and there are several awesome community members helping each other there, constantly.

It seems that despite all the problems with a chat system, it somehow helps foster an active community. For example, it seems it's easier for a community member to answer a question in the chat than to go to StackOverflow and answer `fastapi` questions there, even when StackOverflow gives points and stuff. 

So, if the chat is helping, we should embrace it and put it in the docs. :man_shrugging: 

### Additional context

https://gitter.im/tiangolo/fastapi?at=5e4d1705c2c73b70a44530ca

**Comment by aakashnand** [comment]
@tiangolo I tried implementing this feature please check my first PR here https://github.com/tiangolo/fastapi/pull/1061

**Comment by tiangolo** [comment]
This was solved by @aakashnand in #1061 :tada:
