### ISSUE TITLE
OpenAPI don´t load schemas in this last versions.

### ISSUE THREAD

**Issue by jqueija** [tiangolo/fastapi#10123]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

I have detected problems in the loading of the schemas generated by fastapi in openapi. As of version 0.95.1 schemas are loading null. It is possible that the error is caused by some pydantic update. With version 0.95.1 the schemas load correctly and can be seen in the development portals.

**Comment by Kludex** [comment]
Please create a discussion following the template: https://github.com/tiangolo/fastapi/discussions/new/choose.

>  I'm @tiangolo or he asked me directly to create an issue here.

I'll be closing this since you are not @tiangolo, and I know he didn't ask you to create this. 😅
