### ISSUE TITLE
Openapi example breaks when using multiple dependencies with the same body

### ISSUE THREAD

**Issue by pypae** [tiangolo/fastapi#1012]
If multiple dependencies use the same body parameter, the openapi example gets broken.

### Steps to Reproduce
1. Create a file with:
```python
from enum import Enum

from fastapi import Depends, FastAPI
from pydantic import BaseModel


app = FastAPI()


class Title(str, Enum):
    mr = 'Mr.'
    ms = 'Ms.'
    mrs = 'Mrs.'


class GreetRequest(BaseModel):
    name: str
    title: Title


def get_title(body: GreetRequest):
    return body.title


def get_name(body: GreetRequest):
    return body.name


@app.post('/greet')
def greet(name: str = Depends(get_name), title: Title = Depends(get_title)):
    return f"greetings {title} {name}!"


# For debugging purposes the script can be run directly
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
```
2. Run the file
3. Open the browser, go to `localhost:8000/docs`
4. The request body example is: 
```json
{
  "body": {
    "name": "string",
    "title": "Mr."
  }
}
```
5. Try out your endpoint
6. It fails with a `422` Unprocessable Entity

### Expected behavior

The request body example should be:
```json
{
  "name": "string",
  "title": "Mr."
}
```
### Environment

- OS: Linux / Windows
- FastAPI Version: 0.48.0
- Python Version: 3.7.5

**Comment by tiangolo** [comment]
I think this was recently fixed, please try with the latest version `0.54.1`.

I just tried with your example and it seems to be working as expected.
