### ISSUE TITLE
SQL Alchemy NULL POOL connection

### ISSUE THREAD

**Issue by jayapratha111998** [tiangolo/fastapi#10148]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

def get_db():
   
    try:
        engine = create_engine(f"mysql+pymysql://AIC_FASTAPI_ALL:c20baf51cf022c3a02b835badc7bb7d9@localhost:{port_num}/digital_factory_ent_v1",pool_pre_ping=True,pool_recycle = 60,poolclass=QueuePool)
        # engine = create_engine("mysql+pymysql://root@localhost/digital_factory_ent_v1",pool_pre_ping=True,pool_recycle = 60,poolclass=QueuePool)
        SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
        createFolder("Log/",f"Engine : {engine} ")
        
        db = SessionLocal()
        yield db
    finally:
        db.close()                                     i have been using db connection for api.. every request i need open and close the connection...what are the method should i use for close the db connection...shall i use null pool concept ...is it the make any issues

**Comment by tiangolo** [comment]
Hey there, although you checked that box, it seems you're not @tiangolo, and I didn't ask you to create this issue. :sweat_smile: 

So, please open a GitHub Discussion following all the template step by step. That will allow me or others to properly help you. :coffee: 

Given that, I'm gonna close this one.
