### ISSUE TITLE
[BUG] Documentation formatting error on SQL Databases page

### ISSUE THREAD

**Issue by alexjacobson95** [tiangolo/fastapi#1016]
### Describe the bug

The formatting on the tutorial SQL Database page is messed up near the bottom

### To Reproduce
Load https://fastapi.tiangolo.com/tutorial/sql-databases/
Scroll to `Review all the files` section.

### Expected behavior

There is supposed to be code formatting around the code samples but it looks like that's broken

### Screenshots
![Screen Shot 2020-02-21 at 3 06 03 PM](https://user-images.githubusercontent.com/402922/75078895-bf1a2280-54bb-11ea-9c87-b00e90b76466.png)

**Comment by shadrus** [comment]
Seems like it was fixed with [https://github.com/tiangolo/fastapi/pull/1168](https://github.com/tiangolo/fastapi/pull/1168)

**Comment by tiangolo** [comment]
Thanks for the report! Yeah, it was fixed recently. So I'm gonna close this issue now.
