### ISSUE TITLE
Shorter param definitions

### ISSUE THREAD

**Issue by vitalik** [tiangolo/fastapi#10178]
Hello @tiangolo 

Do you think this PR #9941 could be merged ?

**Comment by vitalik** [comment]
@Kludex is it a yes or a no ? :)

**Comment by Kludex** [comment]
I have no idea.

The issue was closed because it didn't check the required box. I didn't move to discussions because it just feels that you are trying to catch the maintainer's attention.

@tiangolo will check the PR at some point.
