### ISSUE TITLE
Cannot return response containing pydantic model that includes aliases since FastAPI 0.47.1

### ISSUE THREAD

**Issue by johnanthonyowens** [tiangolo/fastapi#1043]
### Starting in 0.47.1, responses fail validation if they include any pydantic model objects that contain field aliases

You can work around this by explicitly calling `.dict(by_alias=True)` on the top-level response model object before returning it from the path operation function (see the example below). However, this is super unintuitive and makes the use of field aliases painful. In our codebase we use aliases extensively (via `Config.alias_generator`) to expose camelCase in our public APIs while keeping our internal field names snake_case, and this issue is a real hassle.

### To Reproduce

1. Create a `test.py` file with:

```Python
import fastapi
import pydantic
import starlette.testclient
from typing import List

app = fastapi.FastAPI()

class Item(pydantic.BaseModel):
    my_value: int = pydantic.Field(..., alias='myValue')

class RootResponse(pydantic.BaseModel):
    items: List[Item] = pydantic.Field(...)

@app.get('/broken_1', response_model=RootResponse)
async def broken_1():
    # embedded models don't work if they have aliased fields
    return {'items': [Item(myValue=5), Item(myValue=10)]}

@app.get('/broken_2', response_model=RootResponse)
async def broken_2():
    # making the top-level response a model instance doesn't help
    return RootResponse(items=[Item(myValue=5), Item(myValue=10)])

@app.get('/workaround', response_model=RootResponse)
async def workaround():
    # workaround is to build a top-level model and then dict(by_alias=True)
    return RootResponse(items=[Item(myValue=5), Item(myValue=10)]).dict(by_alias=True)

with starlette.testclient.TestClient(app) as test_client:
    for path in ['/broken_1', '/broken_2', '/workaround']:
        try:
            print('-------------------------------------------')
            print(path)
            response = test_client.get(path)
        except Exception as exc:
            print(exc)
        else:
            print('succeeded')
```
2. Run `python3 test.py` with FastAPI 0.47.0. All 3 cases succeed.
3. Run `python3 test.py` with FastAPI 0.49.0. Only the "workaround" case succeeds.

### Expected behavior

Model classes that include aliased fields (whether the alias is directly specified on the field as in the above example, or using a pydantic `Config.alias_generator`) should be usable with the context of a response model.

### Environment

- OS: Linux (Ubuntu 18.04)
- FastAPI Version: 0.47.1 and above
- Python version: 3.7, 3.8

**Comment by juhovh-aiven** [comment]
I would just like to add this test case that breaks it even with 0.47.0:
```
@app.get('/broken_3', response_model=RootResponse, response_model_exclude_unset=True)
async def broken_3():
    # setting response_model_exclude_unset=True makes it fail even on 0.47.0
    return RootResponse(items=[Item(myValue=5), Item(myValue=10)])
```

**Comment by juhovh-aiven** [comment]
Basically a quick fix that would fix the problem for all cases I can imagine is to just do this following modification, but it does come with a certain performance penalty by doing the serialization twice (once for validation, and second time for actual output):

```
@@ -59,11 +59,7 @@ async def serialize_response(
 ) -> Any:
     if field:
         errors = []
-        if exclude_unset and isinstance(response, BaseModel):
-            if PYDANTIC_1:
-                response = response.dict(exclude_unset=exclude_unset)
-            else:
-                response = response.dict(skip_defaults=exclude_unset)  # pragma: nocover
+        response = jsonable_encoder(response, by_alias=True, exclude_unset=True)
         if is_coroutine:
             value, errors_ = field.validate(response, {}, loc=("response",))
         else:
```

**Comment by juhovh-aiven** [comment]
The above quick fix broke some SQLAlchemy stuff, so I ended up doing a less invasive solution in https://github.com/tiangolo/fastapi/pull/1074 instead, which simply recurses over lists and dicts looking for `BaseModel` instances.

**Comment by jmriebold** [comment]
I've run into this as well. We solved it by subclassing `BaseModel` like so:

```python
class CustomBaseModel(BaseModel):
    class Config:
        # Don't force use of aliases in class instantiation/attribute access
        allow_population_by_field_name = True
```

I tried running your test script using the subclassed model and it appeared to work correctly:

```
/broken_1
succeeded
-------------------------------------------
/broken_2
succeeded
-------------------------------------------
/workaround
succeeded
```

**Comment by tiangolo** [comment]
Thanks for the report @johnanthonyowens and for the discussion here everyone!

This was fixed by @juhovh-aiven on https://github.com/tiangolo/fastapi/pull/1074 :tada: :rocket:

**Comment by Oreilles** [comment]
I just faced this issue, which wan't fix for the situation where the returned type has the attribute `table=True`.
For example, here's a modified version of the code sample provided in #1070 :

```python
from fastapi import FastAPI
from pydantic import BaseModel, Field

class SimpleModel(BaseModel, table=True):
    id: int = Field(primary_key=True, default=1)
    name: str
    value: int

class AliasedModel(BaseModel, table=True):
    id: int = Field(primary_key=True, default=1)
    name: str = Field(..., alias="aliased_name")
    value: int

app = FastAPI()

@app.get("/simple", response_model=SimpleModel)
def read_simple():
    return SimpleModel(name="name", value=1234)

@app.get("/aliased", response_model=AliasedModel)
def read_aliased():
    return AliasedModel(aliased_name="name", value=1234)
```

`GET /aliased` will result in a server error:
```
pydantic.error_wrappers.ValidationError: 1 validation error for AliasedModel
response -> aliased_name
  field required (type=value_error.missing)
```

Is this expected, or should we open another issue ?
