### ISSUE TITLE
[BUG] Broken link to GraphQL tutorial

### ISSUE THREAD

**Issue by e-ruiz** [tiangolo/fastapi#1045]
### Describe the bug

It's a documentation bug, not a software bug :wink: 

Unfortunately the link for GraphQL tutorial is broken: https://fastapi.tiangolo.com/tutorial/graphql/ 

References: 
- https://fastapi.tiangolo.com/release-notes/#061
- PR #48 

Best regards.

**Comment by tiangolo** [comment]
Thanks! This was fixed by @sattosan in #1052

**Comment by e-ruiz** [comment]
Links mentioned working perfectly.

Closing issue.
