### ISSUE TITLE
Support for pydantic exclude_none

### ISSUE THREAD

**Issue by ricleal-fugue** [tiangolo/fastapi#1050]
### Is your feature request related to a problem

I want to exclude from the output values set to `None`.
`pydantic` has support for this: `<object>.json(exclude_none=true)`

### The solution you would like

Similar to the parameter `response_model_exclude_unset` but to exclude the `None`s.

### Describe alternatives you've considered

Not setting any `None`... Lot of boiler plate code.

**Comment by tiangolo** [comment]
In the latest versions you can set it in the *path operation decorator* with `response_model_exclude_none=True`.

The current latest version is `0.54.1`.

**Comment by ricleal-fugue** [comment]
Thanks 👍
