### ISSUE TITLE
[FEATURE] Set up translations for docs

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/fastapi#1055]
### Is your feature request related to a problem

Nope.

Several community members have proposed and offered help adding translations to other languages.

Portuguese: #921 
Chinese: discussed with https://twitter.com/linupy1 on Twitter
Spanish: at least I would do it, I hope others would be willing to help :smile: 

### The solution you would like

I have to set up a simple way to add translations.

I think it will be adding a copy of the same MkDocs files for each language and including all that on a sub path.

It will probably include copying each original English file that is not translated and adding a note about its translation.

And there should also be a way to add a note about translations that need to be re-synchronized with the original English version.

There should also probably be a note about translations being provided by the community and that the "official" version is always English.

The translation process would probably be page by page in a separated PR. That way others can review those translations in small amounts.

It would probably depend a lot on each PR getting several PR approvals by community members. I can verify and check Spanish and, to some extent, Portuguese. But for example, I don't speak Japanese, Chinese, nor Rusian. And there's a lot of content about FastAPI in those languages, I suspect those would be some of the first translations.

### Describe alternatives you've considered

Not adding translations at all.

Waiting for MkDocs to have official support for translations https://github.com/mkdocs/mkdocs/issues/617 , but as this is a complex topic, I expect that to take some time. And we can have a simple version that works, at least just for FastAPI.

### Additional context

:earth_africa: :man_shrugging:

**Comment by pyropy** [comment]
@tiangolo I can help with translations to Serbian

**Comment by yutayamazaki** [comment]
@tiangolo I would like to help translate into Japanese.

**Comment by tiangolo** [comment]
We have it now! :earth_africa: :rocket: 

Here are the new docs for contributing translations to FastAPI: https://fastapi.tiangolo.com/contributing/#translations

And I think it ended up quite easy to use/set up. :sparkles: :tada: 

Thanks @pyropy , @yutayamazaki , @linupychiang, @juhovh-aiven for your offer and/or help! It's very much appreciated :cake: :earth_africa:

**Comment by waynerv** [comment]
@tiangolo

**Comment by waynerv** [comment]
@tiangolo 
We(@Dustyposa ) have formed a small team to complete the translation of Chinese version. Interested friends are welcome to join us.

**Comment by tiangolo** [comment]
Thanks for doing it @waynerv, @Dustyposa, and everyone contributing!

If you want, feel free to create a new issue to coordinate Chinese translation and I will pin it. There's currently one for Portuguese translations https://github.com/tiangolo/fastapi/issues/1211

As we now have the translations system and workflow more or less set up I'll now close this issue.
