### ISSUE TITLE
[BUG] OpenAPI incorrect if request body is consumed more than once

### ISSUE THREAD

**Issue by chbndrhnns** [tiangolo/fastapi#1077]
### Describe the bug

Both endpoints in the test below accept the same request body. However, the OpenAPI spec looks different for `/nested-body` and suggests to wrap the `ProjectIn` fields in to a `project_in` key.

Doing so fails the test (cf. `def test_nested_body_post_wrapped()`).

The bug occurs when you consume the body twice, like in the endpoint and in its dependency.

### To Reproduce

Steps to reproduce the behavior with a minimum self-contained file.

Replace each part with your own scenario:

1. Create a file `test_body.py`:

<details><summary>Click to toggle content</summary>

```python
import pytest
from fastapi import FastAPI, Depends, Body
from pydantic import BaseModel
from starlette import status
from starlette.testclient import TestClient


class ProjectIn(BaseModel):
    name: str


app = FastAPI()


async def dep(
        project_in: ProjectIn = Body(...)
):
    pass


@app.post(path='/nested-body')
def body_nested(
        project_in: ProjectIn = Body(...),
        dep: None = Depends(dep),
):
    ...


@app.post(path='/normal-body')
def body_normal(
        project_in: ProjectIn = Body(...)
):
    ...


@pytest.fixture
def client():
    yield TestClient(app)


def test_normal_body_post_returns_200_as_per_spec(client):
    body = ProjectIn(name='abc').json()

    res = client.post('/normal-body', data=body)

    assert res.status_code == status.HTTP_200_OK


def test_nested_body_post_unwrapped_returns_error_as_per_spec(client):
    body = ProjectIn(name='abc').json()

    res = client.post('/nested-body', data=body)

    assert res.status_code >= status.HTTP_400_BAD_REQUEST


def test_nested_body_post_wrapped_returns_200_as_per_spec(client):
    body = {
        'project_in': ProjectIn(name='abc').json()
    }

    res = client.post('/nested-body', data=body)

    assert res.status_code == status.HTTP_200_OK


def test_body_spec_should_be_the_same_for_both_endpoints(client):
    res = client.get('/openapi.json')

    parsed = res.json()

    assert 'ProjectIn' in \
           parsed['paths']['/normal-body']['post']['requestBody']['content']['application/json']['schema']['$ref']
    assert 'ProjectIn' in \
           parsed['paths']['/nested-body']['post']['requestBody']['content']['application/json']['schema']['$ref']
```

</details>

2. Run `pytest test_body.py`.

### Expected behavior

The OpenAPI spec matches the actual behavior (`test_body_spec_should_be_the_same_for_both_endpoints` should pass).

Instead, given tests assume that the openapi.json is correct:

- `test_nested_body_post_unwrapped_returns_error_as_per_spec` should fail
- `test_nested_body_post_wrapped_returns_200_as_per_spec` should pass

### Environment

- OS: macOS
- FastAPI Version: 0.52.0
- Python version: 3.7.6

**Comment by Toad2186** [comment]
Opened https://github.com/tiangolo/fastapi/pull/1079 to fix this. Can you test it out if you are able?

`test_normal_body_post_returns_200_as_per_spec` => Passes
`test_nested_body_post_unwrapped_returns_error_as_per_spec` => Fails, because this should be the correct behavior and `status_code` should be 200.
`test_nested_body_post_wrapped_returns_200_as_per_spec` => Fails, because the parameter should not be embedded.
`test_body_spec_should_be_the_same_for_both_endpoints` => The openapi specs are now the same for both.

**Comment by tiangolo** [comment]
Thanks for the report @chbndrhnns , and thanks for the fix @Toad2186 ! :clap: 

This is already merged and released, you can check it in the latest version: `0.54.1`.

If that solves your problem, may we close this issue?

**Comment by chbndrhnns** [comment]
Solved for me. Thanks much!
