### ISSUE TITLE
[BUG] Upgrade python-mulipart==0.0.7 from low version fastapi upload file may be 400

### ISSUE THREAD

**Issue by Sube-py** [tiangolo/fastapi#11104]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

> In order to fix the [security issue](https://github.com/tiangolo/fastapi/security/advisories/GHSA-qf9m-vfgh-m389) of uploaded files, we upgraded the python-mulipart library, but this caused "There was an error parsing the body" to appear frequently when uploading files.
![image](https://github.com/tiangolo/fastapi/assets/53138073/ab35a6fd-ca76-4009-b225-bf821c362165)

- macos: 14.2.1 
- fastapi: 0.94.1
- python-multipart: 0.0.7

**Comment by Sube-py** [comment]
Due to the major changes in the version after 0.94.1, we were unable to upgrade our project in a short period of time, but we also wanted to avoid upload vulnerabilities. After upgrading python-mulitpart, the security problem was indeed solved, but we could not upload it.

**Comment by Sube-py** [comment]
[BUG2] The latest fastapi version can not upload the file which name contains Chinese.

**Comment by h0rn3t** [comment]
file which name contains non-ascii can not upload

**Comment by tiangolo** [comment]
Thanks for the interest! The best place to start these conversations is in GitHub Discussions. New issues should be created by me, or someone I asked directly.

GitHub Discussions have a specific template that guides the conversation in a way that allows us to figure out what needs to happen, what is currently happening, etc. Including a replicable example and others.

---

This specific error is related to `python-multipart`, it's reported here: https://github.com/Kludex/python-multipart/issues/78, introduced by me here: https://github.com/Kludex/python-multipart/pull/75, and fixed here: https://github.com/Kludex/python-multipart/pull/79#pullrequestreview-1872766504

---

Given that, I'll now close this one. ☕
