### ISSUE TITLE
Middleware runs twice 

### ISSUE THREAD

**Issue by linpan** [tiangolo/fastapi#11159]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

2024-02-18 11:33:05.299 | INFO     | patrol.middlewares:add_middleware:18 - add GZip middleware
2024-02-18 11:33:05.336 | INFO     | patrol.middlewares:add_middleware:18 - add GZip middleware

**Comment by Nannigalaxy** [comment]
can you please reopen this issue?

**Comment by Kludex** [comment]
This issue doesn't exist on the latest FastAPI.

**Comment by Nannigalaxy** [comment]
I'm facing this in 0.104.1. will try with new version and update

**Comment by Nannigalaxy** [comment]
upgraded to 0.110.0 and tried, but issue persists. any help please

**Comment by Kludex** [comment]
Open a discussion with an MRE.

**Comment by Kludex** [comment]
Locking this issue to avoid confusion, since this is not an issue.
