### ISSUE TITLE
[BUG] [Documentation] Example for GZipMiddleware

### ISSUE THREAD

**Issue by sagrawal-idrc** [tiangolo/fastapi#1149]
### Describe the bug

Example for `GZipMiddleware` is instead for `TrustedHostMiddleware`.

### To Reproduce

Please visit: https://fastapi.tiangolo.com/advanced/middleware/#gzipmiddleware

### Expected behavior

Example for `GZipMiddleware` should be available.

**Comment by tiangolo** [comment]
Thanks for the report, this was fixed recently, so I'll close this issue.
