### ISSUE TITLE
[QUESTION] dependencies inherited from typing.Generic 

### ISSUE THREAD

**Issue by snaffi** [tiangolo/fastapi#1155]
How can I avoid 'args' and 'kwargs' as a required query parameters if I use typing.Generic?

I have got next generic base class

```python
from typing import Generic, Type, TypeVar

ModelType = TypeVar("ModelType", bound=BaseModel)
CreateSchemaType = TypeVar("CreateSchemaType", bound=BaseModel)
UpdateSchemaType = TypeVar("UpdateSchemaType", bound=BaseModel)

class CRUDBase(Generic[ModelType, CreateSchemaType, UpdateSchemaType]):

    def __init__(self, db: Database, table: Table, model: Type[ModelType]):
        self.db = db
        self.model = model
        self.table = table
```

And successor class which used as a dependency 

```python

class UserService(CRUDBase[User, UserCreate, UserUpdate]):
    def __init__(self, db: Database = Depends(get_db)):
        super().__init__(db, UserTable, User)
```

Since typing.Generic has overwritten `__new__` method, so FastAPI makes `args` and `kwargs` as a required query attributes.

I have only one solution with a factory function, have you another solution?

**Comment by tiangolo** [comment]
Nope, I don't have a different solution as FastAPI needs to be able to read the function signature.

Nevertheless, given that the generics part of `CRUDBase` is just to provide type checks and nothing more, you could remove that part and then it would work normally.

Otherwise, you could create a `UserService` that creates an internal instance of `CRUDBase` and uses it internally instead of inheriting from it.

**Comment by dardosordi** [comment]
Got it working somehow with this decorator.

`def restore_signature(cls):
    @functools.wraps(cls)
    def wrap(*args, **kwargs):
        return cls(*args, **kwargs)

    sig = inspect.signature(cls.__init__)
    parameters = list(sig.parameters.values())[1:]

    wrap.__signature__ = sig.replace(parameters=parameters)
    return wrap
`

**Comment by myheartsgoon** [comment]
> Got it working somehow with this decorator.
> 
> ```python
> def restore_signature(cls):
>     @functools.wraps(cls)
>     def wrap(*args, **kwargs):
>         return cls(*args, **kwargs)
> 
>     sig = inspect.signature(cls.__init__)
>     parameters = list(sig.parameters.values())[1:]
> 
>     wrap.__signature__ = sig.replace(parameters=parameters)
>     return wrap
> ```

@dardosordi Could you please share detail how you get it working?

**Comment by dardosordi** [comment]
> @dardosordi Could you please share detail how you get it working?

```python
class BaseService(Generic[ModelType, CreateSchemaType, UpdateSchemaType]):
    def __init__(self, model: Type[ModelType], db: Session):
      """Base class for generic service"""

@generic_dependency
class UserService(BaseService[User, UserCreate, UserUpdate]):
    def __init__(self, db: Session = Depends(get_db)):
        super().__init__(User, db)

@router.post("/signup")
def signup(user_service: UserService = Depends()):
 
```
