### ISSUE TITLE
[BUG]Broken Links in Settings and Environment Variables Docs

### ISSUE THREAD

**Issue by Mohamed-Kaizen** [tiangolo/fastapi#1209]
In Settings and Environment Variables Docs the link to  **Bigger Applications - Multiple Files.** doesn't work.

![Screenshot from 2020-04-03 14-10-34](https://user-images.githubusercontent.com/35686076/78354658-f13b9b80-75b4-11ea-922e-9ed8abd5cf2f.png)

**Comment by tiangolo** [comment]
Thanks for reporting it! It should be fixed now.
