### ISSUE TITLE
Broken external link

### ISSUE THREAD

**Issue by DavidBord** [tiangolo/fastapi#1265]
https://blog.bartab.fr/fastapi-logging-on-the-fly/ leads to: 404 page not found

**Comment by tiangolo** [comment]
Thanks! Is that in the docs for External Links?

**Comment by PfeifferJosef-96** [comment]
I searched the repository for this link and i can confirm that it leads to a: 404 page.

Link is in the file: [fastapi/docs/en/docs/external-links.md ](https://github.com/tiangolo/fastapi/blob/a0e4d38bea74940de013e04a6d6f399d62f04280/docs/en/docs/external-links.md) under the section Articles - English point "FastAPI, a simple use case on logging by @euri10.".

Should this link be removed or updated or ... ?

**Comment by victorphoenix3** [comment]
@Kludex should this link be removed?

**Comment by Kludex** [comment]
@victorphoenix3 Yes!

**Comment by tiangolo** [comment]
Yep, it should be removed. Thanks @Kludex ! :rocket:

**Comment by tiangolo** [comment]
This was fixed by @victorphoenix3 :rocket: on https://github.com/tiangolo/fastapi/pull/1565 :tada: 

So I'll close this now. :slightly_smiling_face:
