### ISSUE TITLE
[FEATURE] Use TestClient in an async fashion

### ISSUE THREAD

**Issue by bharel** [tiangolo/fastapi#1273]
### Is your feature request related to a problem

Unfortunately, test client runs it's own event loop. This causes an issue when attempting to do other async operations in the background.
Running it inside an executor will cause it to run in a different threat, which in turn causes issues with other async libraries a they're calling coroutines from a different thread.

### The solution you would like

Make a TestClient that doesn't create it's own loop. Just have it async. 

### Describe alternatives you've considered

Other than executor or partching fastapi, there are no alternatives.

**Comment by nsidnev** [comment]
There are plans (https://github.com/encode/starlette/issues/440 and https://github.com/encode/starlette/issues/652) to move `starlette.testclient.TestClient` from `requests` to `httpx` to fix this behaviour. Before this happens you can try using `httpx` [directly](https://www.python-httpx.org/async/#calling-into-python-web-apps) or try the [`async-asgi-client`](https://pypi.org/project/async-asgi-testclient/) package. But there may be some problems with the templates, if you are using them.

**Comment by bharel** [comment]
As long as fastapi doesn't support it, may I suggest adding a note to the docs?

**Comment by nsidnev** [comment]
Yes, good idea. I think adding an [`info`](https://squidfunk.github.io/mkdocs-material/extensions/admonition/#info) block after the introduction on [this](https://fastapi.tiangolo.com/tutorial/testing/) page will be good place, right? 

In addition, it is possible to create a new page that will show how to use `httpx` (or `async-asgi-client`) for tests. Probably in the advanced section. 

Would you submit a PR?

**Comment by tiangolo** [comment]
Yep, as @nsidnev says. :point_up: 

And yeah, that could probably have a small section in the advanced tutorial.

**Comment by empicano** [comment]
I've done some async testing using `httpx` in the last few days, as I wanted to verify the state of the database in my tests as well, and that works really well! I don't have experience with the `async-asgi-client` though.

Would be up to write a section in the docs on it!

**Comment by aoncreed** [comment]
As @empicano mentioned using httpx directly works great. Here's a little example "workaround" by using the `httpx.AsyncClient` and it's working quite well

in your conftest.py

```python

from typing import Generator
import pytest
from httpx import AsyncClient
from asyncio import get_event_loop

from app.db.session import SessionLocal
 

@pytest.fixture(scope="session")
def db() -> Generator:

    yield SessionLocal()


@pytest.fixture(scope="module")
async def async_client() -> Generator:

    async with AsyncClient(app=app, base_url="http://testserver") as client:

        yield client


@pytest.fixture(scope="module")
def event_loop():

    loop = get_event_loop()

    yield loop

```

in a test file

```python

import pytest
from httpx import AsyncClient
from fastapi import status
from sqlalchemy.orm import Session


@pytest.mark.asyncio
async def test_get_something(async_client: TestClient, db: Session) -> None:
    await create_something(db=db)
    response = await async_client.get("/something?skip=0&limit=5")
    
    assert response.status_code == status.HTTP_200_OK
    assert 0 < len(response.json()) <= 5

**Comment by tiangolo** [comment]
@empicano added this, the new docs are here: https://fastapi.tiangolo.com/advanced/async-tests/ :tada: :rocket: :memo:

**Comment by Gatsby-Lee** [comment]
@tiangolo how to trigger `startup` and `shutdown` event with this approach?

**Comment by madnesspie** [comment]
Hi here, @tiangolo. Thanks for your great work. I faced the same issue as @Gatsby-Lee above. I have to trigger startup event before async testing. Is there any solution?

**Comment by madnesspie** [comment]
@Gatsby-Lee You can use https://pypi.org/project/async-asgi-testclient/. It will run events in context manager's aentry/aexit methods. @tiangolo, hi here, it might be worth to clarify in documentation that the events will work only with `async-asgi-testclient`.

**Comment by seweissman** [comment]
Has anyone been able to get a streaming async test to work with httpx.AsyncClient.stream? I filed an issue here (https://github.com/tiangolo/fastapi/issues/2006) and haven't had any responses. Based on @madnesspie's comment above I tried using async-asgi-testclient and was able to get my tests to work and I added a comment to that effect, so perhaps it is related to the aentry/exit events, but I admit I don't fully understand what is going on.

**Comment by kozhushman** [comment]
> @Gatsby-Lee You can use https://pypi.org/project/async-asgi-testclient/. It will run events in context manager's aentry/aexit methods. @tiangolo, hi here, it might be worth to clarify in documentation that the events will work only with `async-asgi-testclient`.

I strongly agree that this part MUST be in docs about async testing. Events is huge and important part and lack of information about this matter is disappointing. I absolutely love FastAPI and I hope those missing areas will be covered. I can add mention to the docs about events in async testing, but in the current state it will broke it, because approach there is totally different.

**Comment by borishim** [comment]
Is there an AsyncClient equivalent for websockets?

**Comment by ievgennaida** [comment]
AsyncClient helped.
You can also check FastApi article
https://fastapi.tiangolo.com/advanced/async-tests/

**Comment by symstu** [comment]
> Is there an AsyncClient equivalent for websockets?

I found strange things inside Strarlette: it uses anyio for testclient and runs all websockets views in different threads with their own loops. But at the same time, starlette recommends to use deployment with unicorn, which recommends to use one process -> one thread -> one loop. 

As a result, original TestClient from Starlette can not be used for testing production-ready code. Sometimes it causes such huge changes that developer should write another app for test suits. 

In the Internet currently i didn't found any lib for this case. So i made my own client based on original TestClient only for websockets

Example of usage:
```python
@pytest.fixture(scope='session')
async def user():
    async with AsyncioTestClient(app, event_loop=shared_event_loop) as client:
        async with client.websocket_connect("/ws/") as websocket:
            yield websocke
```

[testclient.txt](https://github.com/tiangolo/fastapi/files/8375507/testclient.txt)

**Comment by irgolic** [comment]
> [testclient.txt](https://github.com/tiangolo/fastapi/files/8375507/testclient.txt)

Hey @symstu, this is exactly what I was looking for, thank you. Any chance you could put a license on it, so I could include it in a project?

**Comment by symstu** [comment]
> > [testclient.txt](https://github.com/tiangolo/fastapi/files/8375507/testclient.txt)
> 
> Hey @symstu, this is exactly what I was looking for, thank you. Any chance you could put a license on it, so I could include it in a project?

just include it if you want

**Comment by zerlok** [comment]
I think it's a good feature request to let devs write application tests in async functions with websocket support. Why it's closed?

E.g. I want to make an integration test with 2 servers running during the tests and I can't use sync tests (because `TestClient` blocks the thread). The good alternative is `AsyncClient` but it doesn't support websockets.

**Comment by AivanF** [comment]
Hi! I made my own short workaround for async WebSocket testing in FastAPI / Starlette apps:
https://gist.github.com/AivanF/4616d7e89fb5ea497deda31201db2c60

I also suggested Starlette maintainers to let me make a pull request so this will work out of the box: https://github.com/encode/starlette/discussions/2897
Please upvote if you'd like to see this feature available (and to see me working hard keeping community standards 😅)
