### ISSUE TITLE
[BUG] Typo in [EN] tutorial: body-fields

### ISSUE THREAD

**Issue by chenl** [tiangolo/fastapi#1296]
### Describe the bug

There is a typo in `fastapi/blob/master/docs/en/docs/tutorial/body-fields.md` under `## Add Extra Information:` 

> ...
> You will learn more about it later to declare examples examples.

### To Reproduce

Look for `examples examples` in https://fastapi.tiangolo.com/tutorial/body-fields/#add-extra-information

### Expected behavior

It should probably be a link to somewhere although it is not really clear where to.

**Comment by tiangolo** [comment]
Thanks for reporting it @chenl ! This was solved in #1299 :heavy_check_mark:
