### ISSUE TITLE
[FEATURE] Create response_model schema with header

### ISSUE THREAD

**Issue by mostaphaRoudsari** [tiangolo/fastapi#132]
**Is your feature request related to a problem? Please describe.**

It's currently possible to set the response model to a pydantic class which is very handy but as far as I can see it's not possible to set up the header properties inside the object. I know that I can set up the header in `Response` but that won't be included in opeanapi documentation.

What I get:

![image](https://user-images.githubusercontent.com/2915573/55423976-27cb7a00-554d-11e9-8271-eacdf46a0bb3.png)

What I want:

![image](https://user-images.githubusercontent.com/2915573/55423928-04a0ca80-554d-11e9-9367-f1f3504faf26.png)

**Describe the solution you'd like**

I think one should be able to create a `pydantic` object for responses which supports `headers`, `content`, etc.

```python
from pydantic import BaseModel, Schema, UrlStr
from uuid import UUID

class CreatedHeader(BaseModel):
    """Header for created response."""
    Location: UrlStr = Schema(
        ...,
        description='Location of the newly created resource.'
    )

class CreatedContent(BaseModel):
    """Content for created response."""
    id: UUID = Schema(
        ...,
        description='Id for the newly created resource.',
        example='3fa85f64-5717-4562-b3fc-2c963f66afa6'
    )
    message: str = Schema(
        None,
        description=' A human readable message',
        example='Use Location in headers to access the new object.'
    )


# This should be used as the response_model
class Created(BaseModel):
    headers: CreatedHeader
    content: CreatedContent

```

**Describe alternatives you've considered**

For now I create a response model only for content. Header is missing from documentation but I add to description that see header for Location.

**Additional context**

This can be considered/ addressed as part of  #16. Generally speaking the response documentation/ validation similar to what is possible for parameters and query will be very helpful.

**Comment by tiangolo** [comment]
Thanks for the report. Yes, I plan on adding that as part of #16 (or based on it).

**Comment by tiangolo** [comment]
It's now possible to include `responses` in *path operations*, including everything available/valid in OpenAPI, like `headers`: https://fastapi.tiangolo.com/tutorial/additional-responses/

It's available in version `0.12.0`. :tada: :rocket:

**Comment by mostaphaRoudsari** [comment]
@tiangolo, beautiful! I will try it out and let you know the results. cheers.

**Comment by mostaphaRoudsari** [comment]
@tiangolo quick feedback. Adding responses works as expected and I can also add the header like this:

```python
@router.post( [...] ,
    responses={
        **additional_error_post_responses,
        201: {'headers': {'Location': ''}}
        }
)
```

but this doesn't have type checking for Location format. If I pass a pydantic object to 'headers' it gives an error. I tried both assigning a model to header which gives me an error on building the redoc page:

```python
class Location(BaseModel):
    """Header for created response."""
    Location: UrlStr = Schema(
        ...,
        description='Location of the newly created resource.'
    )

@router.post( [...] ,
    responses={
        **additional_error_post_responses,
        201: {'headers': {'model': Location}}
        }
)
```
and writing the whole response model as a pydantic object which in this case it takes `headers` as part ot the Response `content` schema: 

```python
@router.post( [...] ,
    responses={
        **additional_error_post_responses,
        201: {'model': CreatedResponse}
        }
)
```

**Comment by tiangolo** [comment]
Hmm, I see. We can think of it as a feature request to support Pydantic models in headers, but it would be exclusively to generate the JSON Schema.

Have in mind that:

* You still need to return a `Response` with the headers already included.
* Those header's won't be validated by **FastAPI**, but you can pass them to your model to validate them in your code (in your *path operation*) and then convert them to a `dict`, before passing them to the `Response`.
* Also, the Pydantic models are currently used to define response bodies, but they are not being used to include several parts of a response in a single model (headers and content).

**Comment by mostaphaRoudsari** [comment]
Thank you for the explanation. Since the first solution already addresses this feature request and there are alternate ways for validating the header I close this issue. Thank you for addressing it quickly.

**Comment by tiangolo** [comment]
Great, thanks!
