### ISSUE TITLE
[FEATURE] Positional-only dependencies

### ISSUE THREAD

**Issue by retnikt** [tiangolo/fastapi#1329]
Is your feature request related to a problem? No

It would be nice to be able to use [positional-only arguments](https://www.python.org/dev/peps/pep-0570/) (new in Python 3.8) as dependencies in endpoints, e.g.
```python
@app.get("/foo")
async def foo(something=Depends(Something), /, more_dependencies, ...):
    ...
```

### The solution you would like

Dependencies are resolved correctly in the case above

This is just an idea, I understand it would be a lot of effort to implement, and I can't think of any compelling use-cases right now, but it seems an arbitrary restriction to place for a new user. I'd be willing to work on a PR if nothing else than to get to know your codebase a bit better

**Comment by tiangolo** [comment]
Hey @retnikt , thanks for the interest.

I don't think there would be a benefit in adding custom logic for that, so I would rather pass on it.

Nevertheless, there's a bunch of issues with `good-first-issue` that you could check if you want to help and get familiar with the code base :smile:
