### ISSUE TITLE
How can i use link tags?

### ISSUE THREAD

**Issue by ArtemZaitsev1994** [tiangolo/fastapi#1331]
Hi there. I can't seem understand, is there any ways to use link tags? I mean, I defined some links as 'protected', for example, and how can i check the link in code?
I'm about something like that:
`request.url in request.app.router.tags['protected']`
Thank you.

**Comment by retnikt** [comment]
Tags are for documentation only, for grouping routes in to categories. If you want to protect routes properly, see the Security tutorial: https://fastapi.tiangolo.com/tutorial/security/

**Comment by tiangolo** [comment]
Thanks for the help here @retnikt ! :coffee: :bow: 

@ArtemZaitsev1994 yep, what @retnikt says. :point_up:
