### ISSUE TITLE
[QUESTION] How to implement Multi tenancy in FastAPI?

### ISSUE THREAD

**Issue by ParticleDuality** [tiangolo/fastapi#1333]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.

### Description

Is it possible to make a multi tenant app with FastAPI? I've searched about multi tenancy within FastAPI and couldn't find any info. 

I only require the possibility to have multiple tenants in a postgreSQL database and be able to discern the users's tenant via url and not by subdomain.

For example:

- webapp.com/tenant1/dashboard

- webapp.com/tenant2/dashboard

I'd appreciate if someone can drop some links or tips of how to reach this approach.

**Comment by retnikt** [comment]
You could add a `tenant` path parameter to each route which is then used to discern which database items to lookup, etc. See https://fastapi.tiangolo.com/tutorial/path-params/

**Comment by Dasapugo4444** [comment]
Thanks, I would try it.

**Comment by tiangolo** [comment]
Thanks for the help here @retnikt ! :bow: 

@ParticleDuality I'm not sure what you mean with multi-tenancy, but maybe mounting sub-apps might do what you need: https://fastapi.tiangolo.com/advanced/sub-applications-proxy/

**Comment by lukik** [comment]
> Thanks for the help here @retnikt ! 🙇
> 
> @ParticleDuality I'm not sure what you mean with multi-tenancy, but maybe mounting sub-apps might do what you need: https://fastapi.tiangolo.com/advanced/sub-applications-proxy/

The link is broken?

**Comment by lukik** [comment]
I'll add on to this question what my thinking is for Multi Tenancy. 

I came here looking for [Django-Tenant](https://github.com/django-tenants/django-tenants) like functionality for FastAPI. Django-Tenant app allows one to have One Database but multiple schemas (one tenant, one schema). 

Django-Tenant will manage (in Postgresql Speak) the search path based on the URL one has made the request to e.g. http://tenant_one.example.org/books/ will make calls to the `tenant_one` schema in the DB and not touch other tenants data. It will also allow one to run migrations across all Schemas including the Public Schema which is such a peace of mind.

With one more app, [Django-Tenant-Users](https://github.com/Corvia/django-tenant-users) you can have users in the public schema (accessible by all tenants) but with their permissions set and managed at the tenant level.

So I guess that would be my wish list for Multi Tenancy for Fast API which to be honest is a combination of ORM features (SQLAlchemy?) and Routing & Requesting capabilities (FastAPI)

**Comment by lowercase00** [comment]
@lukik been looking for exactly the same. I posted a issue in Django Tenant Schema, to check how 'adaptable' would the code base be. I'm not familiar with Django, so don't know how much it provides. Maybe something based on databases or Gino, and some other custom decorator to get the context... 
Looking foward to the day FastAPI will have as many options for middleware as Django/Flask

**Comment by e-belair** [comment]
A solution would be to use the Request object to retrieve the database :

```
async def get_db_name(request: Request):
    # Get db from subdomain
    db_name = request.base_url.hostname.split('.')[0]

    # Or Get db from header
    if 'HTTP_X_DATABASE' not in request.headers:
        db_name = request.headers['HTTP_X_DATABASE']
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED, detail="HTTP_X_DATABASE is missing"
        )
    return db_name


async def get_db(db_name: str = Depends(get_db_name)):
    # configure database here
    pass
```

**Comment by hacen-ai** [comment]
@lowercase00 @lukik  Did you find (or creat) something in this matter?
Would be really creat if we can have something like  Django-Tenants  in Fastapi. Any resource you can recommend due to your search?
thank you

**Comment by lowercase00** [comment]
@hacen-ai I gave up. As much as would be possible to write something to dynamically set the search path, the extra complexity to manage the connection and migrations wasn't worth it for me, so I went with a regular multi tenant database (tenant_id in every table), and then get the tenant_id in the header. I added an @access_control decorator and made an extra check not to allow users to make requests for different tenants as well (along side the regular access control).

**Comment by skokado** [comment]
@ParticleDuality @hacen-ai @lowercase00 
I've faced a similar use case.
I think, this is more of a SQLAlchemy usage, not FastAPI.

My approach is to use django-tenants to make the database multiple schema, while dynamically switching schemas from SQLAlchemy as well.
See also:
- [Multi-Tenancy Schema Translation for Table objects](https://docs.sqlalchemy.org/en/14/changelog/migration_11.html#multi-tenancy-schema-translation-for-table-objects)
- [schema_translate_map is ignored on refresh in MSSQL](https://github.com/sqlalchemy/sqlalchemy/discussions/5978#discussioncomment-406283)

This is just a sample application, but I hope it will be helpful :)
https://github.com/skokado/FastAPI-with-django-tenants

By using the dependency  `app.dependencies.get_db` to specify the schema corresponding to the tenant, it is able to use different data without being aware of the tenant in the router (`main.py`).

**Comment by Udayaprasad** [comment]
@skokado ,

I have implemented the multi-tenancy by database, but how could we achieve the multi-tenancy using different authentication schemes? 

Like in keycloak we use the realm to isolate one customer users/roles data from another. Is there a way to dynamically load the  `swagger_ui_init_oauth` information based on realm inputs and authenticate the specific user against the specific realm configuration?
