### ISSUE TITLE
Did you know Netflix uses FastAPI?

### ISSUE THREAD

**Issue by retnikt** [tiangolo/fastapi#1337]
Off-topic, but I recently discovered @Netflix's Dispatch, and poking around in the source I discovered that most of the app is written with FastAPI! I thought you might like to know so you could use it for promotion and potentially reach out for a testimonial to add to the README. (if you didn't already know they used it)

**Comment by sm-Fifteen** [comment]
Guess we have **kevgliss** and **mvilanova** (not sure I actually want to ping them) to thank for that. It could be worth reaching out to them, yeah, seeing FastAPI being used in the wild is always cool.

@tiangolo, have you seen this?

**Comment by michael0liver** [comment]
@tiangolo shared it on twitter a while ago. +1 could be added to the testimonials.

**Comment by tiangolo** [comment]
Thanks! Yeah, I had seen the blog post but hadn't had the time to add it to the docs and external links.

I recently did :smile: 

...also, cool issue number you got :sunglasses:
