### ISSUE TITLE
[FEATURE] Should jsonable_encoder use by_alias=True by default?

### ISSUE THREAD

**Issue by dbichko** [tiangolo/fastapi#135]
Hello,

At the moment, jsonable_encoder sets `by_alias=False`, while the encoder for OpenAPI uses `by_alias=True`. This causes somewhat undesirable behavior: the API definition does not match the serialized model. And generally limits the usefulness of aliases.

I saw the workaround in #31, but I am wondering if the current default is ever the expected/preferable behavior?

Thank you.

**Comment by tiangolo** [comment]
I agree with you.

I just implemented it in PR #168, including tests.

It is now available in version `0.17.0` (just released).

**Comment by tiangolo** [comment]
As this is now fixed, I'll close this issue now. But feel free to add more comments or create new issues.
