### ISSUE TITLE
Add unknown parameters to a GET request

### ISSUE THREAD

**Issue by lsabi** [tiangolo/fastapi#1388]
### Is your feature request related to a problem

I don't think it's a problem. It's a nice and useful feature that I don't find mentioned neither on the docs nor by searching.

### The solution you would like

The basic idea is to have some parameters of GET requests that are not known in advance. It would be nice to be able to access them, along with predefined parameters (as in this case is `limit`)

```
@app.get("/")
async def my_func(limit: int = 0, **kwargs):
    var1 = kwargs["var1"]
    print("Limit is {}".format(limit))
    return {"data": var1}

# Generate a request to the url http://my_domain?var1=hi&var2=hello&limit=10
resp = testclient.get("my_domain", params={"var1": "hi", "var2": "hello", "limit": 10})
assert resp.json()["data"] == "hi"
```

### Describe alternatives you've considered

I thought about accessing the raw request, but I can't find how. Also it's not a clean way of doing it.

### Additional context

Instead of `**kwargs`, another name may be used, such as `params`

**Comment by phy25** [comment]
Namespaced variable would be safer here I guess. Alternatively you could just use [`request.query_params`](https://fastapi.tiangolo.com/advanced/using-request-directly/).

**Comment by obataku** [comment]
I've had fine mileage with `query_params` although it's worth noting that `starlette.datastructures.QueryParams` is a multi-dict and attempting to use it as a conventional `Mapping` may lead to missing some values for repeated keys

**Comment by lsabi** [comment]
@phy25 how did I miss that? Anyway thanks.

As @obataku is noting, for cases where I have a request URL such as  `http://my_domain?var1=hi&var2=hello&var1=hello&limit=10` , one would not get the full list of values, only the last value.

In my opinion it is a useful feature, as my api relies on some parameters that may not be known before.

**Comment by obataku** [comment]
@lsabi you **can** get all of the values, just not using it naively like any old `Mapping`. `query_params` is an [`ImmutableMultiDict`](https://github.com/encode/starlette/blob/master/starlette/datastructures.py#L277) structure with methods like `getlist(key)` and `multi_items()`

**Comment by lsabi** [comment]
@obataku oh yes, that's true. Didn't know that.

Anyway it works, although it is quite verbose. But it's enough. Thanks

**Comment by tiangolo** [comment]
Thanks for the help here everyone! :clap: :bow: 

Thanks for reporting back and closing the issue @lsabi  :+1:
