### ISSUE TITLE
🌍 Translations coordination (list of translations)

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/fastapi#1497]
Here are the issues coordinating the translations to each language:

* Portuguese: https://github.com/tiangolo/fastapi/issues/1211
* Spanish: https://github.com/tiangolo/fastapi/issues/1218
* Chinese: https://github.com/tiangolo/fastapi/issues/1228
* Russian: https://github.com/tiangolo/fastapi/issues/1362
* Italian: https://github.com/tiangolo/fastapi/issues/1556
* Japanese: https://github.com/tiangolo/fastapi/issues/1572
* Ukrainian: https://github.com/tiangolo/fastapi/issues/1748
* Turkish: https://github.com/tiangolo/fastapi/issues/1892
* French: https://github.com/tiangolo/fastapi/issues/1972
* Korean: https://github.com/tiangolo/fastapi/issues/2017
* Persian: https://github.com/tiangolo/fastapi/issues/2041
* Polish: https://github.com/tiangolo/fastapi/issues/3169
* German: https://github.com/tiangolo/fastapi/issues/3716
* Indonesian: https://github.com/tiangolo/fastapi/issues/3717
* Azerbaijani: https://github.com/tiangolo/fastapi/issues/3994
* Dutch: https://github.com/tiangolo/fastapi/issues/4701
* Uzbek: https://github.com/tiangolo/fastapi/issues/4883
* Swedish: https://github.com/tiangolo/fastapi/issues/5146
* Hebrew: https://github.com/tiangolo/fastapi/issues/5157
* Tamil: https://github.com/tiangolo/fastapi/issues/5434
* Arabic: https://github.com/tiangolo/fastapi/issues/3349
---

Note: this meta-issue is here because GitHub only allows a limited number of issues to be pinned, so I can't pin all of them. I'll update it here when there's a new language.

**Comment by sm-Fifteen** [comment]
Couldn't we just have a tag for translations instead?

**Comment by tiangolo** [comment]
Having a specific issue for translations of a specific language lets people coordinate which section each one is working on.

**Comment by sm-Fifteen** [comment]
Oh, sure, for individual languages, yeah, but I meant if it was necessary to have a meta-issue for those instead of just a 4th tag for translations?

**Comment by csr** [comment]
I could help with some Italian translations. Is this something you may be interested in?

**Comment by tiangolo** [comment]
That would be great @csr ! :rocket: 

I think you would probably be the best to judge, how comfortable would you think other Italians are with docs in English?

For example, I know that in Latin America many developers are not very comfortable with English and need and benefit from Spanish/Portuguese docs.

I understand it's similar in China. How would you think it is in Italy?

**Comment by csr** [comment]
Yes, I think it would be useful to have an Italian translation, as that can help more Italian developers better work with the FastAPI framework. I've created a new issue [here](https://github.com/tiangolo/fastapi/issues/1556) so that we Italian speakers can all coordinate the translation efforts.

**Comment by Kludex** [comment]
https://en.wikipedia.org/wiki/List_of_countries_by_English-speaking_population

**Comment by acidjunk** [comment]
If you need help for Dutch/NL : I will be happy to help.

**Comment by shidenko97** [comment]
If you need some help with Russian/Ukrainian translation - I will be happy to help)

**Comment by shidenko97** [comment]
I've been starting to make Ukrainian translation at the index page.

**Comment by csr** [comment]
@shidenko97 If you haven't already, I believe you can create a separate thread for the language you're translating, as you can see from the links in the first post here :)

**Comment by shidenko97** [comment]
> If you haven't already, I believe you can create a separate thread for the language you're translating, as you can see from the links in the first post here :) Once you create a thread, you can post your progress there.

Thanks for your advice) I've did [it](https://github.com/tiangolo/fastapi/issues/1748) right now

**Comment by Jatzek3** [comment]
I would like to make polish translation for documentation. I'm pretty new to open source. :) Can someone contact me for some advice and guidance?
My discord:Jatzek3#9820 
My skype: jatzek3x

**Comment by umitkaanusta** [comment]
If you're interested in helping me translate FastAPI docs to Turkish, check this issue 👇 

#1892

**Comment by hard-coders** [comment]
I've been starting to translate the Korean language.
If you're interested, please check #2017 😃

**Comment by BTruer** [comment]
I can translate to Hindi? is this needed?

**Comment by eseglem** [comment]
Have you considered using something like https://lokalise.com/ for translations? They appear to offer free accounts to open source. It might be worth a look at least. I only know about it because I saw it in another repo: https://github.com/hacs/frontend/blob/main/.github/workflows/ReleaseActions.yml they pull the docs from Lokalize as part of the release process and build everything that way. 

It might be more for translating text within an app than actual documentation though. I am not sure.

**Comment by vicknguyen1992** [comment]
Awesome project! If you 're interesting, I'm very pleasure to make Vietnamese translation.

**Comment by Kamrulhasan12345** [comment]
Guys, I am eager to add `Bengali`. I am preparing the translations but what I need to do after being done with translating?

**Comment by ycd** [comment]
@Kamrulhasan12345 , you can start from [here](https://fastapi.tiangolo.com/contributing/#translations).

**Comment by neternefer** [comment]
Started Polish translation project. You can track it here -> #3169

**Comment by Hultner** [comment]
If anyone is interested in making a Swedish translation I'd be happy to review and help such efforts. I unfortunately don't have the bandwidth to be the main driver of such a project though.

**Comment by zarinpy** [comment]
guys what about the exception messages inside the framework should we handle this on our own?

**Comment by oillypump** [comment]
hello,
is there any guidance/procedure which I can read to contribute?
Id love to could help translate to Indonesia.

**Comment by hard-coders** [comment]
@oillypump 
See https://fastapi.tiangolo.com/contributing/
and you should check [Indonesian translate issue](https://github.com/tiangolo/fastapi/issues/3717)

**Comment by tiangolo** [comment]
Translations are now coordinated in GitHub Discussions https://github.com/tiangolo/fastapi/discussions/categories/translations :tada: 

I also updated the bot (GitHub Action) to put the notifications for new translations there, and to update comments for PRs that are done. :rocket: :coffee: 

Given that, I'll now close this issue. :sunglasses:
