### ISSUE TITLE
openapi_url incorrect from behind reverse proxy

### ISSUE THREAD

**Issue by qubidt** [tiangolo/fastapi#15]
The use case:

I'm running FastAPI behind a nginx reverse proxy, at the path `http://localhost/api/`. The documentation front ends (swagger and redoc) are expecting `openapi.json` at `http://localhost/openapi.json` but it's actually routed at `http://localhost/api/openapi.json`.

Setting `openapi_url` to `/api/openapi.json` also changes the `openapi.json` path, so now it's looking for (through the proxy) `http://localhost/api/api/openapi.json`.

Ideally, it'd be great if we could specify the "public path" for the api. That's how e.g. vue does it

**Comment by tiangolo** [comment]
Thanks for the report. I'll check it, I agree that this is probably the most straightforward way to solve it, with a "public path".

This is also (probably) related to #8 

I'll check it.

**Comment by qubidt** [comment]
Yup, sorry, I didn't notice #8. This is indeed a duplicate of that issue. Would you like me to close this one?

**Comment by tiangolo** [comment]
This should be solved by PR #26 by @kabirkhan . It is released as `0.4.0`, the new docs are here: https://fastapi.tiangolo.com/tutorial/sub-applications-proxy/ :tada: :rocket: 

Let me know if it works for you.

**Comment by qubidt** [comment]
Love it! I'll test it out asap!

**Comment by tiangolo** [comment]
Great! Thanks for reporting back and closing the issue.

**Comment by RmStorm** [comment]
> This should be solved by PR #26 by @kabirkhan . It is released as `0.4.0`, the new docs are here: https://fastapi.tiangolo.com/tutorial/sub-applications-proxy/ tada rocket
> 
> Let me know if it works for you.

For anyone coming across this, the new link for the tutorial is here:
https://fastapi.tiangolo.com/advanced/sub-applications-proxy/

**Comment by Fogapod** [comment]
Even newer link :smile:: https://fastapi.tiangolo.com/advanced/behind-a-proxy/
