### ISSUE TITLE
[FEATURE] Start translate to Japanese

### ISSUE THREAD

**Issue by ryuckel** [tiangolo/fastapi#1503]
I want to translate document to Japanese.
Can I translate document by following below URL?
https://fastapi.tiangolo.com/contributing/#translations

If it is no problem, I will make PR after translate index.md.

**Comment by tiangolo** [comment]
That's awesome! Maybe you can create an issue like this one: https://github.com/tiangolo/fastapi/issues/1218

To track who is translating a page to Japanese. And I'll add it to the pinned issue here: https://github.com/tiangolo/fastapi/issues/1497

**Comment by ryuckel** [comment]
@tiangolo 
Thanks!
I created an issue #1572 for tracking.

**Comment by tiangolo** [comment]
Great! :rocket: I just added it to the pinned issue.

**Comment by ryuckel** [comment]
Thanks!

**Comment by tiangolo** [comment]
Now that we have https://github.com/tiangolo/fastapi/issues/1572 :tada:  to track Japanese translations, I'm going to close this issue.
