### ISSUE TITLE
[BUG] Override successful response

### ISSUE THREAD

**Issue by Kludex** [tiangolo/fastapi#1528]
### Describe the bug

On the `responses` field in the route decorator we can't override the description of the successful response. Even on the tutorial we can see it: https://fastapi.tiangolo.com/advanced/additional-responses/

### To Reproduce

![image](https://user-images.githubusercontent.com/7353520/83968295-81a19f80-a8c8-11ea-8b2e-cce027582d17.png)
![image](https://user-images.githubusercontent.com/7353520/83968299-88301700-a8c8-11ea-8d42-d0d9f2a1ec3c.png)

### Expected behavior

We should have "Item requested by ID" in the description field for the code 200.

**Comment by Kludex** [comment]
We can use `response_description`, but we can't override with `responses` so the BUG still remains.

**Comment by fabrizzioalco** [comment]
Hey i would like to contribute and perhaps some mentorship. This would be my first contribution to open source

**Comment by tiangolo** [comment]
@fabrizzioalco that's great!

You should probably:

* Make sure to read and follow the tutorial and get familiar with using the framework and how it works
* You could help others here and in the Gitter chat, many questions just need a bit of guidance and help. And by helping others you would get a lot more expertise with FastAPI.
* If you speak another language apart from English, you could help with the translations to your language, that's something that only a few can do (and I can't, as I don't speak all the languages :sweat_smile: ): https://fastapi.tiangolo.com/contributing/#translations
    * And as by doing that you would be reading the documentation, having to understand it, and re-writing it in your language, you would probably learn a lot of the concepts and how it all works.
* If you want to contribute code to FastAPI itself, check the contributing guide: https://fastapi.tiangolo.com/contributing/

**Comment by rkbeatss** [comment]
@tiangolo if there has not been any PRs yet, i have been thinking of looking into contributing to this issue. what do you think?

**Comment by Kludex** [comment]
@rkbeatss I can say that there are no PRs solving it for now, I think you can safely work on it.

**Comment by fabrizzioalco** [comment]
Please, be my guest. I had some troubles so i can't work on this @rkbeatss

**Comment by fabrizzioalco** [comment]
Later i would contribute on something else

**Comment by tiangolo** [comment]
Thanks for the report and for the discussion here everyone! :coffee: 

And thanks @rkbeatss for the initial implementation! :cake: 

This should be fixed in https://github.com/tiangolo/fastapi/pull/1577

Available in FastAPI version `0.58.0` :tada:

**Comment by kevlarr** [comment]
Wow, this is fantastic - I literally just ran into this bug (was on 0.54) so I was *really* excited to see it fixed. I couldn't use `response_model` in one of my handlers because the response was large as raw data, and serializing it to pydantic classes increased response time by like 4x. Being able to skip runtime validation but *still* have documentation is fantastic.

**Comment by kevlarr** [comment]
@tiangolo Side note: Thanks for including the version number that included the bug fix. As a busy, busy dev it makes my life much easier knowing immediately what version to bump to, so that was really appreciated.
