### ISSUE TITLE
Documentation uses “subtype” incorrectly

### ISSUE THREAD

**Issue by yurikhan** [tiangolo/fastapi#1545]
The documentation uses the term “subtype” in the context of generic `typing` types.

E.g. [here][1]:

[1]: https://fastapi.tiangolo.com/python-types/#lists

> As the list is a type that takes a "subtype", you put the subtype in square brackets:
 
The word *subtype* already has a defined meaning in the type theory; it is very close to *subclass* and Liskov Substitutability Principle, i.e. it declares a relationship between two types such that an instance of the subtype can be used in every scenario involving the supertype. `str` is most definitely *not* a subtype of `List`. (`List[str]`, however, is.)

The correct term for the thing in brackets is “generic type arguments” or “type args” for short.

**Comment by tiangolo** [comment]
Thanks! Good point. I think I was using the term from the internal code in Pydantic :sweat_smile: 

Anyway, I just updated it to "type parameters" which is used in the mypy docs for Generics: https://mypy.readthedocs.io/en/stable/generics.html#generics :rocket:
