### ISSUE TITLE
Documentation Italian 

### ISSUE THREAD

**Issue by mikeleg** [tiangolo/fastapi#1546]
It's possible to translate in Italian the documentation?

**Comment by csr** [comment]
I could also help with the Italian translation efforts if needed!

**Comment by mikeleg** [comment]
Mee too

**Comment by csr** [comment]
Ciao @mikeleg, I've just opened a new thread for the Italian translation discussions [here](https://github.com/tiangolo/fastapi/issues/1556). Let's get this done 💪 🇮🇹

**Comment by tiangolo** [comment]
Awesome! :rocket: :tada: 

Thanks for your help! :cake: :bow: 

I'll then close this now. Let's continue tracking the progress in https://github.com/tiangolo/fastapi/issues/1556 :nerd_face:
