### ISSUE TITLE
Get internal route string from request

### ISSUE THREAD

**Issue by basepaws-tech** [tiangolo/fastapi#1559]
Is it possible to obtain the internal route string from a request? 

If I have a route: "/api/{name}". And I request "/api/myName", I can get the url by request.url. But is it possible to the get the internal route string: "/api/{name}" somehow?

**Comment by molto0504** [comment]
@basepaws-tech try this

```
app = FastAPI()
for route in app.routes:
    print(route.path)
```

**Comment by tiangolo** [comment]
Hey, please keep and follow the issue template, you can edit this issue or create a new one following the template here: https://github.com/tiangolo/fastapi/issues/new?assignees=&labels=question&template=question.md&title=

**Comment by obataku** [comment]
@basepaws-tech: from just a request, no, not readily; it's possible using a custom `APIRoute` class, however, considering the path template is stored in its attributes: https://github.com/tiangolo/fastapi/blob/master/fastapi/routing.py#L303-L306
