### ISSUE TITLE
Update docs with parameters that default to None to use Optional

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/fastapi#1561]
### First check

* [x] I added a very descriptive title to this issue.
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [x] After submitting this, I commit to:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * Or, I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Example

Here's a self-contained [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with my use case:

```Python
from fastapi import FastAPI, Query

app = FastAPI()


@app.get("/")
def read_root(q: str = Query(None)):
    return {"q": q.lower()}
```

### Description

* Open the editor with that code, similar to many examples in the docs.
* It's quite probable that the editor won't complain that `q` can be `None` and that `q.lower()` could raise an error.

### The solution you would like

I would like the examples in the docs to use `Optional`:

```Python
from typing import Optional

from fastapi import FastAPI, Query

app = FastAPI()


@app.get("/")
def read_root(q: Optional[str] = Query(None)):
    return {"q": q.lower()}
```

By using `Optional` the editor would be able to warn that `q.lower()` could raise an error if `q` is `None`.

### Describe alternatives you've considered

To leave it as is.

### Environment

* OS: [e.g. Linux / Windows / macOS]: All (docs)
* FastAPI Version [e.g. 0.3.0]: 0.56.0

To know the FastAPI version use:

```bash
python -c "import fastapi; print(fastapi.__version__)"
```

* Python version: All (docs)

To know the Python version use:

```bash
python --version
```

### Additional context

I was waiting to first introduce `Optional` in the docs, but it was done in https://github.com/tiangolo/fastapi/pull/1377 :tada: 

The new docs are here: https://fastapi.tiangolo.com/python-types/#optional

Now it's a good moment to update all the examples that have a default of `None` in all the docs to also use `Optional`.

**Comment by kx-chen** [comment]
I'll be working on this with @chrisngyn

**Comment by BCasaleiro** [comment]
I believe this was already solved with #1644 being merged to `master`. Should this issue be closed @tiangolo?

**Comment by Illwatermelon** [comment]
Thanks a lot!

**Comment by meysam81** [comment]
@tiangolo 
Is this issue still accepting contributors?
You mentioned [here](https://github.com/tiangolo/fastapi/pull/1574#issuecomment-650802924) that you merged another branch.

**Comment by mdaj06** [comment]
@tiangolo Is this available to take up?

**Comment by Darkflame72** [comment]
@tiangolo is this fixed or do you want someone to take it up a quick search through the docs makes it look all solved?

**Comment by Kludex** [comment]
This issue was **solved** on https://github.com/tiangolo/fastapi/pull/1644

To confirm I've made a quick search and the docs are following the request on this issue. :nerd_face:

**Comment by azimovMichael** [comment]
Is this still up for grabs?

**Comment by M549233** [comment]
@azimovMichael

**Comment by Liliyord** [comment]
> ### First check
> * [x]  I added a very descriptive title to this issue.
> * [x]  I used the GitHub search to find a similar issue and didn't find it.
> * [x]  I searched the FastAPI documentation, with the integrated search.
> * [x]  I already searched in Google "How to X in FastAPI" and didn't find any information.
> * [x]  I already read and followed all the tutorial in the docs and didn't find an answer.
> * [x]  I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
> * [x]  I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
> * [x]  I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
> * [x]  After submitting this, I commit to:
>   
>   * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
>   * Or, I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
>   * Implement a Pull Request for a confirmed bug.
> 
> ### Example
> Here's a self-contained [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with my use case:
> 
> ```python
> from fastapi import FastAPI, Query
> 
> app = FastAPI()
> 
> 
> @app.get("/")
> def read_root(q: str = Query(None)):
>     return {"q": q.lower()}
> ```
> 
> ### Description
> * Open the editor with that code, similar to many examples in the docs.
> * It's quite probable that the editor won't complain that `q` can be `None` and that `q.lower()` could raise an error.
> 
> ### The solution you would like
> I would like the examples in the docs to use `Optional`:
> 
> ```python
> from typing import Optional
> 
> from fastapi import FastAPI, Query
> 
> app = FastAPI()
> 
> 
> @app.get("/")
> def read_root(q: Optional[str] = Query(None)):
>     return {"q": q.lower()}
> ```
> 
> By using `Optional` the editor would be able to warn that `q.lower()` could raise an error if `q` is `None`.
> 
> ### Describe alternatives you've considered
> To leave it as is.
> 
> ### Environment
> * OS: [e.g. Linux / Windows / macOS]: All (docs)
> * FastAPI Version [e.g. 0.3.0]: 0.56.0
> 
> To know the FastAPI version use:
> 
> ```shell
> python -c "import fastapi; print(fastapi.__version__)"
> ```
> 
> * Python version: All (docs)
> 
> To know the Python version use:
> 
> ```shell
> python --version
> ```
> 
> ### Additional context
> I was waiting to first introduce `Optional` in the docs, but it was done in #1377 🎉
> 
> The new docs are here: https://fastapi.tiangolo.com/python-types/#optional
> 
> Now it's a good moment to update all the examples that have a default of `None` in all the docs to also use `Optional`.

**Comment by tiangolo** [comment]
Ah, I forgot to close my own issue! Haha. This is done now. ✅ 

Thanks for the interest and discussion everyone! ☕
