### ISSUE TITLE
Using `Depends` for injecting a dependency in SQLAlchemy ORM class method fails

### ISSUE THREAD

**Issue by townegr** [tiangolo/fastapi#1615]
Application dependencies:
```
[tool.poetry.dependencies]
python = "^3.6"
fastapi = "^0.55.1"
uvicorn = "^0.11.5"
sqlalchemy = "1.3.17"
```
I'm interested in leveraging the **Dependency Injection** system via `Depends` within a declarative model such that I can directly implement class methods on the `Query` object (`sqlalchemy.orm.query.Query`). I have constructed the following ORM mapping and route:
```Python
from fastapi import APIRouter, Depends
from sqlalchemy import Column, DateTime, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, sessionmaker
from app.etc.config import engine


SessionLocal = sessionmaker(bind=engine())
Base = declarative_base()
router = APIRouter()


def query_session():
    try:
        db = SessionLocal()
        yield db
    finally:
        db.close()


class Post(Base):
    __tablename__ = 'posts'

    id = Column(Integer, primary_key=True)
    title = Column(String)
    author = Column(String)
    created_at = Column(DateTime)

    @classmethod
    def all(class_, db: Session = Depends(query_session)):
        return db.query(class_).all()


@router.get("/posts")
async def get_posts():
    return Post.all()
```
The server returns the following exception:
```
INFO:     127.0.0.1:50934 - "GET /posts HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
.
.
.
return db.query(class_).all()
AttributeError: 'Depends' object has no attribute 'query'
```
I recognize this implementation is somewhat unorthodox but my intent is to group frequently used getters within the declarative ORM class. Common practices indicate to pass the session to the _path operation function_ parameters.
```Python
@router.get("/posts")
async def get_posts(db: Session = Depends(query_session)):
    return db.query(Post).all()
```
However, if my initial approach is feasible, I would appreciate some guidance. Thank you in advance for your response.

**Comment by tiangolo** [comment]
`Depends()` is a utility for FastAPI, not for SQLAlchemy classes.

If you want to put logic in the SQLAlchemy class you should still pass the session, so it would be something like:

```Python
class Post(Base):
    __tablename__ = 'posts'

    id = Column(Integer, primary_key=True)
    title = Column(String)
    author = Column(String)
    created_at = Column(DateTime)

    @classmethod
    def all(class_, db: Session):
        return db.query(class_).all()
```

And you would call it with something like:

```Python
@router.get("/posts")
def get_posts(db: Session = Depends(query_session)):
    return Post.all(db)
```

Nevertheless, I would suggest you keep the utilities and functions to handle data apart from the models.
