### ISSUE TITLE
How to request with authorize token when the one of my APIs is simple without Oauth2

### ISSUE THREAD

**Issue by Uievil** [tiangolo/fastapi#1632]
### Example
```python
@router.get("/items", name="my api", response_model=R, description="something....")
async def read_items(request: Request, para: str = Query(None, description="my key param")):
    return [{"a": 1}, {"b": 2}, {"c": para}]
```
### Description
Hi,
 thank you for your work on FastAPI.  I have a problem that can't be solved by searching in Google. Here are several APIs, including Oauth2 to use, and one of them is simple without authorize like `Example` above, in other words `it doesn't request with Authorize header on OpenAPI docs`. So how could I `request it with Authoirze header by OpenAPI docs`, and I would appreciate it if you could give me some advice. Forgive me for my poor English :)
Thanks~

**Comment by tiangolo** [comment]
Unfortunately, the documentation for all the security utilities is not complete, but you can probably use `HTTPBearer`: https://github.com/tiangolo/fastapi/blob/master/fastapi/security/http.py#L94
