### ISSUE TITLE
How can i use fastapi to predict the response directly into an html  file 

### ISSUE THREAD

**Issue by hunaidkhan2000** [tiangolo/fastapi#1686]
I have a flask app where i am using home.html file to fetch the entered values by user and once they enter the value it goes into the app and model predicts the value. 
Predictions are displayed on the webpage itself using render_template of flask . How can i do the same with fastapi.

My flask app code is - 
```
@app.route('/predict',methods=['POST'])
def predict():
    int_features = [x for x in request.form.values()]
    final = np.array(int_features)
    data_unseen = pd.DataFrame([final], columns = cols)
    prediction = predict_model(model, data=data_unseen, round = 0)
    prediction = int(prediction.Label[0])
    return render_template('home.html',pred='Expected Bill will be {}'.format(prediction))
```
and home html file which is in template folder 

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Predict Insurance Bill</title>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Hind:300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='./style.css') }}">
  
</head>

<body>
 <div class="login">
	<h1>Predict Insurance Bill</h1>

     <!-- Form to enter new data for predictions  -->
    <form action="{{ url_for('predict')}}"method="POST">
      <input type="text" name="age" placeholder="Age" required="required" /><br>
    	<input type="text" name="sex" placeholder="Sex" required="required" /><br>
        <input type="text" name="bmi" placeholder="BMI" required="required" /><br>
        <input type="text" name="children" placeholder="Children" required="required" /><br>
        <input type="text" name="smoker" placeholder="Smoker" required="required" /><br>
        <input type="text" name="region" placeholder="Region" required="required" /><br>

        <button type="submit" class="btn btn-primary btn-block btn-large">Predict</button>
    </form>

   <br>
   <br>
  
   
 </div>
 {{pred}}

</body>
</html>
```

**Comment by othi** [comment]
You can use the same templating engine as Flask.

Have a look at the documentation: https://fastapi.tiangolo.com/advanced/templates/

**Comment by hunaidkhan2000** [comment]
@othi  I have tried this method unfortunately it does not open web page and every time I start the app it does not redirect to the HTML page. Also while manually opening HTML page and entering values it gives error that your file not found even though all the required files are in the Templates folder

**Comment by tiangolo** [comment]
Sorry @hunaidkhan2000 but I can't convert the code for you. You will probably need to use redirects https://fastapi.tiangolo.com/advanced/custom-response/?h=+redirect#redirectresponse

And one *GET path operation* returning your Jinja2 HTML template: https://fastapi.tiangolo.com/advanced/templates/, and one *POST path operation* receiving the HTML form.

But you will have to read the tutorial, and understand how to use forms, etc: https://fastapi.tiangolo.com/tutorial/request-forms/
