### ISSUE TITLE
How to flush cache with many processes?

### ISSUE THREAD

**Issue by rspadim** [tiangolo/fastapi#1695]
Hi folks

I have a cache (dict key value) + redis cache with my fastapi app

Since i’m doing process level cache (with small ttl vs redis ttl) i want know if is possible to make a flush cache process to flush the internal process cache of all process running my app

I’m using gunicorn+uvicorn and a k8s cluster running many replicas

The idea is create the inter process flush, and at a second stage propagate the flush to all replicas (but this is the easy part of the problem)

Thanks!

**Comment by rspadim** [comment]
(My first option is `HUP` gunicorn, but i don’t know if it’s “ok”)

**Comment by tiangolo** [comment]
Hey, I'm not sure I understand the question, I think maybe it's not related to FastAPI.

But if you still have problems, please create a new issue following the template.
