### ISSUE TITLE
Include breaking changes in changelog

### ISSUE THREAD

**Issue by ArcLightSlavik** [tiangolo/fastapi#1767]
Version 0.59.0 introduced a small breaking change where the parameter 'openapi prefix' was removed meaning code below wasn't working:

```
openapi_schema = get_openapi(
    version=1.0,
    title='A title',
    description='A description',
    openapi_prefix='',
    routes=app.routes,
)
```
I think it would be useful to have a separate section in the release notes where these types of changes are listed

Example:
 
<img width="798" alt="Screenshot 2020-07-22 at 11 51 41" src="https://user-images.githubusercontent.com/31127044/88156176-bae06580-cc11-11ea-8ce9-8dac41c238dd.png">

It is similar to how angular does it (https://next.angular.io/guide/updating-to-version-10)

**Comment by tiangolo** [comment]
Thanks! Good idea. I started using sections like that for the latest release notes: https://fastapi.tiangolo.com/release-notes/ .

If you think some previous releases deserve separated sections, I would accept PRs updating them.

**Comment by ArcLightSlavik** [comment]
![Alt Text](https://media.giphy.com/media/yyZRSvISN1vvW/giphy.gif)
