### ISSUE TITLE
ImportError: cannot import name 'Field' from 'pydantic'

### ISSUE THREAD

**Issue by rbcabreraUPM** [tiangolo/fastapi#1780]
Hi, I encountered an issue in the API docs and it was reported and address with FastAPI version 0.60.1.

right now when I ran my code, I encounter this one 

`ImportError: cannot import name 'Field' from 'pydantic'`

how do I translate this one

```
from pydantic import BaseModel, Field
from enum import Enum
from typing import List

class PriorityGatewaySchema(BaseModel):
    gatewayName:  str = Field(..., min_length=0, max_length=20, title="OTP Gateway Name")
    gatewayCode:  str = Field(..., min_length=0, max_length=20, title="OTP Code")

```

**Comment by Kludex** [comment]
I'm not on my computer, but that's a Pydantic issue. Can you upgrade the Pydantic version and see if the problem still remains?

**Comment by rbcabreraUPM** [comment]
I actually did. still the same.

**Comment by MacMacky** [comment]
Hi, @rbcabreraUPM, Did you try using this
```py
from pydantic.fields import Field
```

**Comment by Kludex** [comment]
@rbcabreraUPM Your implementation works just fine here. With Pydantic 1.5.1 and 1.6.1, and the same FastAPI version. jfyk

**Comment by rbcabreraUPM** [comment]
right now Im getting an error of  **TypeError: __init__() got an unexpected keyword argument 'title'**

**Comment by MacMacky** [comment]
@rbcabreraUPM I think you need to update your __pydantic__ version.

**Comment by rbcabreraUPM** [comment]
> @rbcabreraUPM I think you need to update your **pydantic** version.

already using 1.6.1

**Comment by rbcabreraUPM** [comment]
this wasn't an issue before using older versions of pydantic and fastapi then the swagger got buggy. after upgrading to the latest versions, I got this issue

**Comment by tiangolo** [comment]
It seems like you got a different error than the original, if you are still having issues, please create a simple example that demonstrates the error.

**Comment by magnusja** [comment]
I have the exact same problem with pydantic 1.7.3 and flask 0.62, any solution?

**Comment by magnusja** [comment]
Just noticed this works in my dock container but not locally on my mac...

**Comment by tiangolo** [comment]
If you are having this type of issue, it's most probably that you don't have your environment correctly set up.

The `python` that is executed should be the same one that was used to install Pydantic, otherwise, it won't be able to find it.

I haven't added docs about environments to FastAPI but you can check about that and how to test it all in the docs for SQLModel: https://sqlmodel.tiangolo.com/tutorial/#create-a-python-virtual-environment
