### ISSUE TITLE
Returning List in ResponseModel triggers type alert

### ISSUE THREAD

**Issue by victoraugustolls** [tiangolo/fastapi#1850]
### First check

* [X] I added a very descriptive title to this issue.
* [X] I used the GitHub search to find a similar issue and didn't find it.
* [X] I searched the FastAPI documentation, with the integrated search.
* [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [X] I already read and followed all the tutorial in the docs and didn't find an answer.
* [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [X] After submitting this, I commit to one of:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Description

When including a `List` in `response_model`, pycharm show this alert:

![image](https://user-images.githubusercontent.com/7843637/89673435-b9bf6180-d8bc-11ea-8b40-00f99b5c346a.png)

Is this expected?

### Environment

* OS: Linux
* FastAPI Version: 0.58.0
* Python version: 3.8.5

**Comment by manuelfedele** [comment]
I confirm that I can reproduce this behavior with pycharm professional.

**Comment by tiangolo** [comment]
Hey there, this was solved in some release at some point, could you check if you still have errors?

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
