### ISSUE TITLE
Simplify internal hl_lines for docs examples

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/fastapi#1859]
### First check

* [x] I added a very descriptive title to this issue.
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [x] After submitting this, I commit to:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * Or, I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Description

The Markdown docs have a lot of inline code sections dynamically included.

Many of them use `hl_lines` to highlight lines, for example, to highlight from lines 5 to 10, and lines from 23 to 25:

<pre>
```Python hl_lines="5 6 7 8 9 10 23 24 25"
{!../../../docs_src/how_to_do_x/tutorial003.py!}
```
</pre>

In a recent PR, @rkbeatss made me realize that `hl_lines` now supports ranges of highlighted lines. So, the example above could be:

<pre>
```Python hl_lines="5-10 23-25"
{!../../../docs_src/how_to_do_x/tutorial003.py!}
```
</pre>

which is a lot easier to understand and maintain.

### The solution you would like

I would like to replace all those `hl_lines` in the docs that highlight a range of lines with the new range syntax to make them easier to maintain and understand.

### Describe alternatives you've considered

Leaving it as is, but all the updates for those docs are quite difficult as it's not obvious which numbers belong to a range and which are individual lines.

Even more, when a line on the top is added (or removed), all those ranges change, increasing or decreasing. The new syntax would be a lot easier to update. With the current syntax (before the update) it's very easy to miss or break some of those line highlights.

**Comment by tiangolo** [comment]
This was handled by @la-mar on https://github.com/tiangolo/fastapi/pull/1863 :tada: :rocket:

**Comment by pranish512** [comment]
Just checking the issues
