### ISSUE TITLE
Add imports of Starlette datastructures for type annotating Request

### ISSUE THREAD

**Issue by jamescurtin** [tiangolo/fastapi#1871]
### First check

* [x] I added a very descriptive title to this issue.
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [x] After submitting this, I commit to:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * Or, I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Description

As a user of FastAPI, I want to type annotate functions that return properties of `fastapi.Request` without needing to import `starlette`, in keeping with the [documentation that states](https://fastapi.tiangolo.com/deployment/#about-starlette):

> You shouldn't pin the version of starlette.

### The solution you would like

Instead of the current state, where Starlette must be a pinned dependency to be able to use type annotations for the properties of `Request`:

```python
from fastapi import Request
from starlette.datastructures import URL  # Can only import URL from starlette; it isn't exposed in FastAPI

def example_get_url_from_request(request: Request) -> URL:
    return request.url
```

Instead, import all necessary properties in `fastapi.requests` such that the example could be updated to:

```python
from fastapi import Request
from fastapi.requests import URL

def example_get_url_from_request(request: Request) -> URL:
    return request.url
```

**Comment by tiangolo** [comment]
Thanks for the detailed report and for the fix in https://github.com/tiangolo/fastapi/pull/1872 ! :clap: :cake: 

This will be available later today in FastAPI version `0.68.0` 🔖🎉
