### ISSUE TITLE
[FEATURE] Add section to docs about configuration

### ISSUE THREAD

**Issue by mjmare** [tiangolo/fastapi#190]
It would be useful if you could add a section to the (already excellent) docs on the recommended way to add app configuration. Would you recommend something based on Pydantic's BaseSettings, or on Starlette's Config?
Both would work I think, but your opinion on the optimal integration in FastAPI would be useful.
TIA

**Comment by tiangolo** [comment]
Yep, good idea. I have been thinking about adding it.

It's probably gonna be based on Pydantic, it should probably be a bit more powerful, and in FastAPI you are already familiar with it, so it should be relatively easy to use.

**Comment by mjmare** [comment]
Looking forward to it. Thx

**Comment by jasonkuhrt** [comment]
Keep testing in mind. We want to be able to import `app` into tests for creating a test client. But we often want to mock the environment too. This means we want to avoid side-effect of init code firing upon `app` import, such as configuration.

What we currently do on my project:

```py
# lib/config.py
from functools import lru_cache

from pydantic import BaseSettings


class Config(BaseSettings):
    guestlist_client_secret: str
    guestlist_client_id: str
    guestlist_tenant_domain: str
    guestlist_audience: str
    app_name: str = "unknown"
    app_stage: str = "unknown"
    app_place: str = "unknown"
    app_log_level: str = "INFO"
    under_test: bool = False

    class Config:
        env_prefix = ""
        case_insensitive = True


@lru_cache()
def read() -> Config:
    return Config()

```
```py
# main.py
from fastapi import FastAPI

from locksmith import lib
from locksmith.routers import healthcheck, sync

app = FastAPI()
app.include_router(healthcheck.router)
app.include_router(sync.router)


@app.on_event("startup")
def on_startup():
    config = lib.config.read()
    lib.logging.configure()
```

Furthermore we have routers that need access to config:
```py
# routers/healthcheck.py

...
@router.get("/", response_model=HealthCheck)
def healthcheck():
    log.debug("healthcheck", url="/")
    config = lib.config.read()
    return HealthCheck(
        app=config.app_name, stage=config.app_stage, place=config.app_place, status="OK"
    )
```

It was too much work to get this all setup and it still feels clunky.

Here's a sketch for what a first-class config feature in FastAPI might look like:

- wrap `pydantic.BaseSettings` so `env_prefix` defaults to `""` and `case_insensitive` defaults to `True`.
- actually resolve the config at boot time, allowing tests to easily mock the environment
- inject resolved settings it at event and router points

```py
# settings.py
from fastapi import BaseSettings

class Settings(BaseSettings):
    app_log_level: str = INFO # TODO enum
    b: 2
```
```py
# main.py

from settings import Settings
from fastapi import FastAPI

app = FastAPI(settings=Settings)

@app.on_event("startup")
def on_startup(settings):
    lib.logging.configure(log_level=settings.app_log_level)

```
```py
# routers/healthcheck.py

from fastapi import router
from .settings import Settings
...
@router.get("/", response_model=HealthCheck)
def healthcheck(settings:Settings):
    log.debug("healthcheck", url="/")
    return HealthCheck(
        app=settings.app_name,
        stage=settings.app_stage,
        place=settings.app_place,
        status="OK"
    )
```

**Comment by jasonkuhrt** [comment]
I was catching up with [dependencies](https://fastapi.tiangolo.com/tutorial/dependencies/first-steps/) tonight and observed we almost have a great way of handling config already:

```py
# config.py
from fastapi import BaseSettings

class Config(BaseSettings):
    foo: str = "bar"
```
```py
# routers/healthcheck.py
from fastapi import router, Depends
from .config import Config

@router.get("/")
def healthcheck(config:Config = Depends()):
    return dict(
        app=config.app_name,
        stage=config.app_stage,
        place=config.app_place,
        status="OK"
    )


But this would require:

1. Depends caching the result of the invoked class 
2. Not allowing the Config constructor as affecting path config

non-fastapi solution to 1 is making `Config` a singleton or bringing back a helper read function using lru_cache

@tiangolo thoughts?

**Comment by tiangolo** [comment]
Thanks for all the discussion here!

Yes, we should have docs in the Advanced User Guide about doing app configuration with Pydantic's [`BaseSettings`](https://pydantic-docs.helpmanual.io/usage/settings/).

As it now also supports reading from `.env` files, one simple option that could go in the docs is to have a default in a `.env` file that is suitable for tests with a singleton, and then in production that could be overwritten with env vars.

And we could also have a note saying that depending on the use case, someone could prefer to have those settings generated in a dependency as instead of a singleton.

Nevertheless it would probably work mainly when using env vars only. In the case of `.env` files, getting the config in a dependency AND reading from `.env` files would add a performance penalty as the file would be read from disk for every request. So, to support `.env`, a singleton instance created only at startup would probably be useful for those cases.

---

Another way to solve it for tests would be to have env vars overriding any default in the environment where tests are run. For example, a bash script that creates the env vars and then runs pytest, after having those env vars set.

**Comment by mr-bjerre** [comment]
I also have a case right now where I connect to Firestore database when my application starts. I'd like to mock Firestore in my pytests but I can't figure out how I am supposed to do that.

Any current recommended way to do it atm?

**Comment by mr-bjerre** [comment]
Maybe I should've put a little more thinking into it before writing. This is my "workaround"

```python
from pydantic import BaseSettings

class Settings(BaseSettings):
    LOCAL_DEVELOPMENT = False

    class Config:
        env_file = ".env"

app = FastAPI()
settings = Settings()

if settings.LOCAL_DEVELOPMENT:
    from my_package import MockMyDB as MyDB
else:
    from my_package import MyDB

db = MyDB()
```

**Comment by tiangolo** [comment]
There are new docs for handling settings here: https://fastapi.tiangolo.com/advanced/settings/ , started by @alexmitelman in #1118 . :rocket: 

@mr-bjerre you can use those ideas from the docs there with dependency overrides for your tests :heavy_check_mark:

**Comment by mr-bjerre** [comment]
Great thanks. Looks good. Quick couple of questions though:

1. Having settings as dependency; wouldn’t that disable the initial warm up of the settings when the server start up?
2. would you hold custom types in BaseSettings as well? E.g a custom database class (which could be changed to a mock class in testing)

**Comment by tiangolo** [comment]
Yep, that's taken into account :ok_hand:

Check the new docs. :heavy_check_mark: :memo:

**Comment by mr-bjerre** [comment]
Beautiful (I must’ve missed it)

**Comment by mjmare** [comment]
@tiangolo Thanks for the new docs! Very useful.

**Comment by tiangolo** [comment]
Great! @mr-bjerre and @mjmare  :tada: 

If you think this solves your question, feel free to close the issue @mjmare :heavy_check_mark:

**Comment by mjmare** [comment]
I think this issue can be closed. It would be helpful for newbies to see more info on config strategies with regard to testing vs production. But that might be asked too much for the FastAPI docs.

**Comment by mxdev88** [comment]
It's not 100% clear to me when reading the [docs](https://fastapi.tiangolo.com/advanced/settings/#settings-and-testing) how to use settings in testing/mocking when the settings are not used as dependencies. Below an example:

config.py
```py
class Settings(BaseSettings):
    testing: bool = False
    api_key: str = 'some-secret-production-key'

    class Config:
        env_file = ".env"

@lru_cache()
def get_settings():
    return Settings()
```

somewhere in the app code i have something like 

```py
from config import get_settings
testing = get_settings().testing
```

Now say I would to mock the settings, in conftest.py I have

```py
@pytest.fixture(autouse=True)
def mock_settings(mocker): 
    import config
    mocker.patch.object(config, 'get_settings', side_effect=mock_get_settings) 
    mocker.patch('config.get_settings', side_effect=mock_get_settings)
```
where ```mock_get_settings``` overrides the production values with values for testing.

An example test would look like this:

```py
def test_something(client):
    import config
    print(f'{config.get_settings()}')
    from config import get_settings
    print(f'{get_settings()}')
    response = client.get(f"/something/", headers={"ApiKey": get_settings().api_key}) # where the ApiKey is mocked on the call but not in the app :/
    assert response.status_code == status_code
```
The results of the print statements above show testing values mocked as expected but the values are not mocked when ```client.get``` is invoked and the test fails. I would appreciate if someone could give some insight on how to proceed here. Is there something I am doing wrong here?

**Comment by Mause** [comment]
It's far easier to override the settings when they are a dependency - is there a reason you're choosing not to do it that way?

**Comment by imjohsep** [comment]
@mxdev88 You can drop the `@lru_cache` decorator if you are using `get_settings` as a dependency as `Depends` is set to `use_cache=True` by default.(Someone correct me if I'm wrong.) To your question, you can override dependencies before creating a TestClient like so:

```python
app.dependency_overrides[dependency.get_settings] = self.override_settings
```

The thing I haven't been able to figure out is how to override non dependency settings in testing. For example in my instantiation of `FastAPI(title="Fast App", version=settings.version)` in `main.py`, will throw validation errors at the moment Settings() is called. I could just os.getenv(), but would rather to continue to use Pydantic `BaseSettings`. I don't believe Settings() can be mocked either.

Resources: [dependency_overrides](https://fastapi.tiangolo.com/advanced/testing-dependencies/?h=+dependency+overri#testing-dependencies-with-overrides), [pydantic_basesettings](https://pydantic-docs.helpmanual.io/usage/settings/)

**Comment by phillipuniverse** [comment]
> The thing I haven't been able to figure out is how to override non dependency settings in testing

One of the things I am doing is relying on the behavior of `@lru_cache()` that it always gives me the same phsyical. It feels a little hacky but this works pretty well for say, overriding database settings with a test database:

```python
class DatabaseSettings(BaseSettings):
    name: str = "postgres"
    user: str = "postgres"
    password: str = "postgres"
    host: str = "localhost"
    port: int = 5432

    class Config:
        env_prefix = "DB_"

    @property
    def url(self) -> str:
        return f"postgresql://{self.user}:{self.password}@{self.host}:{self.port}/{self.name}"
...
...

@lru_cache()
def get_database_settings() -> DatabaseSettings:
    return DatabaseSettings()
```

And then in my `conftest.py`:

```python
@pytest.fixture(scope="session")
def postgres_server() -> Postgresql:
    postgres = testing.postgresql.Postgresql()  # uses testing.postgres dependency to create a brand new database

    postgres_params = postgres.dsn()
    db_settings = get_database_settings()
    db_settings.name = postgres_params["database"]
    db_settings.user = postgres_params["user"]
    db_settings.host = postgres_params["host"]
    db_settings.port = str(postgres_params["port"])

    try:
        wait_for_postgres(str(db_settings.url))  #wait_for_postgres just does retrying
        yield postgres
    finally:
        postgres.stop()
```

I can then make dependencies on that `postgres_server` fixture like running Alembic migrations or initializing an SQLAlchemy database. As long as you define the fixtures correctly, when you execute your test the singleton `DatabaseSettings` object will have been modified by that fixture.

**Comment by imjohsep** [comment]
@phillipuniverse Very good suggestion! Breaking settings out of a single large Settings class has resolved my import error issues. I now have 3 classes; 1. Database, 2. Application, and 3. Settings or dependency configurations. This way I'm able to initialize the application and db engine with default values, while overriding my `get_setttings` and `get_db` dependencies in testing. Works like a charm!

**Comment by GrayWizard12345** [comment]
What about just defining module level singletone with lazy init?
```
class MySettings(BaseSettings):
    name: str = "postgres"
    user: str = "postgres"
    password: str = "postgres"
    host: str = "localhost"
    port: int = 5432

    class Config:
        env_prefix = "DB_"

...
...

_settings: MySettings | None = None
def Settings() -> MySettings:
    global _settings
    if not _settings:
        _settings = MySettings()
    return _settings
```

And avoid creating global vars that reference this function in modules that require testing, so dont do
```
from settings import Settings
settings_instance = Settings()
```
And better call Settings() in functions/methods instead. This will help avoid caveat with tests
