### ISSUE TITLE
[BUG] Blocking on ``request.form()`` if middleware consumed it first.

### ISSUE THREAD

**Issue by yihuang** [tiangolo/fastapi#191]
**Describe the bug**
Fastapi hangup when starlette middleware consumed request body first.

**Environment:**
 - OS: macOS
 - Python 3.7.3
 - FastAPI 0.16.0
 - Starlette 0.11.1

```Python
from starlette.requests import Request
from starlette.middleware.base import BaseHTTPMiddleware
from fastapi import FastAPI, APIRouter, Form


class RateLimitMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        _ = await request.form()
        return await call_next(request)


router = APIRouter()


@router.post('/test')
def test(a: str = Form(None)):
    pass


app = FastAPI()
app.add_middleware(RateLimitMiddleware)
app.include_router(router)
```

```
$ uvicorn test:app --reload
```

```
$ curl -d "a=1" http://127.0.0.1:8000/test
```

The reason behind this is the request object in the middleware is different than the one fastapi uses, so it tries to consume request body twice.

**Comment by yihuang** [comment]
I think this is a starlette problem(encode/starlette#495). Closing this one.

**Comment by tiangolo** [comment]
Yep, it's directly related to Starlette. Thanks for opening it there and closing this one.

Also, have in mind that it only happens with form data. As it is read as a stream, in case there are files (that might be very large). But it should work with normal (JSON) bodies.
