### ISSUE TITLE
file uploads > 65536 characters, binary blobs/mp4s etc.

### ISSUE THREAD

**Issue by rcox771** [tiangolo/fastapi#2]
Hello there,

First, I have to say that I am really impressed by what you guys are doing here. Also, your docs are outstanding and easy to follow. I spotted your project on my recommendations page and immediately fell in love, losing most of my Friday night tinkering around.

When I got to your [file upload section](https://fastapi.tiangolo.com/tutorial/request-forms-and-files/) in the docs, I hit a snag when trying to upload an mp4 file. 

`{
  "detail": [
    {
      "loc": [
        "body",
        "file"
      ],
      "msg": "ensure this value has at most 65536 characters",
      "type": "value_error.any_str.max_length",
      "ctx": {
        "limit_value": 65536
      }
    }
  ]
}`
![image](https://user-images.githubusercontent.com/13604961/50720558-6e5c2600-107d-11e9-8918-b6a7457d060c.png)

It seems like the File type expects bytes as strings, which aren't allowed to go past 65536 characters in length. I expect others might run into this too, or be confused like I am when hitting this part.

-Russell

**Comment by tiangolo** [comment]
> First, I have to say that I am really impressed by what you guys are doing here. Also, your docs are outstanding and easy to follow. I spotted your project on my recommendations page and immediately fell in love, losing most of my Friday night tinkering around.

Awesome! It's great to hear that. Thanks for writing it :smile: 

> When I got to your file upload section in the docs, I hit a snag when trying to upload an mp4 file.

Thanks for the very detailed bug report.

The bug was because of a default constraint in Pydantic. I just created a custom internal class for this that fixes the problem. I also added a test for this specific use case.

Please try with the latest version `0.1.17`.

---

I also plan on supporting Starlette's (undocumented) file uploads, to get a file-like object. But this will come afterwards.

**Comment by rcox771** [comment]
Great, thanks! `0.1.17` works without a hitch :tada:. I'll close this issue and keep an eye out for changes in the future. 

> I also plan on supporting Starlette's (undocumented) file uploads, to get a file-like object. But this will come afterwards.

That looks like a good idea. Do you have any plans to reuse [pathlib's file interface](https://docs.python.org/3/library/pathlib.html#pathlib.Path.write_bytes)?

**Comment by tiangolo** [comment]
Awesome! Thanks for reporting back.

I'll use [Starlette's undocumented `UploadFile`](https://github.com/encode/starlette/blob/master/starlette/formparsers.py#L38) which exposes a nice file-like API. So it will be quite similar to standard Python files.
