### ISSUE TITLE
Korean translations

### ISSUE THREAD

**Issue by hard-coders** [tiangolo/fastapi#2017]
### 🇰🇷 Korean translations (ko)

I hope to translate the whole docs into Korean.  
This issue is opened to track the progress of Korean language translation.

Any suggestion is welcome, and I will appreciate it. 😃 

### 📚 Glossary
Use [python official Korean glossary](https://docs.python.org/ko/3/glossary.html) for maintaining consistency.

If you can't find a proper word in the glossary, you can find it from https://www.flowdas.com/pages/python-docs-ko.html python Korean document maintainer, @flowdas, maintains.

Also, use less English as you can. For instance, at [첫걸음](https://fastapi.tiangolo.com/ko/tutorial/first-steps/#_7)

- PUT : 데이터를 ~업데이트~수정하기 위해

See https://github.com/tiangolo/fastapi/discussions/3167#discussioncomment-1502428 (Thanks, @0417taehyun)

### ✍🏻 Writing style (2020-11-07 added)
비격식체(Informal)인 해요체를 지양하고 격식체(Formal)인 합쇼체를 지향합니다.

e.g.
- ~이에요 (NOT Recommended)
- ~입니다.

### 👨‍👩‍👧‍👦 Discussion (2021-05-04 added)
I opened a discussion, https://github.com/tiangolo/fastapi/discussions/3167.
If you have a suggestion or an idea, please comment on it the discussion.

OR

You can join [FastAPI Discord](https://discord.gg/VQjSZaeJmf) and talk to in `Korean` channel!

### 🎁 PR Guide
See https://fastapi.tiangolo.com/contributing/#translations, please.

You don't have to get any permission. FastAPI is an open-source project.
And I'm not an owner, just a contributor like anyone else.
If you want to contribute, do it right now!

**Comment by SangRyul** [comment]
번역작업에 기여하고 싶은데 혹시 관련된 소통 채널이 있을까요?(deployment 부분부터 참여하고 싶습니다.)

**Comment by hard-coders** [comment]
@SangRyul 따로 소통 채널이 있지 않습니다. 자유롭게 PR 날려주시면 됩니다.
추후 인원이 많아지면 새 discussion 을 만들어서 번역 작업이 중복되지 않게 하거나 용어 번역들에 대한 의견을 나누고자 합니다.😁

**Comment by ParkDyel** [comment]
번역 협업에 [git Localize](https://gitlocalize.com/) 도 한번 생각해봐주시면 좋을것 같습니다. 적당히 떨어져 있는 문서 참여해보겠습니다!

**Comment by joosangkim** [comment]
신규 프로젝트에 fastapi 를 사용하고 있는데, feature 의 번역안된 부분부터 참여해보려고 합니다!

**Comment by hard-coders** [comment]
> 신규 프로젝트에 fastapi 를 사용하고 있는데, feature 의 번역안된 부분부터 참여해보려고 합니다!

https://fastapi.tiangolo.com/contributing/#translations PR 번역 가이드 라인입니다.
이 프로젝트는 모두에게 열려 있으므로 자유롭게 PR 날리시면 됩니다:)

**Comment by hard-coders** [comment]
Waiting reviews
- Tutorial - Request Body #2392 
- Tutorial - Query Parameters and String Validations #2415
- Tutorial - Path Parameters and Numeric Validations #2432
- Tutorial - Body Multiple Parameters #2461
- Tutorial - Body - Fields #2489
- Tutorial - Body - Nested Models #2506
- Tutorial - Extra Data Types #2528
- Tutorial - Cookie Parameters #2545
- Tutorial - Response Model #2766
- Tutorial - Middleware #2829
- Tutorial - Static Files #2957
- Tutorial - Request Forms #2908
- Tutorial - Body - Updates #3120
- Tutorial - JSON Compatible Encoder #3152

**Comment by joonas-yoon** [comment]
오래된 PR이 많은 것 같네요. 번역이 아직 안 된 부분을 찾고 싶은데, 어디까지 합쳐진 건지 알 수 있을까요?

**Comment by joonas-yoon** [comment]
안녕하세요. 최근 들어서 번역 기여 Pull Request를 많이 올려주시고 계시는데요, 중복이 꽤 많이 발생하고 있습니다.

물론, 오래 방치된 open issue 때문이라는 것은 알고 있습니다. 동일한 번역 PR이 존재하는 지 검색하시는 것도 번거로우시겠지요.
하지만 이미 작업된 내용을 다시 처음부터 번역하시고 PR을 작성하시는 수고는 없었으면 좋겠습니다.

그래서 **확인하기 편하도록 checklist를 작성**했고 꾸준히 업데이트하고 있으니 참고 부탁드립니다.

Click this link to see the checklist - https://github.com/tiangolo/fastapi/discussions/3167#discussioncomment-3335089

**Comment by KaniKim** [comment]
https://open.kakao.com/o/gWfoIpYe
I made a English-Korean fastapi docs Translation Kakaotalk Open Chatting Room, If you want, plz Join here.
한국어로 된 소통방이 필요할 것 같아서, 카카오톡 오픈 채팅방을 만들었습니다. 자유롭게 참여해 주세요.
