### ISSUE TITLE
[BUG] MyPy error when `response_model` is of type `List`

### ISSUE THREAD

**Issue by sm-Fifteen** [tiangolo/fastapi#216]
**Describe the bug**
When using mypy to check FastAPI routes, setting `response_model` on any route to be `List[MyModel]` instead of simply `MyModel` causes mypy to raise the following type error:

```
$ mypy app.py 
app.py:11: error: Argument "response_model" to "get" of "FastAPI" has incompatible type "Type[List[Any]]"; expected "Optional[Type[BaseModel]]"
```

The error does not prevent the code from executing correctly and does not result in any runtime error, this is strictly limited to mypy code validation.

**To Reproduce**
Minimal code to reproduce:
```py
from fastapi import FastAPI
from typing import List
from pydantic import BaseModel

class TestModel(BaseModel):
	foo: int
	bar: str

app = FastAPI()

@app.get("/test", response_model=List[TestModel])
async def test_return_list():
	return [TestModel(foo=1, bar="baz")]
```

**Expected behavior**
No linting error should occur, meaning `response_model` should be typed to accept both `List[Type[BaseModel]]` and `Type[BaseModel]` arguments, considering FastAPI can indeed accept this and [the documentation actually suggests doing this](https://fastapi.tiangolo.com/tutorial/extra-models/#list-of-models).

**Screenshots**
![image](https://user-images.githubusercontent.com/516999/57575404-8b33ac00-7417-11e9-8580-73ab694ac0cd.png)

**Environment:**
 - OS: Linux
 - FastAPI Version: 0.20.1
 - Python version: Python 3.7.2
 - mypy version: mypy 0.701

**Comment by tiangolo** [comment]
Thanks for the report, I'll check it.

**Comment by tiangolo** [comment]
This should be fixed in one of the last versions (I'm not sure which). If you update your FastAPI version you should be able to use it.

The current latest is `0.27.0`.

I'll close this issue now, but feel free to add more comments or create new issues.
