### ISSUE TITLE
[FEATURE] Make swagger-ui and redoc favicon configurable

### ISSUE THREAD

**Issue by sm-Fifteen** [tiangolo/fastapi#220]
**Is your feature request related to a problem? Please describe.**
Both documentation viewers loaded by FastAPI currently use https://fastapi.tiangolo.com/img/favicon.png as their favicon with no way to change it. It's a nice enough favicon and does the job as a default, but it appears to currently be hardcoded in `fastapi/openapi/docs.py`, which makes it tricky to change.

**Describe the solution you'd like**
Let the user pass a `doc_favicon` argument to FastAPI on initialization and fallback on the default if none is provided.

**Describe alternatives you've considered**
* Having all static assets served by FastAPI moved to an internal folder (the HTML templates for the doc pages and possibly the JS bundles for Redoc and Swagger UI), with the option to let the user specify a custom path instead. That one would represent more work and would make custom assets into an all-or-nothing deal, though that isn't to say that having an internal static folder wouldn't have its benefits.

**Comment by euri10** [comment]
See https://github.com/tiangolo/fastapi/pull/112 :wink:

**Comment by euri10** [comment]
I modified the PR so that you can pass either the js, the css or the favicon or any combination of 1, 2 or 3 of them in fact.

Usage is you pass a `static_directory` kwarg that contains your static files, and then a `swagger_static` dictionnary that can have 3 keys, js, css or favicon whose value is the name of the file.
Should a key be missing it uses the default.

To have a favicon only just do 
```
app = FastAPI(
        static_directory=static_directory,
        swagger_static={
            "favicon": swagger_static_icon,
        },
    )
```

**Comment by tiangolo** [comment]
@euri10 's PR is already merged (although changed from the last comment).

I haven't documented it yet, but you can use it already.

**Comment by tiangolo** [comment]
Using static assets is documented at https://fastapi.tiangolo.com/advanced/extending-openapi/#self-hosting-javascript-and-css-for-docs

It was added a while ago but I hadn't commented about it here. :grimacing: 

I think that should solve the original problem :rocket:  So I'll close this issue now. But feel free to add more comments or issues.

**Comment by Kilo59** [comment]
The `swagger_favicon_url` argument isn't featured anywhere in the provided example, and would still lead one to think this isn't possible unless you pulled up the source code.
https://github.com/tiangolo/fastapi/blob/master/fastapi/openapi/docs.py#L14

A minimal example would be even better. Once/if I figure it out, I'll submit a PR.

**Comment by leosok** [comment]
I have kind of a similar problem. If using this code
```
app = FastAPI(
              swagger_ui_parameters={"tryItOutEnabled": True},
              title="My Title",
              description="Handle with care :-)",
              swagger_favicon_url="/static/favicon.ico")
```
I would expect it to override `https://fastapi.tiangolo.com/img/favicon.png`. It does not. I need to write a function like

```
@app.get("/docs", include_in_schema=False)
def overridden_swagger():
    return get_swagger_ui_html(openapi_url="/openapi.json",
                               title="My better title",
                               swagger_favicon_url="/static/favicon.ico")

```

which only works if the app is created with `app = FastAPI(docs_url=None, ...`

Is this a bug or am I confused here? `swagger_favicon_url` should be overridable from the FastAPI object, IMHO.
