### ISSUE TITLE
[FEATURE] Update Pydantic to v0.25

### ISSUE THREAD

**Issue by kolygri** [tiangolo/fastapi#224]
**Is your feature request related to a problem? Please describe.**
Pydantic structural subtyping can't differentiate between two semantically different but structurally identical types. Hence, in the current Pydantic v0.25 release the `const` keyword was introduced to help with that, [Pydantic issue link](https://github.com/samuelcolvin/pydantic/issues/434). Unfortunately, at the moment FastAPI works with versions less than 0.23, `fastapi (0.20.0) depends on pydantic (>=0.17,<=0.23.0)`  

**Describe the solution you'd like**
I would like to update to pydantic v0.25

**Comment by tiangolo** [comment]
Done! Implemented by @euri10 in PR #225.

Just released (with some other changes) in FastAPI version `0.21.0`. :tada: :rocket: :cake:
