### ISSUE TITLE
FastAPI debugging

### ISSUE THREAD

**Issue by olegasdo** [tiangolo/fastapi#23]
Hello
I've seen on FastAPI documentation site, that it integrates nice with a VSCode. 
Any hint on debugging an FastAPI application in VSCode? There are some exaple configrations for python projects, but unfortunately I'm not able to utilize these for  FastAPI

Thanks
Olegas

**Comment by euri10** [comment]
What examples are you talking about ?
What prevents you from using them ?
If you could be more specific that would help answering.

Docs are very clear and progressive imho, using the parts provided should suffice, if not the tests folder is often a good source of inspiration.

**Comment by olegasdo** [comment]
Yes, documentation is fine, thanks.
What I mean are debug configurations, which allows you set breakpoints in
code. Not only on start, but also when performing api calls.

**Comment by euri10** [comment]
not sure how this is related to FastAPI, this seems more like a general question on how to use vscode.
I'm using pycharm and in order to debug a route you'd simply put a breakpoint in it and call it either with your local browser, or curl, well anything you'd feel comfortable with.
As for vscode seems like debugging is described here: https://code.visualstudio.com/docs/python/debugging that may be a good start. 
You could also use the cool pdb.

**Comment by olegasdo** [comment]
Yes, it's more common question. thanks for tips tho.

Regards

**Comment by tiangolo** [comment]
Thanks for your help here @euri10 !

@olegasdo, I hope you found what you needed in the VS Code docs.

---

Here's one option that might work for you:

You can import `uvicorn` in your file, instead of calling it directly from the command line, and run it inside (maybe just for development).

```Python
from fastapi import FastAPI
import uvicorn

app = FastAPI()

@app.get("/")
def root():
    a = "a"
    b = "b" + a
    return {"hello world": b}


if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8000)
```

Then you can use the default VS Code launcher, "Python: Current File (Integrated Terminal)".

It will then stop at your breakpoints, etc.

Here's how it looks:

![vscode-launch-debug-vscode](https://user-images.githubusercontent.com/1326112/52523080-dfa77e00-2ca6-11e9-8b4d-7c60d0cf4805.png)

**Comment by olegasdo** [comment]
Thank you, Sebastián, that's was exactly what I was looking for. 
Also @euri10 thanks for the hints.

**Comment by tiangolo** [comment]
Just in case, there is now a section for Debugging FastAPI applications, with this same information above: https://fastapi.tiangolo.com/tutorial/debugging/

**Comment by euri10** [comment]
small concern imho using uvicorn programatically is that you can't use the --debug flag for automatic reload, see https://www.uvicorn.org/deployment/

> The reloader is not enabled when running programmatically.

The alternative I use in development mode while in pycharm (not sure about VSCode sorry) is to use a config like this and run the --debug flag, this way auto-reloading works:

![Imgur](https://i.imgur.com/DuA3Sk1.png)

**Comment by tiangolo** [comment]
Sorry for the delay, thanks for the hint @euri10 . Actually, I think it would be nice to have a run command for Uvicorn in PyCharm and Uvicorn with everything pre-configured. Or at least docs for how to do it.

Also, in a recent version of Uvicorn, it's now possible to add `reload` programmatically. But still, I think it would be worth having that directly in the editors. I'll take a note to try and PR that command config to them.

**Comment by euri10** [comment]
@tiangolo  I'm not aware of a way to programatically add a configuration command in Pycharm (like the `uvicorn` one from the screenshot above), it has to be done manually with gui

They are saved in `.idea/workspace.xml` yet this would be awkward to edit that by hand.

If you ok I can write a PR for Pycharm debug (I'm clueless on other IDE), with a set of screenshots for:

1-  fastapi development itself
-  a pytest config (it requires to have `PYTHONPATH=docs/src` in env vars for instance, which is not obvious at first)

2- any application using fastapi
- a uvicorn config (like the one above, with the now super mega cool --reload flag)

**Comment by wshayes** [comment]
I'm happy to try to create a PR with info on using Docker with fastAPI - just not sure where you'd want it in the docs (e.g. along the lines of: https://medium.com/@williamhayes/fastapi-starlette-debug-vs-prod-5f7561db3a59) or maybe a location for links like that article in the docs.

**Comment by tiangolo** [comment]
Thanks @wshayes ! I think we can have that in the project generators, that are all Docker-based. For example, there's a lot of docs in the generated projects: https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.md#backend-local-development-additional-details

@euri10 What I would like to do first, although maybe a bit ambitious, is to PR directly to the source of PyCharm and VS Code, including a runner for Uvicorn. That would allow debugging FastAPI, but also any other ASGI, Starlette directly, Quart, Responder, Bocadillo, etc. So, I think it would be beneficial for everyone. But I have to check their source code to see where those runners live first :grin:

**Comment by yrunts** [comment]
Looks like debugging works only if reloader is disabled (I've tried with pdb).

Any ideas on how to overcome this?

**Comment by Christian-Schultz** [comment]
The following works with the pycharm debugger with reload running in a docker-compose remote interpreter
```
from fastapi import FastAPI
import uvicorn

app = FastAPI()

@app.get("/")
def root():
    a = "a"
    b = "b" + a
    return {"hello world": b}


if __name__ == '__main__':
    uvicorn.run("main:app", host='0.0.0.0', port=8000, reload=True)
```

Notice the it's "main:app" and not app otherwise you get an error: _WARNING:  You must pass the application as an import string to enable 'reload' or 'workers'._

**Comment by bytesemantics** [comment]
This worked for me...... (assuming your python project is using virtualenv)....

1. Set up VSCode to use your local virtualenv python exe:
https://code.visualstudio.com/docs/python/environments

2. Set up a Debug Configuration in VSCode like:
        {
            "name": "Python: Uvicorn",
            "type": "python",
            "request": "launch",
            "module": "xxxxxx",
            "program": "${workspaceRoot}/venv/bin/uvicorn ${module}:app",
        },

where "xxxxxx" is the module name of your python code containing the FastAPI "app"

**Comment by softwarebloat** [comment]
Hi guy's,
sorry but none of the above seems to work for me.
when i run the debug, i get an ImportError:
`ImportError: attempted relative import with no known parent package`

I think i described a little better [here](https://stackoverflow.com/questions/60205056/debug-fastapi-application-in-vscode)

Tanks

**Comment by softwarebloat** [comment]
> Thanks @wshayes ! I think we can have that in the project generators, that are all Docker-based. For example, there's a lot of docs in the generated projects: https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.md#backend-local-development-additional-details
> 
> @euri10 What I would like to do first, although maybe a bit ambitious, is to PR directly to the source of PyCharm and VS Code, including a runner for Uvicorn. That would allow debugging FastAPI, but also any other ASGI, Starlette directly, Quart, Responder, Bocadillo, etc. So, I think it would be beneficial for everyone. But I have to check their source code to see where those runners live first 😁

Did you manage to open a PR to vscode at the end? Thanks 🍻

**Comment by bytesemantics** [comment]
Hi @softwarebloat  - sorry that the above does not work for you. It works for me :-)

This is not a VS Code problem, nor a fastapi problem. The problem is how (and what) you are managing your project python packages with. As stated above - virtualenv approach works fine - as it manages PATH/PYTHONPATH appropriately. VSCode is also designed to support virtualenv environments.

You can either switch to virtualenv - or pursue an integration solution using poetry (with VSCode) - but this certainly is NOT a FastAPI problem or bug. Sorry I can't help further.

**Comment by robertcoopercode** [comment]
> The following works with the pycharm debugger with reload running in a docker-compose remote interpreter
> 
> ```python
> from fastapi import FastAPI
> import uvicorn
> 
> app = FastAPI()
> 
> @app.get("/")
> def root():
>     a = "a"
>     b = "b" + a
>     return {"hello world": b}
> 
> 
> if __name__ == '__main__':
>     uvicorn.run("main:app", host='0.0.0.0', port=8000, reload=True)
> ```
> 
> Notice the it's "main:app" and not app otherwise you get an error:
> 
> > WARNING:  You must pass the application as an import string to enable 'reload' or 'workers'.

This also works with VS Code, I just tried it out.

**Comment by cottrell** [comment]
Has anyone figured out the pattern for setting this up for call from IPython REPL and using pdb?

**Comment by cbnfreitas** [comment]
In regards to **FastAPI/Uvicorn debugging**, considering **VSCode** on Windows and **virtualenv** (with PIPENV_VENV_IN_PROJECT=1 to include virtualenv dependencies on the project folder), maybe this hint can be relevant for you. **It even includes hot reload** :-)

Following @bytesemantics 's answers above, some changes to .\.vscode\launch.json were necessay:
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Uvicorn",
            "type": "python",
            "request": "launch",
            "program": "${workspaceRoot}\\YOUR-VENV-FOLDER\\Scripts\\uvicorn.exe",
            "args": [
                "YOUR-MODULE-NAME.main:app",
                "--reload"
            ],
        }
    ]
}`

Don't forget to change .\.vscode\settings.json 
`{
  "python.pythonPath": ".\\YOUR-VENV-FOLDER\\Scripts\\python.exe" 
}`

**Comment by diegorosen** [comment]
> What I would like to do first, although maybe a bit ambitious, is to PR directly to the source of PyCharm and VS Code, including a runner for Uvicorn. That would allow debugging FastAPI, but also any other ASGI, Starlette directly, Quart, Responder, Bocadillo, etc. So, I think it would be beneficial for everyone. But I have to check their source code to see where those runners live first

@tiangolo sorry for the insistence, did you finally sent PR to PyCharm, related to this "Uvicorn runner" ?  If not, I would be interested on helping towards that, if you already have some progress related.
I am actually debugging as explained at https://fastapi.tiangolo.com/tutorial/debugging/ (by the way, thanks, that tutorial was really helpful), but as I added those lines of code
```
import uvicorn
if __name__ == "__main__":
    uvicorn.run('app.main:app', host="0.0.0.0", port=80, reload=True)
```
specifically for debugging and are not part of my "original project", it sounds great if we could make Pycharm adding a native Uvicorn runner.

**Comment by taffit** [comment]
> Has anyone figured out the pattern for setting this up for call from IPython REPL and using pdb?

Using FastAPI within a docker container and also having problems debugging it from the commandline. A simple `import ipdb; ipdb.set_trace()` unfortunately doesn't work.

**Comment by Master-Y0da** [comment]
This not working for me...I'm not using docker but I try many ways for start debugging, and gives me this error when I hit f5 at VSCODE :

**ModuleNotFoundError: No module named 'fastapi'**

This is my code:

     from fastapi import FastAPI
     import uvicorn  

     if __name__ == "__main__":
          uvicorn.run("main:app", host="127.0.0.1", port=8181, reload=True)

**Comment by olegasdo** [comment]
After some pause got back to the FastAPI with a need to debug some. 
But Have no luck entering Debug mode on WIndows and VSCode
Tried every suggested way from here and from oficial documentaion and it's just not working. Debug does not stop on the beackpoints even in main.py file, left away aother that are loaded.

Anyone with more suggestions?

**Comment by olegasdo** [comment]
Not sure why, but when showing to a colleague @cbnfreitas suggested solution (well alsmost) started working. 
Python path is pointed to the .venv folder in the project dir.
launch.json in VSCode:

{"name":"Python: FastAPI","type":"python","request":"launch","module":"uvicorn",
            "env": {
            "db_username": "postgres",
            "db_password": "",
            "host_server": "localhost",
            "database_name": "fastapi",
            "ssl_mode": "prefer",
            "db_server_port": "5432"
        },
        "args": [
            "app.main:app",
            "--port",
            "5000"
        ],
        "jinja": true
    }

Hope this will will someone to save some time searching

**Comment by olegasdo** [comment]
I've noticed that debugging stopped when I've added "--reload" to the arguments list
