### ISSUE TITLE
[FEATURE]: make swagger_ui_html, redoc_html and openapi.json handled by async function?

### ISSUE THREAD

**Issue by Trim21** [tiangolo/fastapi#238]
**Is your feature request related to a problem? Please describe.**
I add a loop on all my router of my app to check if the handler are all coroutine function to get better performance, but I fount that swagger_ui_html, redoc_html and openapi.json are handled by normal function.

https://github.com/tiangolo/fastapi/blob/56ab106bbbf8054af437821c6683491ca7952c3b/fastapi/applications.py#L80-L86

**Describe the solution you'd like**

I'm wondering if its possible to handle these 3 router with async function, as its only a simple `getattr` operator or concat string.

https://github.com/tiangolo/fastapi/blob/56ab106bbbf8054af437821c6683491ca7952c3b/fastapi/applications.py#L78

```python
    def setup(self) -> None:
        if self.openapi_url:

            async def openapi_handler(req):
                return JSONResponse(self.openapi())

            self.add_route(
                self.openapi_url,
                openapi_handler,
                include_in_schema=False,
            )
```
**Describe alternatives you've considered**

Disable default handlers and I write async handlers by my self to replace inner handlers.

**Additional context**

In `Starlette`, if a handler is not coroutine function, it will be executed by `loop.run_in_executor` . So this could improve performance a litte bit.(In my test, about 2800 r/s to 3200r/s)

**Comment by tiangolo** [comment]
Nice catch @Trim21 ! I'll fix it.

**Comment by Trim21** [comment]
If you don't mind, could I give a PR to fix it?

**Comment by tiangolo** [comment]
Of course! PRs are very welcome.
