### ISSUE TITLE
[FEATURE] skip_defaults for path operations

### ISSUE THREAD

**Issue by wshayes** [tiangolo/fastapi#242]
**Is your feature request related to a problem? Please describe.**

Need to exercise the skip_defaults option for pydantic json serialization so that Optional elements do not get serialized when they are nulls (see [Pydantic issue](https://github.com/samuelcolvin/pydantic/issues/530). 

**Describe the solution you'd like**
Allow the ability to set skip_defaults for endpoints (path operations) so that null values are not emitted in the JSON serializations.

I can take a stab at putting together a PR for this. I didn't realize my front-end colleagues wanted this cleaned up so urgently.

**Comment by tiangolo** [comment]
Thanks for adding it here! That helps us track the state of this feature.

If you can start a PR that would be great, otherwise I'll do it soon (but I'm fixing a couple of things first).

**Comment by tiangolo** [comment]
As the PR is already merged and it is available in the latest versions, I'll close this issue now. But feel free to add more comments or create new issues.
