### ISSUE TITLE
Support starlette 0.14

### ISSUE THREAD

**Issue by FFY00** [tiangolo/fastapi#2493]
Hey, would it be possible to update to starlette 0.14?

**Comment by Kludex** [comment]
There's already a PR proposing it: https://github.com/tiangolo/fastapi/pull/2335

**Comment by SunsetOrange** [comment]
I think this could be closed now as fastapi now..
`requires = [
    "starlette ==0.14.2",`

**Comment by tiangolo** [comment]
Thanks for the discussion! :coffee: 

The current version of Starlette is 0.22.0. So I think we can close this one. :sweat_smile: 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
