### ISSUE TITLE
[QUESTION] HTTPException detail type

### ISSUE THREAD

**Issue by knyghty** [tiangolo/fastapi#261]
**Description**

I'm not sure if this is a bug since I'm not sure what the fix would be and it _seems_ to be covered in the docs, though not explicitly.

Per the docs you can pass anything JSON serializable to `HTTPException`'s `detail` parameter: https://fastapi.tiangolo.com/tutorial/handling-errors/

However, it's typed as `str`, presumably because it's inheriting Starlette's HTTPException, and I assume it does this to get some specific functionality from Starlette. So for now I have to just pass in my JSON serializable content and stick `# type: ignore` on the end.

I'm just wondering if there's a better way to do this, or if it's something that can be fixed.

**Comment by tiangolo** [comment]
Thanks for the report.

This should be fixed and available since `0.27.1`, the current latest (just released) is `0.27.2`. :tada: :rocket:

**Comment by knyghty** [comment]
Thanks, it's fixed for me now.
