### ISSUE TITLE
[FEATURE] Add support for Pydantic's dataclasses

### ISSUE THREAD

**Issue by sebastianschramm** [tiangolo/fastapi#265]
**Describe the question**
I am using a  pydantic.dataclasses.dataclass as a response_model of my fast api route.

```
from fastapi import FastAPI
from pydantic.dataclasses import dataclass


@dataclass
class Foo:
    bar: int

app = FastAPI()

@app.get('/foo', response_model=Foo)
def get_bar() -> Foo:
    return Foo(bar=1)
```

**To Reproduce**
1. Create a file **app.py** with the above code.
2. Start the app: `uvicorn app:app`
3. Open the browser and go to **localhost:8000/foo**
4. See error: 
```
pydantic.error_wrappers.ValidationError: 1 validation error
response
  __init__() got an unexpected keyword argument '__initialised__' (type=type_error)
```

**Expected behavior**
No validation error and serialized json does not contain any keys `__initialised__`.

**Environment:**
 - OS: Linux
 - FastAPI Version 0.25.0
- Python version 3.7.3

**Comment by sebastianschramm** [comment]
**Possible solution**

Add the following to jsonable_encoder in fastapi.encoders:

```
from dataclasses import is_dataclass, asdict

def jsonable_encoder(
    obj: Any,
    include: Set[str] = None,
    exclude: Set[str] = set(),
    by_alias: bool = True,
    skip_defaults: bool = False,
    include_none: bool = True,
    custom_encoder: dict = {},
    sqlalchemy_safe: bool = True,
) -> Any:
...
    if is_dataclass(obj):
        return asdict(obj)
```

**Comment by tiangolo** [comment]
Thank you. Pydantic's dataclasses are not supported yet. They probably will be at some point.

**Comment by abdusco** [comment]
Any updates on this?

**Comment by manojlds** [comment]
Using pydantic BaseModel vs dataclass causes tremendous slowdown as well in my codebase.

**Comment by dmontagu** [comment]
@manojlds which one is slower?

**Comment by dconathan** [comment]
👍 for this.  I have a backend code base that heavily relies on pydantic dataclasses.

Just a thought, the way pydantic dataclasses are handled is by putting the `BaseModel` subclass at `cls.__pydantic_model__`, e.g.:

```python
from pydantic.dataclasses import dataclass
from pydantic import BaseModel

@dataclass
class Foobar:
    pass

assert issubclass(Foobar.__pydantic_model__, BaseModel)
```

Could this be solved with a simple:
```python
if isdataclass(cls) and hasattr(cls, "__pydantic_model__"):
    cls = cls.__pydantic_model__
```
Somewhere?

**Comment by dconathan** [comment]
Maybe part of https://github.com/tiangolo/fastapi/blob/master/fastapi/utils.py#L53 ?

**Comment by justinttl** [comment]
Hi, 

I have been trying to get native dataclasses to work, but am still running into issues when the view function returns the dataclass (referenced as response_body) 

Error: 
```
pydantic.error_wrappers.ValidationError: 1 validation error for XYZResponse
response
  value is not a valid dict (type=type_error.dict)
```

Code:
```python
@dataclass
class XYZResponse:
    X: str
    Y: SomeOtherDataclass
    Z: int

@app.post(
    '/xyz',
    response_model=XYZResponse,
)
async def calculate_xyz(r: XYZRequest):
    return XYZResponse(...) 
```
Would be helpful if documentation can address this functionality and its possible limitations (given that it is not a BaseModel) of **using** and **mixing** the usage of BaseModel and dataclass as Schemas

**Comment by jomido** [comment]
Is it more likely that tools such as `mypy` and `pyright` will opt to do type checking on built-in objects, such as Python's standard `dataclasses`, vs library-supplied objects, like `FastAPI`'s `BaseModel` and `pydantic.dataclasses`?

I think it might. In addition, `TypedDict` (another built-in come Python 3.8), is already being checked (to varying degrees of success) by the aforementioned type checkers.

**Comment by dmontagu** [comment]
@justinttl I don't think pydantic dataclasses are supported as response models yet. I think it *might* make sense to add support for this, but either way I wouldn't expect it to happen until after the upgrade to support pydantic v1.

@jomido Pydantic v1.1 has a mypy plugin that supports checks for `BaseModel` including everything supported for dataclasses, and more. You can see the full details [here](https://pydantic-docs.helpmanual.io/mypy_plugin/).

(I am confident in this assessment because I wrote the pydantic mypy plugin, and based it largely on the official dataclasses plugin. Also, note `BaseModel` is actually a pydantic thing, not a FastAPI thing.)

Pydantic dataclasses are also treated by mypy in exactly the same way as built-in dataclasses (except that support for the pydantic-specific `config` argument was recently added to the pydantic dataclass decorator).

**Comment by dmontagu** [comment]
@justinttl It looks like pydantic dataclasses work as long as you provide a config with `from_orm=True`:

```python
from fastapi import FastAPI
from pydantic.dataclasses import dataclass
from starlette.testclient import TestClient


class ORMConfig:
    orm_mode = True


@dataclass(config=ORMConfig)
class XYZResponse:
    x: str


app = FastAPI()


@app.get(
    '/xyz',
    response_model=XYZResponse,
)
async def calculate_xyz():
    return XYZResponse("hello")


print(TestClient(app).get("/xyz").content)
# b'{"x":"hello"}'
```

@tiangolo I feel like there is room for improvement around the handling and/or error messages here. Maybe we should require `orm_mode` for any model used by FastAPI? Or turn it on automatically?

@samuelcolvin Any ideas about how we might more clearly indicate to users that the problem is coming from `orm_mode=False`?

**Comment by samuelcolvin** [comment]
I would guess the best approach would be a check in fastapi that `orm_mode` is enabled, perhaps powered by some pydantic tool methods like `get_model` or `get_config` that work on both models and dataclasses?

**Comment by dmontagu** [comment]
That's a good idea, I think we should add that check to FastAPI in the near future when a `response_model` is specified.

Actually, perhaps we should even automatically enable `orm_mode` as necessary, possibly by subclassing the provided `response_model` with an update to the `Config`.

**Comment by Imaclean74** [comment]
agreed with this. I've just hit the same issue - and the logged error ("value is not a valid dict (type=type_error.dict)") is less than informative. The orm_mode fix does work as expected though - so that's good.

**Comment by frejsoya** [comment]
This does not work with nested dataclassed. The inner class record will have ```...,__intialized__ : true,...```

**Comment by rafaellehmkuhl** [comment]
> This does not work with nested dataclassed. The inner class record will have `...,__intialized__ : true,...`

My solution was to implement an `asdict` method on the class, which returns a dictionary with the correct fields. It's definitely not a good solution, but a workaround.

**Comment by matthewygf** [comment]
@tiangolo I don't think this should be closed, as @rafaellehmkuhl @frejsoya  mentioned, nested dataclasses will still have the __initialised__ keyword....

**Comment by j4k0bk** [comment]
This feature would be nice, since our data model is defined generally using data classes, and fastapi is only part of the system using this data model.

**Comment by tiangolo** [comment]
Thanks for the discussion everyone. If any of you is still having issues related to this, please create a new issue following the template.

> Sorry for the long delay! 🙈  I wanted to personally address each issue and they piled up through time, but now I'm checking each one in order.
