### ISSUE TITLE
[BUG] missing link in doc

### ISSUE THREAD

**Issue by wshayes** [tiangolo/fastapi#274]
**Describe the bug**
https://fastapi.tiangolo.com/tutorial/security/oauth2-scopes/#security-in-decorator-dependencies  link to  Depends in the decorator's dependencies parameter (https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-in-decorator/) results in a 404.

**Comment by tiangolo** [comment]
Thanks! @dmontagu fixed it in #275 . It should be OK now.
