### ISSUE TITLE
[BUG] Generic typehints causing mypy errors

### ISSUE THREAD

**Issue by dmontagu** [tiangolo/fastapi#276]
**Describe the bug**
The following code results in a mypy error
```python
from typing import List
from fastapi import FastAPI, params

def admin_dependencies() -> List[params.Security]:
    return []

app = FastAPI()

@app.get("/", dependencies=admin_dependencies())
def admin_endpoint():
    pass
```
The mypy error is
```
error: Argument "dependencies" to "get" of "FastAPI" has incompatible
    type "List[Security]"; expected "Optional[List[Depends]]"
```
This error is occurring because `List` is invariant. However, if I understand correctly, in this case `dependencies` can be safely type hinted as `Sequence`, which is covariant (and would fix the mypy error). This specific case (for `dependencies`) occurs in a few places that could probably be replaced.

This is probably also the case for the `routes` argument to `FastAPI`.

**Comment by tiangolo** [comment]
Thanks for the report. I'll check it soon.

**Comment by tiangolo** [comment]
Thanks for the clear report, with auto-contained test and explanation :heavy_check_mark:

This is handled in #338 and will be included in the next release :rocket:
