### ISSUE TITLE
how to accept the part dict of the json body as the dict rather than the entire json body

### ISSUE THREAD

**Issue by 0warning0error** [tiangolo/fastapi#2927]
OS: Ubuntu 18.04 LTS
Python version: 3.6.9
fastapi: 0.63.0

This is part of my code

```python
@router.post("/register")
async def register(user:dict = Body(...)):
    "the code"
```
However, when I sent the body like below
```python
{
  "user":{
    "name":"john",
    "age":14,
    "position": "engineer"
  }
}
```
I wanted the param _user_ to be accepted as
```python
{
    "name":"john",
    "age":14,
    "position": "engineer"
  }
```
but it turned out to be the entire body
```python
{
  "user":{
    "name":"john",
    "age":14,
    "position": "engineer"
  }
}
```

**Comment by tiangolo** [comment]
Thanks for the help here @raphaelauv ! 👏  🙇 

I'm not sure I understood what you needed but I'm glad you solved your use case!

Thanks for reporting back and closing the issue 👍 :coffee: 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
