### ISSUE TITLE
frozenset not working as expected

### ISSUE THREAD

**Issue by as24-asingla** [tiangolo/fastapi#2932]
### First check

* [x] I added a very descriptive title to this issue.
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [x] After submitting this, I commit to one of:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Example

Here's a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with my use case:

```Python
from fastapi import FastAPI

app = FastAPI()


@app.get("/prices", name='Prices for stocks')
def get_prices(stocks: Optional[frozenset]):

    return 23
```

### Description

I get an error 422 when run the query on /docs page itself.

````JSON
{
  "detail": [
    {
      "loc": [
        "query",
        "stocks"
      ],
      "msg": "value is not a valid frozenset",
      "type": "type_error.frozenset"
    }
  ]
}
```
### Environment

* OS: macOS
* FastAPI Version: 0.63.0

To know the FastAPI version use:

```bash
python -c "import fastapi; print(fastapi.__version__)"
```

* Python version: 3.8.5

To know the Python version use:

```bash
python --version
```

**Comment by ycd** [comment]
`Python version: 2.7.18` a typo or?

**Comment by as24-asingla** [comment]
Sorry, its 3.8.5. 2.7.18 was the version of my EC2 instance and not docker.

**Comment by juntatalor** [comment]
@as24-asingla Hi! frozenset was not processed as a sequence (but set did). I suggest a solution in #2938

**Comment by theo-brown** [comment]
Hi, I've got this issue as well. Looks like #2938 hasn't been merged.

**Comment by tiangolo** [comment]
Hey there! Thanks for the discussion. This was solved by @juntatalor in https://github.com/tiangolo/fastapi/pull/2938 :tada: 

It will be available in the next version, released in a couple of hours, FastAPI `0.81.0`. :rocket:

**Comment by kannanwisen** [comment]
`@app.post("/FrozenSet")
def frozen_set(param1: FrozenSet[str] = Body(default=None)):
    print(param1, type(param1))
    return param1`

![image](https://user-images.githubusercontent.com/27722774/195856069-b526fff4-b248-4767-a829-d782ea3c6ce5.png)

If I pass like this, i get the below error.

![image](https://user-images.githubusercontent.com/27722774/195856252-599db11d-1a4e-4eb8-a593-61c0e2f74aed.png)

If i pass like below, it works.

![image](https://user-images.githubusercontent.com/27722774/195856428-9adbae78-b26b-4812-9eeb-d35e95a22462.png)

**Comment by kannanwisen** [comment]
Even same for bytes data type
