### ISSUE TITLE
[BUG] Dead link in the doc

### ISSUE THREAD

**Issue by meandus** [tiangolo/fastapi#303]
**Dead link**

in the page : https://fastapi.tiangolo.com/tutorial/response-directly/
there is "document it" link, this one returning "404"

**To Reproduce**
404 : https://fastapi.tiangolo.com/tutorial/response-directly/tutorial/additional-responses/

**Comment by tiangolo** [comment]
Thanks for reporting it @meandus !

@dmontagu fixed it in #306. It should be OK now.

I'll close this issue now, but feel free to add more comments or open new issues.
