### ISSUE TITLE
Official support for python 3.9

### ISSUE THREAD

**Issue by vlcinsky** [tiangolo/fastapi#3190]
### First check

* [x] I added a very descriptive title to this issue.
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [x] After submitting this, I commit to:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * Or, I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Description

FastAPI officially declares support for python up to version 3.8. This holds true in `pyproject.toml` and in declaration of tested python versions.

At the same time, FastAPI installs on python 3.9 and works without problem.

### The solution you would like

- Extend tests to include also python 3.9
- Declare support for python 3.9 in `pyproject.toml`, so that on https://pypi.org/project/fastapi/ it shows support for it.

### Additional context

There are also docker images for FastAPI such as [tiangolo/uvicorn-gunicorn-fastapi-docker](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker) which currently declare support up to python 3.8 and not for python 3.9.

Anyway, these things can go it's own upgrade path.

**Comment by Kludex** [comment]
https://github.com/tiangolo/fastapi/pull/2298/

**Comment by Hultner** [comment]
I use FastAPI with python 3.9, and does so in docker. Been doing since shortly after the 3.9 release back in October. 
As for my docker-image I use the tiangolo/uvicorn-gunicorn:python3.8 image in my build stages to copy over all the scripts and unicorn config. Then I set it up in a very similar fashion with some minor tweaks based on our production environment.

**Comment by Kludex** [comment]
I guess the thing is here is to be _official._

**Comment by Hultner** [comment]
Yes I agree, should have been more clear.
My posting was meant to reassure that more users are using FastAPI with 3.9 successfully.

**Comment by nilansaha** [comment]
Any update on this ?

**Comment by vlcinsky** [comment]
In package metadata at https://github.com/tiangolo/fastapi/blob/master/pyproject.toml#L31 is python 3.9 compatibility declared.

Test suite https://github.com/tiangolo/fastapi/blob/master/.github/workflows/test.yml#L13 covers python 3.9 too.

PR #2298 is merged and is awaiting next release, changelog already declares 3.9 compatibility in [release notes](https://fastapi.tiangolo.com/release-notes/) in section "Latest changes".

Closing.
