### ISSUE TITLE
[QUESTION] One or more objects in request body?

### ISSUE THREAD

**Issue by kevlar1818** [tiangolo/fastapi#379]
**Description**

I'd like to have an endpoint in my API that accepts one or more objects in the request body. For example, I would like both of these to be valid request bodies:

``` javascript
{
  "name": "foo"
}
```

``` javascript
[
  {"name": "foo"},
  {"name": "bar"}
]
```

I'm not sure how to do this in fastapi/pydantic. Is it even possible? Any advice?

**Comment by dmontagu** [comment]
I haven't yet seen anything like this implemented in FastAPI, but I think a reasonable starting point would be to try to use the recently-added custom root model feature in pydantic: https://github.com/samuelcolvin/pydantic/pull/628 and https://github.com/samuelcolvin/pydantic/issues/507 (I am not sure whether FastAPI is compatible with the appropriate version of pydantic yet).

Note that it would be straightforward to handle either case if contained inside an object wrapper, i.e.:
```
{
    "name_data": {
        "name": "foo"
    }
}
```
vs.
```
{
    "name_data": [
        {"name": "foo"},
        {"name": "bar"},
    ]
}
```
which (I believe) could be implemented via
```python
class Name(BaseModel):
    name: str

class NameData(BaseModel):
    name_data: Union[Name, List[Name]]

**Comment by kevlar1818** [comment]
@dmontagu Thanks for the response. Yes, I'm aware of the pattern you mention above, but I want to avoid wrapping my object(s) as such. I've also run into problems with Pydantic when it tries to marshall Unions with collection types like in your example above; I might try running your example to see if it works. Lastly, I've also looked at the custom root models in Pydantic, and I had some troubles getting a custom validator to work with one (and your concern about FastAPI compatibility is valid).

**Comment by dmontagu** [comment]
@kevlar1818 

`Union` is currently somewhat finicky in pydantic due to the way it is implemented -- the order matters because it will try to parse types in the provided order. For what it's worth, if you have issues with pydantic `Union` parsing, I would encourage you to open a github issue over on the pydantic repository -- if the problem _isn't_ a bug (which it might be), you'll probably get a suggestion for how to accomplish your goal.

-----
For what it's worth, the following script does work for me:
```python
from typing import List

from pydantic import BaseModel, Union


class Name(BaseModel):
    name: str


class NameData(BaseModel):
    name_data: Union[Name, List[Name]]


data1 = {
    "name_data": {
        "name": "foo"
    }
}

data2 = {
    "name_data": [
        {"name": "foo"},
        {"name": "bar"}
    ]
}

print(NameData(**data1))
# NameData name_data=<Name name='foo'>

print(NameData(**data2))
# NameData name_data=[<Name name='foo'>, <Name name='bar'>]
```
-----
If your issue with the container approach is that you don't want to write a container model for every list-or-object type you want to have, you can leverage `pydantic.generics.GenericModel`:

```python
from typing import List, TypeVar, Generic

from pydantic import BaseModel, Union
from pydantic.generics import GenericModel

T = TypeVar("T")


class Name(BaseModel):
    name: str


class ListOrObject(GenericModel, Generic[T]):
    contained: Union[T, List[T]]


data1 = {
    "contained": {
        "name": "foo"
    }
}

data2 = {
    "contained": [
        {"name": "foo"},
        {"name": "bar"}
    ]
}

data3 = {
    "contained": "string1"
}

data4 = {
    "contained": ["string1", "string2"]
}

print(ListOrObject[Name](**data1).contained)
# Name name='foo'

print(ListOrObject[Name](**data2).contained)
# [<Name name='foo'>, <Name name='bar'>]

print(ListOrObject[str](**data3).contained)
# string1

print(ListOrObject[str](**data4).contained)
# ['string1', 'string2']
```
(The above script runs for me as is)

**Comment by kevlar1818** [comment]
Thanks for the detailed response! I'll consider these options and decide how to proceed. I'll mark this issue as closed unless someone else objects.

**Comment by tiangolo** [comment]
Thanks for the help @dmontagu 🌮!

Thanks @kevlar1818 for reporting back and closing the issue.
