### ISSUE TITLE
Utility function for gathering the experts from the discussions tab

### ISSUE THREAD

**Issue by ghandic** [tiangolo/fastapi#3947]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import requests
from collections import Counter

headers = {"Authorization": "token XXX"}


def run_query(query):
    request = requests.post("https://api.github.com/graphql", json={"query": query}, headers=headers)
    if request.status_code == 200:
        return request.json()
    else:
        raise Exception("Query failed to run by returning code of {}. {}".format(request.status_code, query))


def get_all_discussion_experts():
    after = ""
    output = []
    while True:
        query = f"""
            query {{
                repository(owner: "tiangolo", name: "fastapi") {{
                    discussions(first: 100{f', after:"{after}"' if after else ''}) {{
                        totalCount # Int!

                        pageInfo {{
                            endCursor
                            hasNextPage
                        }}

                        nodes {{
                            # type: Discussion
                            author {{
                                    login
                                }}
                            answer {{
                                author {{
                                    login
                                }}
                            }}
                        }}
                    }}

                }}
            }}
        """
        result = run_query(query)
        print(result)
        for node in result["data"]["repository"]["discussions"]["nodes"]:
            # Needs an answer and cant be the creator of the discussion
            if (
                (node["answer"] is not None)
                and (node["author"] is not None)
                and (node["author"]["login"] != node["answer"]["author"]["login"])
            ):
                output.append(node["answer"]["author"]["login"])

        if not result["data"]["repository"]["discussions"]["pageInfo"]["hasNextPage"]:
            break
        after = result["data"]["repository"]["discussions"]["pageInfo"]["endCursor"]

    return Counter(output)



result = get_all_discussion_experts()
print(result)
```

### Description

Allows @tiangolo an easy way to pull out all of the counts of people who have answered questions on the discussions panel

### Wanted Solution

NA

### Wanted Code

```python
NA
```

### Operating System

Linux

### FastAPI Version

NA

### Python Version

NA

**Comment by ghandic** [comment]
Add your own token - could be automated using github actions

Currently returns 
```python
Counter({'Mause': 6, 'r-bar': 3, 'Tert0': 1, 'ghandic': 1, 'dbanty': 1, 'FyZzyss': 1, 'StephenPCG': 1, 'mxp-xc': 1, 'yifeikong': 1, 'alukach': 1, 'Hultner': 1, 'jcwilson': 1, 'sm-Fifteen': 1, 'jjwwiodyne': 1, 'houmie': 1, 'yhatpub': 1, 'frankie567': 1, 'kbakk': 1, 'SnkSynthesis': 1, 'ichorid': 1})
```

**Comment by tiangolo** [comment]
Thanks! I recently refactored this including it in the FastAPI People script to include this. :nerd_face: 

I did it when switching to Discussions as the main place for questions, now that they support templates. 🚀

So I'll close this, but thanks for sharing it!

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
