### ISSUE TITLE
Preserve json.JSONDecodeError when handling invalid JSON in request body

### ISSUE THREAD

**Issue by declaresub** [tiangolo/fastapi#3993]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
not applicable
```

### Description

I think that the response to a request with syntactically invalid JSON should be 400, not 422.  This is the feature request I would prefer.  But I would be willing to write a custom exception handler for now, if that were feasible.

### Wanted Solution

   In FastAPI/routing.py line 210-211, we have 

        except json.JSONDecodeError as e:
            raise RequestValidationError([ErrorWrapper(e, ("body", e.pos))], body=e.doc)

I propose that the original exception not be discarded, by raising from -- 

        except json.JSONDecodeError as e:
            raise RequestValidationError([ErrorWrapper(e, ("body", e.pos))], body=e.doc) from e

With the original exception included, it would be simple enough to write a custom exception handler to handle the request as I see fit.  This change should not break anyone's code, and I think it is generally the better practice to use raise from in such situations.

### Wanted Code

```python
not applicable
```

### Operating System

Linux, macOS

### FastAPI Version

0.63.0

### Python Version

3.9.5

**Comment by UKnowWhoIm** [comment]
Is this currently being worked on @declaresub ?

**Comment by declaresub** [comment]
I don't know.  I would be happy to do it, but this is the first issue I've submitted to fastapi, and with 389 open pull requests, I didn't see the point spending time on a pull request that would never be looked at.

**Comment by tiangolo** [comment]
Thanks for posting it @declaresub! And thanks @UKnowWhoIm for the PR! :tada: :cake: 

This should be solved in https://github.com/tiangolo/fastapi/pull/4057 and will be available in the next version, released in some hours or the next days. (the current latest is `0.80.0`).

**Comment by Quix0r** [comment]
I know this is an old ticket, but isn't it `json.decoder.JSONDecodeError` instead? E.g. starlette uses the long version while this here the short version (lacking `.decoder` package in import reference).
