### ISSUE TITLE
GZip Middleware Throws "Response content longer than Content-Length" when given a 304 empty-body response

### ISSUE THREAD

**Issue by nicknotfun** [tiangolo/fastapi#4050]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Awaitable, Callable

from fastapi import FastAPI
from fastapi.middleware.gzip import GZipMiddleware
from starlette.requests import Request

app = FastAPI()


@app.middleware("http")
async def noop_middleware(request: Request, call_next: Callable[[Request], Awaitable]):
    return await call_next(request)


@app.get("/", status_code=304)
def youve_seen_this_before():
    pass


app.add_middleware(GZipMiddleware)
```

### Description

curl -sH "Accept-Encoding: gzip" localhost:8000

This will reliably:
a) Give the expected 304 empty response.
b) Show a stack trace "Response content longer than Content-Length"

The root cause I believe is the base middleware (in this example the noop one) creates a StreamingResponse for what is ultimately an empty response, it consists of two streaming chunks ("", more=True), ("", more=False); which bypasses the minimum length check in the GZip middleware.

GZip then compresses the 'nothing' resulting in the GZip minimum boilerplate, but an expected content length of 0 then throws. This is post-response so the client wont see the error but the server will.

### Operating System

Linux, macOS

### Operating System Details

Don't think this is relevant.

### FastAPI Version

0.63.0

### Python Version

 3.8.10

### Additional Context

This is actually the root cause of issue: https://github.com/tiangolo/fastapi/issues/2818

In the case of that issue the trigger is the StaticFiles mount has not-modified support, and on getting a non-modified static resource returns a 304. I suspect the original issue reporter stopped running into it either as a by-product of not getting 304 as often, or alternatively changing their middleware so as not to create the StreamingResponse.

**Comment by nicknotfun** [comment]
FYI, I believe this reproduces on any empty response (confirmed on 204 as well, 200 works as it technically has a body)

**Comment by levrik** [comment]
Experiencing the same issue

**Comment by hiranp** [comment]
We encountered this problem on in internal application when adding both GZIP and Brotli compression.  We tested the following fix using several use cases. 
https://github.com/encode/starlette/pull/1579

**Comment by tiangolo** [comment]
This can be reproduced even without the `GzipMiddleware`:

```Python
from fastapi import FastAPI

app = FastAPI()


@app.get("/", status_code=204)
def endpoint():
    print("Oh, hi mark")
```

More details in this Starlette issue: https://github.com/encode/starlette/issues/1764

I'm fixing it on Starlette here: https://github.com/encode/starlette/pull/1765

And I'm fixing it on FastAPI here: https://github.com/tiangolo/fastapi/pull/5145

It will be available in the next version, released in some hours, FastAPI `0.79.0` :tada:

**Comment by Yolley** [comment]
@tiangolo I think we need to update starlette version in FastAPI dependencies, the issue with GZip Middleware was fixed in 0.20.1 https://github.com/encode/starlette/pull/1579

Currently fix provided by https://github.com/tiangolo/fastapi/pull/5145 does not work if GZip Middleware is used.

**Comment by Kludex** [comment]
> This can be reproduced even without the `GzipMiddleware`:
> 
> ```python
> from fastapi import FastAPI
> 
> app = FastAPI()
> 
> 
> @app.get("/", status_code=204)
> def endpoint():
>     print("Oh, hi mark")
> ```
> 
> More details in this Starlette issue: [encode/starlette#1764](https://github.com/encode/starlette/issues/1764)
> 
> I'm fixing it on Starlette here: [encode/starlette#1765](https://github.com/encode/starlette/pull/1765)
> 
> And I'm fixing it on FastAPI here: #5145
> 
> It will be available in the next version, released in some hours, FastAPI `0.79.0` tada

Those 2 are different issues.

**Comment by Kludex** [comment]
@tiangolo I mean, those are different issues, but both were fixed.

**Comment by tiangolo** [comment]
Ah! Great, thanks @Kludex ! 🚀
