### ISSUE TITLE
Update Starlette to 0.18.0 to solve some issues fastapi will have on FIPs enabled systems

### ISSUE THREAD

**Issue by tonybutt** [tiangolo/fastapi#4477]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
No code needed see starlette's release notes.
```

### Description

Please bump starlette version to 0.18.0 to get the haslib.md5() function fixes for FIPs enabled systems

### Operating System

Linux

### Operating System Details

Ubuntu 20.04

### FastAPI Version

0.73.0

### Python Version

3.9

### Additional Context

Starlette recently fixed a FIPs system issue in version 0.18.0. Would like to see starlette bumped a version up so we don't have to fork fastapi.

**Comment by newsman2** [comment]
I also ran into the same problem. Hope to bump to 0.18.0

**Comment by tiangolo** [comment]
Thanks! This was handled in #4483 by @Kludex :rocket: 

This will be available in the next release in a couple of hours, FastAPI `0.76.0` :label:
