### ISSUE TITLE
[FEATURE] Add favicon to swagger/redoc

### ISSUE THREAD

**Issue by wshayes** [tiangolo/fastapi#46]
**Is your feature request related to a problem? Please describe.**

Would like favicon for Swagger/ReDoc. I generally have a ton of tabs open in my browser and it helps me figure out which one to open.

**Describe the solution you'd like**

I can enter a PR to add the favicon from a CDN service (https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/favicon-32x32.png) to the html file you generate for swaggerui and redoc.

**Comment by tiangolo** [comment]
Good idea!

It's implemented in `0.6.3` :tada: 

https://github.com/tiangolo/fastapi/pull/53

**Comment by wshayes** [comment]
Thanks!
