### ISSUE TITLE
[BUG] ValidationError missing constructor argument in routing module (L54)

### ISSUE THREAD

**Issue by Ghost-in-a-Jar** [tiangolo/fastapi#460]
**Describe the bug**
This ValidationError: https://github.com/tiangolo/fastapi/blob/master/fastapi/routing.py#L54 is being instantiated with only 1 argument. As you can see here: https://github.com/samuelcolvin/pydantic/blob/master/pydantic/error_wrappers.py#L51 a pydantic ValidationError requires a model argument as well.

**To Reproduce**
1. Write a Model with a validation error.
2. Hit this line of code: `raise ValidationError(errors)` https://github.com/tiangolo/fastapi/blob/master/fastapi/routing.py#L54
3. See this exception: `TypeError: __init__() missing 1 required positional argument: 'model'`

**Environment:**
 - OS: macOS
 - FastAPI Version: 0.35.0

**Comment by dmontagu** [comment]
@Ghost-in-a-Jar this is due to incompatibility with the most recent version of pydantic. Currently fastapi only supports pydantic<=0.30; I believe that change happened in 0.31.

Hopefully we can get an upgrade for compatibility with pydantic 0.32 soon 🤞.

**Comment by tiangolo** [comment]
Thanks for the report @Ghost-in-a-Jar and thanks for the help @dmontagu.

The most recent version of FastAPI sports Pydantic 0.32, so this should be solved there.

I'll close this now, but feel free to add more comments or create new issues.
