### ISSUE TITLE
[FEATURE] Updating pydantic

### ISSUE THREAD

**Issue by wshayes** [tiangolo/fastapi#47]
**Is your feature request related to a problem? Please describe.**

I need the ability to use the Extra.forbid config option to indicate when I have extra values in my pydantic model. This feature landed in v0.19.0 and was fixed/enhanced in v0.20.0. There appears to be one breaking change in v0.20.0 since v0.18.2 (which is what is currently locked for fastapi)

**Describe the solution you'd like**
I'd like to update to pydantic v0.20.0. I can generate a PR for this, but I'm not sure why you locked it at v0.18.2

**Comment by tiangolo** [comment]
Yes, I'll update it soon. There are a couple breaking changes (mainly in the type definitions).

It is pinned because as these packages are still in versions `0.x`, it means that any change could be a breaking change, as we (Starlette, Pydantic, FastAPI, etc) are still all evolving and improving quite quickly.

But I'll update it soon.

**Comment by wshayes** [comment]
Completely understand the pinning. I don't understand the codebase well enough to do the PR most likely but I'm happy to tilt at this or something else to help out. We are really enjoying using FastAPI.

**Comment by euri10** [comment]
I begun a branch on that, I'm not a mypy pro so not sure I should PR an unfinished attempt, if you're interested in looking at it it's on https://github.com/euri10/fastapi/tree/pydantic_0.20.0
I have still some typing issues, I got no tests problems despite the breaking changes listed in pydantic changelog, which I find strange, so my work may be complete crap :drooling_face:

**Comment by edrodri2** [comment]
Would updating this add support for skip_defaults for pydantic models added in 0.20.0 or would this need more changes? I would like to be able to not show null values in my responses.

**Comment by tiangolo** [comment]
It is updated now, compatible with the latest Pydantic :tada:

It's available in version `0.9.0`.

Thanks @euri10, I couldn't see your branch (it gives 404 for some reason). But it's updated now.

@edrodri2 Nope, because `skip_defaults` must be called in the `dict` and `json` methods, that are called automatically.

One option would be to include, apart from a `response_model` parameter, another parameter (maybe something like `model_extra`) with a dict of `kwarg` options to pass to Pydantic's `dict` directly. It would be used internally by FastAPI.

How does that sound?

**Comment by StepanBakshayev** [comment]
I have a issue with pydantic 0.21, but pydantic 0.23 works fine. Please, update pydantic. Do you have schedule of next release?

```python
from pydantic import BaseModel, ValidationError, constr
from typing import List, Optional


class Phone(BaseModel):
    id: Optional[int]

    phone: constr(min_length=10, max_length=30)
    additional_code: Optional[constr(min_length=1, max_length=30)]


class Representative(BaseModel):
    id: Optional[int]

    name_last: constr(min_length=1, max_length=100)
    name_first: constr(min_length=1, max_length=100)
    name_middle: Optional[constr(min_length=1, max_length=100)]
    phone: Phone


class CorporateEntity(BaseModel):
    id: Optional[int]

    name: constr(min_length=1, max_length=300)
    representatives: Optional[List[Representative]]


try:
    CorporateEntity(**{
        'name': 'Corporate',
        'representatives': [{
            'name_last': 'name_last',
            'name_first': 'name_first',
            'name_middle': 'name_middle',
            'phone': {
                'phone': '123'}}]})
except ValidationError as e:
    print(e.json())

#
## Unexpected result in 0.21
#
"""
[
  {
    "loc": [
      "phone",
      "phone"
    ],
    "msg": "ensure this value has at least 10 characters",
    "type": "value_error.any_str.min_length",
    "ctx": {
      "limit_value": 10
    }
  },
  {
    "loc": [
      "representatives"
    ],
    "msg": "value is not none",
    "type": "type_error.none.allowed"
  }
]
"""

#
## Expected result in 0.23
#
"""
[
  {
    "loc": [
      "representatives",
      0,
      "phone",
      "phone"
    ],
    "msg": "ensure this value has at least 10 characters",
    "type": "value_error.any_str.min_length",
    "ctx": {
      "limit_value": 10
    }
  },
  {
    "loc": [
      "representatives"
    ],
    "msg": "value is not none",
    "type": "type_error.none.allowed"
  }
]
"""
```

**Comment by tiangolo** [comment]
@StepanBakshayev The just-released FastAPI version `0.16.0` is compatible with Pydantic `0.23` :tada: (thanks to @euri10 's PR)

**Comment by StepanBakshayev** [comment]
I used it. You solved the issue fastly and completely.

**Comment by tiangolo** [comment]
Great @StepanBakshayev !
