### ISSUE TITLE
[BUG] route_class not preserved when calling APIRouter.include_router

### ISSUE THREAD

**Issue by dmontagu** [tiangolo/fastapi#539]
**Describe the bug**

When calling `APIRouter.include_router`, the class of the included routes should be preserved. Right now, this is not the case -- the `route_class` of the parent router is used. This means that the `route_class` is lost on inclusion if one isn't careful. Worse, it means that even if you manually create a router with multiple route-types present, there is no way to include that router in another without changing the route type of some of the routes.

See the `include_typed_router` function from #521 for an example of how this currently requires a workaround.

I have addressed this in the short PR #538, but wanted to create an issue for discussion in case there is any reason to preserve the current behavior.

**Comment by sandys** [comment]
is there an update on this PR ? i see that more bugs of this category are being filed - https://github.com/tiangolo/fastapi/issues/558

**Comment by dmontagu** [comment]
I'm wondering if maybe it would be better to rework things so that `include_router` doesn't re-instantiate the entire route from its attributes, but instead copies the route and just modifies the relevant properties as appropriate.

That would eliminate the need for this PR, and make router inclusion more robust to boot.

@tiangolo thoughts?

**Comment by sandys** [comment]
@dmontagu your PR on the deep copy was having trouble on 3.6. Also - do you believe from a performance perspective deepcopy is less performant than reinstantiation ?

@tiangolo ?

**Comment by dmontagu** [comment]
@sandys I noticed the problem with 3.6 but didn’t want to invest more in fixing it without some more feedback. (I’m not sure the changes are likely to be accepted yet even if I did work through the 3.6 issues.)

It’s not about performance — this happens once during app initialization, and will be insignificant from a performance perspective.

The thing that I find awkward about the code as it exists now is that the route is reinstantiated when calling include_router, potentially using a different class than the one that was used to create it in the first place. From a design perspective this feels a little awkward to me — the idea of “including” the router really seems to me more about the path (and possibly the extra dependencies and openapi spec considerations like tags). I feel like the class of the router (and any associated custom initialization of the route) should ideally not be repeated.

I can see multiple ways in which this design is convenient (doing the refactor wasn’t totally straightforward), but it also makes it a little more awkward to extend in creative ways.

**Comment by sandys** [comment]
Understood. I will let you be the judge of that.

Thanks for replying.

**Comment by dmontagu** [comment]
@sandys I fixed the above referenced PR to work with 3.6; now I think both #538 and #568 are valid fixes for this "bug". We can let @tiangolo decide which (if either) solution is preferable.

**Comment by sandys** [comment]
that's brilliant!!
thanks so much.
