### ISSUE TITLE
[FEATURE] tags at APIRouter level

### ISSUE THREAD

**Issue by euri10** [tiangolo/fastapi#54]
**Is your feature request related to a problem? Please describe.**
I have a certain number of APIRouter, with for each of those a certain number of routes.
I want all routes that belong to a given APIRouter to have the same tag, and currently I'm achieving this by adding `tags=['Tag1']`  to each and every route.

**Describe the solution you'd like**
I got the feeling that I should be able to add the tags keyword directly to APIRouter and that all routes belonging to it inherit the tag.

Not sure it makes sense though but I feel it would avoid some useless repetition

**Comment by tiangolo** [comment]
Totally agree, good idea.

**Comment by nilsdebruin** [comment]
@tiangolo Just tested it, works like a charm!

**Comment by tiangolo** [comment]
Thanks for the report @nilsdebruin !

Thanks for the idea and PR @euri10 !

I'll close this issue now as your PR is already merged and tested :grinning:

But feel free to add new comments or issues.

**Comment by ReRubis** [comment]
And what do I do now if I want the opposite behavior?
