### ISSUE TITLE
[FEATURE] Ability to override the app-building in an APIRoute

### ISSUE THREAD

**Issue by dmontagu** [tiangolo/fastapi#540]
I would like to be able to more easily override the use of `get_app` near the end of `APIRoute.__init__` so that I can inject some custom handling of the request, response, or the request-to-response pipeline without needing to replace the entire pipeline.

This would be useful, for example, in #521 in order to determine a response class as a function of a header without needing to replicate the code to do this in every endpoint.

-----

### More detail:
Thanks to the ability to specify a `route_class` when creating an `APIRouter`, it is now possible to override some of the behaviors in `APIRoute`. In particular, this provides a more targeted way to modify the request and/or response coming from a specific route as part of the `APIRoute` implementation.

However, one of the better targets for modification is the `app` property, which is created at the end of a rather long `__init__` method. Moreover, the stored property is the result of wrapping the result of `fastapi.routing.get_app` (which is readily modified) with `starlette.routing.request_response`, and the result of this function does not expose the result of the original `get_app` for modification. As a result, overriding the behavior of the `route_class` can involve repeating an undesirable amount of code from the base implementation.

(See #521 for an example of how this can be useful.)

-----

I see two routes to improving this:

1. Refactor the end of the `APIRoute.__init__` so that `get_app` is called inside a method:

    Currently:
    ```python
        ...
        self.app = request_response(get_app(...))
    ```
    Desired:
    ```python
        ...
        self.app = request_response(self.get_app(...))

        def get_app(...):
            return get_app(...)
    ```
    This approach would (with minimal changes) make it easier to modify the request and response from an endpoint by just overriding `APIRoute.get_app` (see #521 for an example).

2. Refactor the `fastapi.routing.get_app` function to make use of a *class* to build the `app`, rather than returning a 50-line function to use as the app. Some care would be required in order to preserve performance, but if the function returned by `get_app` could be built from a class that breaks out the various parts of the process into discrete steps, it would make it much easier to modify some of the steps. For example:
    * It would make it substantially easier to conditionally transform the request body prior to parsing. This would substantially simplify some of the workflows discussed in #200 and #381. It would also enable things like parsing exotic serialization formats prior to passing them to pydantic (as desired in #521).
    * It would make it much easier to have the response_class depend on the request parameters (e.g., the `Accept` header) -- handling this in the endpoint means lots of boilerplate for handling the request in each endpoint, but handling it in middleware would require both reloading the serialized json *and* converting the starlette StreamingResponse resulting from `starlette.routing.request_response` back to the desired response class (and possibly converting it back into a StreamingResponse again after that). The `get_app` function feels like the obvious place to handle this.

    This could also be combined with point 1. above, and would make it easy to override each component of the app by overriding the class used to build the app in the `get_app` function, and then overriding the `APIRoute.get_app` method to use the modified app building process, with minimal code.

**Comment by tiangolo** [comment]
I think you already implemented this in a PR, right? :thinking: :sweat_smile: :man_shrugging:
