### ISSUE TITLE
Implement Textarea support

### ISSUE THREAD

**Issue by zackees** [tiangolo/fastapi#5419]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
Yes, this is a swagger UI issue.

Fastapi doesn't support a textinput line greater than one row tall. This code implements this by hacking the javascript:

https://stackoverflow.com/questions/69874134/fastapi-textarea-openapi-for-form-data

Could something like this be merged in for Fastapi?
```

### Description

See above

### Wanted Solution

https://stackoverflow.com/questions/69874134/fastapi-textarea-openapi-for-form-data

### Wanted Code

```python
https://stackoverflow.com/questions/69874134/fastapi-textarea-openapi-for-form-data
```

### Operating System

Linux, Windows, macOS

### FastAPI Version

0.79

### Python Version

3.10.4

**Comment by JarroVGIT** [comment]
Probably not, as you have to self host the JavaScript for that solution. I also don’t see FastAPI provide “hacky” solutions like this in the end product

**Comment by tiangolo** [comment]
Thanks for the help @JarroVGIT ! 🙇

@zackees you can override and customize Swagger UI as you need, you can see how here: https://fastapi.tiangolo.com/advanced/extending-openapi/

As this wouldn't belong in FastAPI, I'll close this issue. Thanks for the interest! ☕

**Comment by zackees** [comment]
Textarea is something that is very essential. People like to add multi line descriptions and I've hit this limitation in multiple projects now. Not having this as a stock feature is very disappointing.

**Comment by tiangolo** [comment]
That's probably a complaint you would need to do to Swagger UI and the OpenAPI spec, not to FastAPI.

Also, have in mind that Swagger UI is supposed to be a tool mainly for developers testing their APIs, not a fully featured admin interface for your app.
