### ISSUE TITLE
[FEATURE] Do not log warning if email-validator not installed

### ISSUE THREAD

**Issue by victornoel** [tiangolo/fastapi#542]
**Is your feature request related to a problem? Please describe.**

I don't use email validation with pydantic in fastapi and I don't want to have my logs polluted with a warning about it.
This sentiment is also shared in https://github.com/samuelcolvin/pydantic/issues/815

**Describe the solution you'd like**

There should be no warning logged.

I'm not clear if it's acceptable to just explode when email-validator is missing and an email field must be validated as suggested by https://github.com/samuelcolvin/pydantic/issues/815.

**Describe alternatives you've considered**

Leaving it like that, it's not the end of the world to have this warning :)

**Comment by samuelcolvin** [comment]
This check should be unnecessary in fastapi, pydantic will raise an import error when a model is initialised which includes an email field.

Surely they should be sufficient.

**Comment by dmontagu** [comment]
@samuelcolvin except those email-using objects may be desirable to use (as part of your open api schema) even without validation. I think it makes sense to warn about the removal of validation, but it should be easier to suppress I think.

**Comment by dmontagu** [comment]
I think something like this might be more appropriate; any thoughts?

```python
from enum import Enum
from typing import Any, Dict, List, Optional, Union
import warnings

from pydantic import BaseModel, Schema as PSchema
from pydantic.types import UrlStr

try:
    import email_validator

    assert email_validator  # make autoflake ignore the unused import
    from pydantic.types import EmailStr  # type: ignore
except ImportError:  # pragma: no cover
    warnings.warn(
        "email-validator not installed, email fields will be treated as str.\n"
        "To install, run: pip install email-validator\n",
        "To suppress this warning, set environment variable "
        "PYTHONWARNINGS=ignore:::fastapi.openapi.models",
        ImportWarning
    )
    class EmailStr(str):  # type: ignore
        pass

...
```

**Comment by samuelcolvin** [comment]
> even without validation

It's not validation that raises the `ImportError`, it's model initialisation. So even if no validation is called, the error will still occur. See [here](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/networks.py#L268).

**Comment by dmontagu** [comment]
Yes, sorry my point was just this: rather than adding email-validator as a dependency, I may just want to allow arbitrary strings as emails. But fastapi doesn’t want to do that without any warning to the user, which is why the warning exists.

**Comment by cjw296** [comment]
@dmontagu - I think this creates enough noise and confusion that if there's a desire to use `EmailStr` without `email-validator`, then the application doing that should take care of catching the `ImportError` rather than forcing the (what I suspect is the) vast majority of users who don't use `EmailStr` and have to go out of their way to silence the warning.

**Comment by dmontagu** [comment]
But it is used by fastapi internally -- is your point that you just don't want fastapi to warn you that it isn't going to validate email addresses if email-validator isn't installed?

**Comment by dmontagu** [comment]
For reference: https://github.com/tiangolo/fastapi/blob/55c4b5fb0bd260765b6eedbf8c200caa3cdc670e/fastapi/openapi/models.py#L16

https://github.com/tiangolo/fastapi/blob/55c4b5fb0bd260765b6eedbf8c200caa3cdc670e/fastapi/openapi/models.py#L28

(The above line is the only place where EmailStr occurs.)

Given how inconsequential this is (a single optional field on a rarely used type) I feel like it's probably worth just dropping the warning.

**Comment by cjw296** [comment]
When are the things in models.py used? It doesn't seem like it's worth doing email validation then, so maybe just change that to be a `str` and drop the dependency on the package all together?

**Comment by dmontagu** [comment]
I went through the codebase and I only see one place where a reference to an `EmailStr` leaves `models.py`:

* `fastapi.models.OpenAPI.info` is of type `fastapi.models.Info`
* `fastapi.models.Info.contact` is of type `Optional[Contact]`
* `fastapi.models.Contact.email` is of type `Optional[EmailStr]`
* `fastapi.models.OpenAPI` is used at the end of `fastapi.openapi.utils.get_openapi`.

The thing is, it is currently not possible to set the `info` field of the generated `OpenAPI` to contain a non-None contact using`fastapi.openapi.utils.get_openapi`. So I suppose those models are just for convenience if you want to implement your own function to build the `OpenAPI` instance if overriding `fastapi.FastAPI.openapi()`.

Given all of this, I'd agree that I think it makes sense to  drop the dependency.

(Note: the `EmailStr` type is also currently used in some of the tests, and the test do actually check that the generated schema says that the field has string format `'email'`. So either those tests would need to be changed, or `email-validator` would need to remain a development dependency. But I'm assuming we're fine with it as a development dependency.)

**Comment by cjw296** [comment]
`email-validator` as a test dependency seems sensible, but if we just turn that into a `str` field then those tests would need to change, right?

**Comment by dmontagu** [comment]
The tests don't check the schema of the openapi schema type -- they check the schema of an app which uses an unrelated model containing an EmailStr field. So those fields can remain as EmailStr. (There are no tests involving `fastapi.models.Contact`.)

**Comment by cjw296** [comment]
Ah, perfect!

**Comment by tiangolo** [comment]
Thanks for the conversation here everyone!

In a recent version, I added custom logic to log the warning only if the `EmailStr` is actually used, only if it receives a value: https://github.com/tiangolo/fastapi/pull/946

So, it should not show again, in most of the cases (only if you did custom stuff to include a contact in your OpenAPI).

That is available in latest version.

**Comment by cjw296** [comment]
I think this issue is good to close :-)

**Comment by victornoel** [comment]
yep, thanks to all!

**Comment by LoHertel** [comment]
For anyone (including me) who was wondering why the warning appears even if you don't use `EmailStr` explicitly:

Check whether you passed a contact email address to the `FastAPI` object:
```python
app = FastAPI(
    ...
    contact={
        "name": "Team Name",
        "url": "https://example.net/team",
        "email": "team@example.net",
    },
    ...
)
```

This causes `FastAPI` to validate the email address using `EmailStr`, which emits the warning. To prevent the warning, you might want to install `email-validator`.
