### ISSUE TITLE
How to manage a set of nested items without running the error "unhashable type"?

### ISSUE THREAD

**Issue by guhur** [tiangolo/fastapi#5618]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

class MyBaseModel(BaseModel):
    def __hash__(self):  # make hashable BaseModel subclass
        return hash((type(self),) + tuple(self.__dict__.values()))

class NestedItems(MyBaseModel):
    name: str

class Items(MyBaseModel):
    items: set[NestedItems]

@app.post("/offers/")
async def create_items(items: Items):
    return items

```

This can be tested with the following command:

```bash
uvicorn mre:app --reload &
curl -X 'POST' \
  'http://127.0.0.1:8000/offers/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "items": [
    {
          "name": "string"
    }
  ]
}'
```

### Description

* The following command triggers the error `TypeError: unhashable type: 'dict'`. 
* It works if I replace `NestedItems` by a simple `str`.
* It works if I replace `set` by a simple `list`.

### Operating System

Linux

### Operating System Details

Ubuntu 22.04

### FastAPI Version

0.86.0

### Python Version

3.11.0

**Comment by tiangolo** [comment]
What you are receiving from the client is not a Pydantic model but a JSON object (dict), I suspect that's the problem here, that the dict is what is not hashable. But I'm not sure.

You could try using a list and cleaning the duplicates in a Pydantic "validator".
