### ISSUE TITLE
Feature: The implementation of a class to manage cron tasks

### ISSUE THREAD

**Issue by GermanMT** [tiangolo/fastapi#5645]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import FastAPI, CronTasks

from time import sleep

app = FastAPI()

@app.on_event("startup")
async def startup_event():
    await some_function()

async def some_function(cron_tasks: CronTasks):
    cron_tasks.add_task(function = other_function, parameters = 'Some parameters', repeat_time = 216000) # Time in seconds; 24h = 216000

async def other_function(parameters):
    print(parameters)
    sleep(3)
```

### Description

Call a cron tasks class in my controllers or events to set up repetitive actions.

### Wanted Solution

When I launch my project with uvicorn I would like to have some cron tasks, like background tasks but repeated over time instead of in the background.

### Wanted Code

```python
I haven't thought about the solution yet, but I could do it if it is interesting for the community.
```

### Operating System

Linux

### FastAPI Version

0.87.0

### Python Version

3.10

**Comment by OpetherMB** [comment]
i would suggest that you use Celery, i think it's not a great idea for the FastAPI app to include such an overheat.
you can use workers that schedule a task and run after X time. i personnally use rq package it's lightweight lib that works with redis and you can duplicate your workers to run the task. there is also an async version of rq called arq by all means go and check them out. 
let me know if i can help
