### ISSUE TITLE
An error is displayed when the length of int type in response_model exceeds 16 bits

### ISSUE THREAD

**Issue by jingyifun** [tiangolo/fastapi#5988]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

example
id: int = 109037141215586310
The final display is: id = 109037141215586300

The length of the data in the example is 18 bits

python version: 3.11
fastapi version: 0.91.0

At present, I don't know if it is a framework problem, or other reasons! Thanks!

**Comment by tiangolo** [comment]
Hey there! It seems you are not @tiangolo 😅 ...and I didn't ask you to create an issue here. So I'll close this.

Please create a Discussion Question following all the template.
