### ISSUE TITLE
graphql example

### ISSUE THREAD

**Issue by rcox771** [tiangolo/fastapi#6]
It would be useful to show how to accomplish integrating fastapi with graphene or another graphQL interface. Its touched on lightly in the docs, but I couldn't find a complete example that reuses the good parts of fastapi and pydantic.

Is this too far out of scope for a suggestion?

**Comment by tiangolo** [comment]
Yep, it's still missing from the docs.

There are a couple other features that are provided directly by Starlette that I haven't documented yet. And some that I have to update the docs in Starlette directly first.

But I have it planned and I'll add them :smile:

**Comment by tiangolo** [comment]
GraphQL docs are now live at: https://fastapi.tiangolo.com/tutorial/graphql/ :tada: :rocket:

**Comment by rcox771** [comment]
thanks @tiangolo. I will definitely be on the lookout for the pydantic type-based stuff. I found a talk given by Alec Macqueen at Europython 2018 where he discusses some work his company was doing internally in this realm (type-annotation qraphql magic). I don't believe they open-sourced anything yet, but he may have some ideas that will help. I pinned the start time for ye for the juicy bits.

[![video](http://img.youtube.com/vi/LxoKPGvMXf0/0.jpg)](https://youtu.be/LxoKPGvMXf0?t=820"video")

**Comment by tiangolo** [comment]
Thanks for the video, I finally got to see it. It looks interesting indeed.

**Comment by necaris** [comment]
FYI @tiangolo (and anyone else who's interested) we just released our Graphene + Pydantic layer which we're using in a FastAPI project: https://pypi.org/project/graphene-pydantic/ -- hope it's helpful for folks!

**Comment by DTrafford** [comment]
> GraphQL docs are now live at: https://fastapi.tiangolo.com/tutorial/graphql/ :tada: :rocket: 

This link doesn’t work anymore

**Comment by phy25** [comment]
You should be able to search on the doc website but https://fastapi.tiangolo.com/advanced/graphql/

**Comment by lfvilella** [comment]
Hello there, inspired on the `graphene-pydantic` packaged I created the [pydantic2graphene](https://github.com/lfvilella/pydantic2graphene), this is a package that allows you to re-use the pydantic schemas that you use on your FastAPI endpoints to also generate graphene objects for your GraphQL endpoint.

You can checkout a full [example](https://github.com/lfvilella/pydantic2graphene/blob/master/docs/examples/fastapi_graphql_and_rest/api.py) of re-using schemas to get your REST and GraphQL endpoints running.
https://github.com/lfvilella/pydantic2graphene/blob/master/docs/examples/fastapi_graphql_and_rest/api.py
