### ISSUE TITLE
fastapi and sqlalchemy

### ISSUE THREAD

**Issue by roshanafara** [tiangolo/fastapi#6006]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

In fast API after execution of the code, the database connection is not closing using SQL alchemy how to resolve this issue?

**Comment by yinziyan1206** [comment]
I use `asynccontextmanager` to decorate the session in sqlalchemy. And I use connection pool, it will manage the connections in sqlalchemy

**Comment by moadennagi** [comment]
It depends on the database connection is created, it's hard to tell without a reproducible example.

**Comment by odiseo0** [comment]
You should check the [documentation](https://fastapi.tiangolo.com/tutorial/dependencies/)

**Comment by roshanafara** [comment]
app = FastAPI()




def get_db():
  engine = create_engine("mysql+pymysql://root@localhost3306/sample")
   SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
 


@app.get("/average_duration_shifwise")
def get_average_duration_shift(db: Session = Depends(get_db)):
    select_query = 'SELECT average_duration FROM average_duration'
    data = db.execute(select_query).fetchall()
    print(data)
    return {"message": "predicted successfully"}




if __name__ == "__main__":
    uvicorn.run("main
:app", host="0.0.0.0", port=4002, reload=True)

**Comment by odiseo0** [comment]
It should  be 
```python
engine = create_engine("mysql+pymysql://root@localhost3306/sample")
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def get_db():
    try:
        db = SessionLocal()
        yield db
    finally:
        db.close()
```
How did you know it did not close?

**Comment by roshanafara** [comment]
when giving show full process list the connection is still there and when giving the next request it adds a new connection.so if i like 20 request and 20 connection when giving 21 st connection the db may be slow

**Comment by odiseo0** [comment]
I don't get it

**Comment by Sahil481** [comment]
You could just set the db as None at the beginning and then check if it's null, if it is null then change execute db = SessionLocal()

I have not yet tested the code and am not sure if it will work

`
engine = create_engine("mysql+pymysql://root@localhost3306/sample")
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

db = None

def get_db():
    try:
        if db == None:
             db = SessionLocal()
        yield db
    finally:
        db.close()
`

**Comment by Sahil481** [comment]
You could just set the db as None at the beginning and then check if it's null, if it is null then change execute db = SessionLocal()

I have not yet tested the code and am not sure if it will work. Please correct me if this is not what you were looking for, or this did not solve your problem

```python
engine = create_engine("mysql+pymysql://root@localhost3306/sample")
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

db = None

def get_db():
     try:
          if db == None:
               db = SessionLocal()
          yield db
     finally:
          db.close()

```

**Comment by jgould22** [comment]
> when giving show full process list the connection is still there and when giving the next request it adds a new connection.so if i like 20 request and 20 connection when giving 21 st connection the db may be slow

Did you actually try and get 20 connections?. 

SQLAlchemy uses a connection pool, it will open and maintain a number of connections so it doesn't have to reconnect every time. By default the pool will keep up to 5 connections which is will open as you request them. 

To disable this behavior you can pass `poolclass=NullPool` to the engine when you init it(but you probably dont want to, databases can handle a lot of connections and it is inefficient to be opening and closing them needlessly all the time).

**Comment by Suhail-Ahm** [comment]
I'm using middleware.

```python
@app.middleware("http")
async def db_session_middleware(request, call_next):
    """
    Create a new SQLAlchemy session for each request, and close it afterwards.
    """
    with Session(engine) as session:
        request.state.db = session
        response = await call_next(request)
    return response
```

**Comment by tiangolo** [comment]
Hey there, although you checked that box, it seems you're not @tiangolo, and I didn't ask you to create this issue. :sweat_smile: 

So, please open a GitHub Discussion following all the template step by step. That will allow me or others to properly help you. :coffee: 

Given that, I'm gonna close this one.
