### ISSUE TITLE
[BUG] Unable to have List of Pydantic Model as route 'responses' model

### ISSUE THREAD

**Issue by nwalsh1995** [tiangolo/fastapi#628]
**Describe the bug**
When using `responses={...: {"model": List[PydanticModel]}}` in a route function there is an exception returned `AssertionError: A response model must be a Pydantic model` when attempting to run the application.

**To Reproduce**
```python
from fastapi import FastAPI
from pydantic import BaseModel

class T(BaseModel):
    a: int


app = FastAPI()

@app.get("/", responses={200: {"model": List[T]}})
def index():
    ... # This is never entered due to error when adding the route
```

**Expected behavior**
This behaves the same as `response_model=` since it is allowed and works as intended there.

**Environment:**
 - OS: macOS
 - FastAPI Version [e.g. 0.3.0], get it with: fastapi==0.42.0
 - Python 3.7.0

**Additional Context**
I was going to return my response directly but would like the schema to be automatically done based on the pydantic model. I was following the steps in https://fastapi.tiangolo.com/tutorial/additional-responses/

**Comment by iamaldi** [comment]
Hi @nwalsh1995 
On your code:

1. you should include ``` response_model=T ```
2. you should not be using ```List``` as it's not a Pydantic model
```python
@app.get("/", responses={200: {"model": List[T]}})
def index():
    ... # This is never entered due to error when adding the route
```

By reviewing documentation code (https://fastapi.tiangolo.com/tutorial/additional-responses/) I see that ```response_model``` attribute is used prior to every response model.
Instead, could you could try out:

```python
@app.get("/", response_model=T, responses={200: {"model": T}})
def index():
    ... # This is never entered due to error when adding the route
```

Also from the documentation we can clearly see that each response shall include a Pydantic model.
>  Each of those response dicts can have a key model, containing a Pydantic model, just like response_model.

**Comment by iamaldi** [comment]
@nwalsh1995  I've updated my suggestion, please take another look if you've already read it. Thanks

**Comment by dmontagu** [comment]
@iamaldi But isn't that the wrong response? Why would you want to document it as returning a `T` instead of a `List[T]`?

If I understand correctly, this seems like a bug, but I think it shouldn't be too hard to fix.

**Comment by iamaldi** [comment]
Well, by writing ```response_model=List[T]``` you're basically saying that the response should be a list of ```T``` then inside the responses, each model is going to be of model T.

Could you ellaborate a bit more on why this seems like a bug? I read all the available documentation and saw ```response_model=List[T]``` as the only available option to do this.

Thanks

**Comment by dmontagu** [comment]
The "model" for the response should be the actual type returned for the response. `response_model` is basically a shorthand for what to use in the case where everything goes as planned, but, for example, if you wanted to return a list of errors in the case of a 400, you'd want to have `responses={400: {"model": List[ErrorModel]}}`.

It seems to me like you are concerned with the schema making sense as a human, but the point is for it to be correct if interpreted by a machine (e.g., for client generation).

I don't see any reason why this version:

```python
@app.get("/", responses={200: {"model": List[T]}})
def index():
    ... # This is never entered due to error when adding the route
```
shouldn't result in the same openapi schema as this version:

```python
@app.get("/", response_model=List[T])
def index():
    ... # This is never entered due to error when adding the route
```

My suspicion is that this is only broken right now because most people don't frequently use this capability. I don't see any reason an arbitrary pydantic field couldn't be supported here.

**Comment by iamaldi** [comment]
@dmontagu Now I can see what the issue was in the first place. I was initially confused and thought this was a implementation-specific issue @nwalsh1995 had.

Thanks for the clarification.

**Comment by tiangolo** [comment]
Yep. Response models in the extra `responses` should receive any type valid for a Pydantic field, not only Pydantic models. That's a valid bug/feature request.

**Comment by tiangolo** [comment]
This was fixed by @patrickmckenna in https://github.com/tiangolo/fastapi/pull/1017.

It will be available in the next release. :rocket: :tada:
