### ISSUE TITLE
Uvicorn 0.5

### ISSUE THREAD

**Issue by tomchristie** [tiangolo/fastapi#66]
* reloading now works programmaticaly. Not just when running `uvicorn` from the console.
* Multi-worker support is available. (But not on by default)

Changes you'll want to make:

Switch the docs to `uvicorn --reload` instead of `uvicorn --debug`.

Debug tracebacks will be becoming strictly an application-level concern, and will disappear from uvicorn in a future version. If you want debug tracebacks, make sure you're using starlette's ServerErrorMiddleware, and switching it on or off appropriately depending on if FastAPI is running in a debug mode or not.

**Comment by tiangolo** [comment]
Thanks for taking the time to report it here! That's greatly appreciated :smile: 

I'll update accordingly.

---

I see [Uvicorn docs](https://www.uvicorn.org/deployment/) still suggest Gunicorn for production, is it still recommended?

**Comment by tomchristie** [comment]
*Shrug* Depends a bit on the deployment environment. Gunicorn has process monitoring, which unicorn doesn't - so *broadly* yes. But there's not so much in it ATM.

**Comment by tiangolo** [comment]
Get it, thanks!

I'll start exploring with Uvicorn's `--workers`.

I just updated all the docs relevant from `--debug` to `--reload`. Thanks for the report.

**Comment by tiangolo** [comment]
I'll close this issue now that the docs are updated. Again, thanks for the report!
