### ISSUE TITLE
Need a heroku specific deployment page

### ISSUE THREAD

**Issue by vnwarrior** [tiangolo/fastapi#669]
Need heroku specific deployment docs and a sample project just like this - https://github.com/bocadilloproject/bocadillo/blob/master/docs/how-to/heroku.md

**Comment by prostomarkeloff** [comment]
I think it isn't bug. You may create PR for it's. :)

**Comment by tiangolo** [comment]
Yep, as @prostomarkeloff says, that's not a bug 🤷‍♂️

In fact, it could make sense to have it as an external blog post linked, the same as deployments for other platforms.

I encourage you to write one! 🚀
