### ISSUE TITLE
Clarify user_dict in Extra Models

### ISSUE THREAD

**Issue by bastula** [tiangolo/fastapi#7]
Awesome project you have going on! Keep up the good work! 🎉

I was reading through the docs and in the Extra Models section, the About `**user_dict` sub-section doesn't explain why there is a difference between using `**user_dict` vs `**user_in.dict()`.

Also I wasn't sure if you meant to specify `user_dict` as a generic dictionary for the section as that object doesn't exist in the above code example, or did you mean to also continue to use `user_in`?

**Comment by tiangolo** [comment]
> Awesome project you have going on! Keep up the good work!

Thanks a lot! :tada: :smile: 

---

> I was reading through the docs and in the Extra Models section, the About **user_dict sub-section doesn't explain why there is a difference between using **user_dict vs **user_in.dict().

> Also I wasn't sure if you meant to specify user_dict as a generic dictionary for the section as that object doesn't exist in the above code example, or did you mean to also continue to use user_in?

Yes, I just checked and it had a couple of wrong variable names that messed up the whole idea :scream: . I think I mixed it when adding a similar note for the OAuth2 docs.

I just re-wrote that section taking your comments into account. It should be a lot clearer now: https://fastapi.tiangolo.com/tutorial/extra-models/#about-user_indict

**Comment by tiangolo** [comment]
I think the docs should be clearer now, so I'll close the issue. But feel free to re-open it, add more comments or create new ones.
