### ISSUE TITLE
FastAPI throw 'exception_handlers' attribute error

### ISSUE THREAD

**Issue by nielsonsantana** [tiangolo/fastapi#711]
**Describe the bug**
FastAPI is incompatible with Startlette handling error. The error is that `'FastAPI' object has no attribute 'exception_handlers'`. 
Here the trace error:
```
File "/app/soarapi/app.py", line 72, in <module>
	application = app = FastAPI()
File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 78, in __init__
	self.setup()
File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 130, in setup
	self.add_exception_handler(HTTPException, http_exception_handler)
File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 124, in add_exception_handler
	self.exception_handlers[exc_class_or_status_code] = handler
AttributeError: 'FastAPI' object has no attribute 'exception_handlers'
```

**To Reproduce**
Just run the tutorial to reproduce the error: [docs/handling_errors/tutorial004.py]( https://github.com/tiangolo/fastapi/blob/62af6e0eeb80672158d09260d3f341dcc08616bf/docs/src/handling_errors/tutorial004.py)

**Expected behavior**
I expected that the `exception_handler` interface worked similar as Starlette.

**Screenshots**
no

**Environment:**
 - OS: Linux - Ubuntu
 - FastAPI Version:  0.42.0
 - Python version: 3.7
 - Starlette Version: 0.13.0

**Comment by nielsonsantana** [comment]
I read about FastAPI deps and it compatible with Starlette 0.12.9.

**Comment by Ashok93** [comment]
Please reopen this issue as this issue persists with the latest version of `starlette`

**Comment by mmoravcik** [comment]
Hi when is FastAPI planning to support the latest version of Starlette? I am getting  errors for anything greater than 0.12.11

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue @nielsonsantana  :+1: 

---

FastAPI supports Starlette `0.13.2` since version `0.50.0` (we're at version `0.54.1` now).

**Comment by AuniChowdhury** [comment]
Still getting this error with Starlette version 0.13.4  and FastApi 0.58.0
