### ISSUE TITLE
[QUESTION] How can I add example responses to the swagger docs for an endpoint?

### ISSUE THREAD

**Issue by jjorissen52** [tiangolo/fastapi#723]
**Description**

How can I add example responses to the swagger docs for an endpoint?

This does not seem to work:
```python
from fastapi import FastAPI, APIRouter
from pydantic import BaseModel


app = FastAPI()
api = APIRouter()

class Message(BaseModel):
    message: str

    class Config:
        schema_extra = {
             'example': [{
                'message': 'Cool',
            }]
        }

@api.post("/activity", responses={200: {'model': Message}})
async def post_activity(body: dict = dict()):
    print(body)
    return Message(message="thanks")


app.include_router(
    api,
    prefix="/api",
    tags=["api"],
)

```

Result:

![image](https://user-images.githubusercontent.com/12461302/69287725-ed3a4e80-0bbc-11ea-88b7-2dd93c957046.png)

**Additional context**

This issue has been raised before, but the resolution was not shared.
https://github.com/tiangolo/fastapi/issues/549

**Comment by prostomarkeloff** [comment]
However, you can pass example response model as `response_model` attribute in decorator.

```python
@app.get(..., response_model=MyModel)

```

**Comment by tiangolo** [comment]
Thanks for the conversation here everyone!

@jjorissen52 check the new docs here: https://fastapi.tiangolo.com/tutorial/schema-extra-example/

**Comment by ilya-kolpakov** [comment]
See below on how to examples specifically to response models (which is not described in the docs)
https://betterprogramming.pub/how-to-add-multiple-request-and-response-examples-in-fastapi-ce2117eac7ed
