### ISSUE TITLE
Default favicon has very poor contrast against dark-themed browsers

### ISSUE THREAD

**Issue by sm-Fifteen** [tiangolo/fastapi#727]
**Describe the bug**
The current monochrome logo is a black circle on a transparent background, which makes it very hard to see against a dark background. Since I'm a ***1337 H4X0R*** who uses dark themes pretty much everywhere, this happens to be all the time and especially frustrating given I tend to have the FastAPI doc and/or the API documentation open alongside a number of github tabs, whose logo also happens to be a black and transparent circle-like shape.

**Screenshots**
![image](https://user-images.githubusercontent.com/516999/69455788-226aac00-0d37-11ea-917b-d62a08b6fd19.png)
(Firefox's dark theme on Windows above, Chrome's incognito mode below. FastAPI is the second tab from the left in both cases.)

**Expected behavior**
The teal icon could be used instead of black, or the lightning bolt could be colored white so that either the circle or the bolt is going to be clearly visible regardless of the background color.

**Additionnal context**
This has been bugging me for months now, and somehow I never thought of reporting this as a bug until now.

**Comment by prostomarkeloff** [comment]
LGTM

**Comment by skewty** [comment]
Fixed color is often essential to branding.  If you saw a big blue M sign would you think McDonalds?   Since a white lightning bolt in a teal circle is used on the documentation website, I would suggest that is the proper approach.

**Comment by tiangolo** [comment]
That's an interesting point. I'll try and see how it looks like :man_shrugging: :art:

**Comment by sm-Fifteen** [comment]
@tiangolo: So this issue seems to be part of the 20 or so (not counting translation tracking issues) that have been kept on the issue tracker instead of moved to discussions. This one in particular was submitted during FastAPI's first year and hasn't seen much attention since, so I personally expected to see it be closed or migrated. Does this mean anything with regards to this issue's relevance? Are there plans around this for an upcoming release?

**Comment by Lord-V15** [comment]
Another issue is the lack of a better theme in the docs. 
I actually dug very deep into the code some time ago and turns out the HTML CSS wrote for the swagger docs are extremely old (~10 years ago) and FastAPI uses it. 
Now, I'm no expert with CSS but something modern would look much better like the CSS created [here](https://github.com/ostranme/swagger-ui-themes/tree/master/themes/3.x)

**Comment by karolrzadczyk** [comment]
> Another issue is the lack of a better theme in the docs.
> I actually dug very deep into the code some time ago and turns out the HTML CSS wrote for the swagger docs are extremely old (~10 years ago) and FastAPI uses it.
> Now, I'm no expert with CSS but something modern would look much better like the CSS created [here](https://github.com/ostranme/swagger-ui-themes/tree/master/themes/3.x)

Is there a way to override the default theme with something like that? Without affecting the base code of fast api?

**Comment by hasnatsajid** [comment]
I also use dark themes :)

**Comment by Lord-V15** [comment]
> > I actually dug very deep into the code some time ago and turns out the HTML CSS wrote for the swagger docs are extremely old (~10 years ago) and FastAPI uses it.
> > Now, I'm no expert with CSS but something modern would look much better like the CSS created [here](https://github.com/ostranme/swagger-ui-themes/tree/master/themes/3.x)
> 
> Is there a way to override the default theme with something like that? Without affecting the base code of fast api?

The css is used via a URL so you need to change the package code which means you have to build from scratch and that's just too complicated for switching themes. 
Maybe @tiangolo can suggest something better? 😅

**Comment by tiangolo** [comment]
Now that the icon was updated, this is finally done! 🚀

**Comment by sm-Fifteen** [comment]
> Now that the icon was updated, this is finally done! 🚀

Only took... 4½ years, but better late than never!

I really like the new logo, BTW. Nice mix of the old lightning bolt, the general suggestion of an "F", and a shape I personally associate with [Hermes' winged sandals](https://stock.adobe.com/ca/images/wing-shoe-hermes-logo-line-simple-design-vector/416528336?prev_url=detail) (which makes sense, as he's a messenger god known for being fast). Pretty nifty stuff.
