### ISSUE TITLE
[BUG] Invalid Constrained Decimals (condecimal) cause 500 response code, rather than a 422 with explanation of what was invalid.

### ISSUE THREAD

**Issue by Sean1708** [tiangolo/fastapi#743]
**Describe the bug**
If an invalid `condecimal` is sent to a FastAPI service the service will return a 500 internal server error, instead of a 422 validation error. I can't reproduce this using Pydantic alone.

**To Reproduce**
1. Run the attached [`condecimal-500-server.py`](https://github.com/tiangolo/fastapi/files/3900830/condecimal-500-server.py.txt) file.
2. In a separate terminal run the attached [`condecimal-500-client.py`](https://github.com/tiangolo/fastapi/files/3900829/condecimal-500-client.py.txt) file.
3. [`condecimal-500-server.log`](https://github.com/tiangolo/fastapi/files/3900824/condecimal-500-server.log) shows what you will see in the terminal that is running the server, most of the invalid requests will return a 422 but the one that violates the decimal constraint raises a `TypeError`.
4. [`condecimal-500-client.log`](https://github.com/tiangolo/fastapi/files/3900823/condecimal-500-client.log) shows what you will see in the terminal running the client, basically the same info that you see in the server's logs.
5. Run the attached [`condecimal-500-pydantic.py`](https://github.com/tiangolo/fastapi/files/3900870/condecimal-500-pydantic.py.txt) file.
6. [`condecimal-500-pydantic.log`](https://github.com/tiangolo/fastapi/files/3900869/condecimal-500-pydantic.log) shows what you will see when running that file, Pydantic correctly raises a `ValidationError` when the constraint is violated indicating that this is not an bug in Pydantic.

**Expected behavior**
I expect a 422 response along with an explanation of what is invalid about the number to be returned, as happens when other invalid payloads are sent.

**Environment:**
 - OS: Linux
 - FastAPI Version: 0.44.0
 - Pydantic Version: 1.1.1
 - Python Version: 3.7.2

**Comment by dmontagu** [comment]
Okay, I figured this out. The issue is that error messages for condecimal include the limit in the context, and fastapi doesn't apply `jsonable_encoder` to the raw errors.

I'll open a PR to fix this.

----

Separately, it is much easier to debug issues if you can create reproducible examples using the starlette `TestClient`, like this:
```python
import decimal

import pydantic
from starlette.testclient import TestClient

import fastapi


class Request(pydantic.BaseModel):
    foo: pydantic.condecimal(gt=decimal.Decimal(1.0))


app = fastapi.FastAPI()


@app.post("/echo")
def margin(*, request: Request):
    return request


print(TestClient(app).post("/echo", json={"foo": 0.9}, ).content)
```

**Comment by tiangolo** [comment]
Thanks @Sean1708 for the report :mag: :bug: 

And thanks @dmontagu for the fix! That was fast! :rocket: You rock :guitar:

**Comment by Sean1708** [comment]
Yes, thanks for such a quick fix @dmontagu.

And I'll try to remember to use `TestClient` in the future, it seems so obvious in hindsight...
