### ISSUE TITLE
[BUG] asyncpg uuid implementation not recognized by fastapi because of too strict typechecking

### ISSUE THREAD

**Issue by RmStorm** [tiangolo/fastapi#755]
### Describe the bug

An alternative implementation of the `UUID` type is not serialized by fastapi but throws an error instead. This is because it is of type `asyncpg.pgproto.pgproto.UUID` instead of type `uuid.UUID`. However it is implemented in such a way that it does the exact same things as the regular UUID but just faster. Also,
```python
isinstance(asyncpg.pgproto.pgproto.UUID(), uuid.UUID) == True
```
this should make fastapi able to recognize it as a uuid.

### To Reproduce
1. Create a file called uuid_error.py with:

```Python
import uuid

from fastapi import FastAPI
from asyncpg.pgproto import pgproto

app = FastAPI()


@app.get("/normal_uuid")
def return_normal_uuid():
    regular_uuid = uuid.UUID("a10ff360-3b1e-4984-a26f-d3ab460bdb51")
    assert isinstance(regular_uuid, uuid.UUID)
    return {"normal_uuid": regular_uuid}


@app.get("/fast_uuid")
def return_fast_uuid():
    asyncpg_uuid = pgproto.UUID("a10ff360-3b1e-4984-a26f-d3ab460bdb51")
    assert isinstance(asyncpg_uuid, uuid.UUID)
    return {"fast_uuid": asyncpg_uuid}
```
2. Run it with uvicorn uuid_error:app
3. Open the browser and call the endpoint `/fast_uuid`.
4. It returns 'internal server error' .
5. But I expected it to return `{"fast_uuid":"a10ff360-3b1e-4984-a26f-d3ab460bdb51"}`.

### Expected behavior

I expected fastapi to jsonify the uuid and send, but instead it returns 'internal server error'. The precise error being thrown in the server is:
```
ValueError: [KeyError(<class 'asyncpg.pgproto.pgproto.UUID'>), TypeError("'asyncpg.pgproto.pgproto.UUID' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

### Environment

- OS: Linux Mint 19 Tara
- FastAPI Version: 0.44.0
- Python version: 3.8.0

### Additional context

I initially made an issue in the asyncpg repo asking them if they could fix it: https://github.com/MagicStack/asyncpg/issues/512 I think it's usefull as additional context for this issue.
The problem can be solved here in the fastapi code by improving the code a little. I'm working on a PR, this line seems to be the issue:
https://github.com/tiangolo/fastapi/blob/c200bc2240d48a4a27e96fba536351038eafc44f/fastapi/encoders.py#L113
I think it shouldn't use `type()` but it should instead use `isinstance()` this will make for slightly looser typechecking but I think that might be a good thing in this case?

**Comment by 1st1** [comment]
Including an explicit

```python
if isinstance(obj, uuid.UUID):
    return str(obj)
```

before line https://github.com/tiangolo/fastapi/blob/c200bc2240d48a4a27e96fba536351038eafc44f/fastapi/encoders.py#L108 would fix this issue.

**Comment by RmStorm** [comment]
> Including an explicit
> 
> ```python
> if isinstance(obj, uuid.UUID):
>     return str(obj)
>     # or, altrenatively, `return ENCODERS_BY_TYPE[uuid.UUID](obj)`
> ```
> 
> before line
> 
> https://github.com/tiangolo/fastapi/blob/c200bc2240d48a4a27e96fba536351038eafc44f/fastapi/encoders.py#L108
> would fix this issue.

I think I solved it in a more general way in #756 such that any other objects that subclass custom classes will also work from now one. I think that's nicer than only handling my case.

**Comment by pablogamboa** [comment]
introduced in asyncpg 0.20.0, 0.19.0 works fine with latest fastapi

**Comment by tiangolo** [comment]
Thanks @RmStorm for the report and PR!

And thanks @1st1 for your tip, an honor to have you here :smile:
