### ISSUE TITLE
[FEATURE] Docs for HTTP/2 support

### ISSUE THREAD

**Issue by pgjones** [tiangolo/fastapi#80]
Uvicorn is a great and fast HTTP/1 ASGI server that you recommend. I propose you recommend [Hypercorn](https://gitlab.com/pgjones/hypercorn) as a fast HTTP/2 ASGI server. 

I'm the Hypercorn author, so naturally very biased. Also congratulations on the recognition of your great work.

**Comment by tiangolo** [comment]
Thanks! That's a very good idea. And I feel flattered that you come here to suggest it :smile: 

I have a question, does Hypercorn support lifespan events? 'Cause in Starlette's docs it seems it doesn't (or didn't at some point): https://www.starlette.io/events/

I just want to make sure if I should put a note there, after adding Hypercorn to the docs.

**Comment by pgjones** [comment]
It does, ([update to Starlette](https://github.com/encode/starlette/pull/451)).

**Comment by tiangolo** [comment]
Thanks @pgjones ! It's now included in the docs :tada: https://fastapi.tiangolo.com/deployment/#alternatively-deploy-fastapi-without-docker

And in the main page too.

**Comment by pgjones** [comment]
🎉 Thanks!

**Comment by tiangolo** [comment]
Thanks to you :cake: 

And thanks for coming back and closing the issue.
