### ISSUE TITLE
[BUG][DOCUMENTATION] Sub application startup event never triggered

### ISSUE THREAD

**Issue by jonathanunderwood** [tiangolo/fastapi#811]
### Describe the bug

Startup event handlers for sub-applications never trigger.

### To Reproduce

```python
from fastapi import FastAPI


sub_app = FastAPI(openapi_prefix="/subapp")


@sub_app.on_event("startup")
async def sub_app_startup():
    print("++++ Sub-app startup event")  # Never fires


app = FastAPI()


@app.on_event("startup")
async def app_startup():
    print("++++ App startup event")


app.mount("/subapp", sub_app)


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, port=8000, host="0.0.0.0")  # nosec
```

Running the above shows:

```bash
$ python subapp_events.py
INFO:     Started server process [38462]
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Waiting for application startup.
++++ App startup event
INFO:     Application startup complete.
```

**Notice that `sub_app_startup()` is never run.**

### Expected behavior

I would expect the sub-application startup event handler to also run (although I am not sure what ordering I would expect).

### Environment

- OS: macOS
- FastAPI Version: 0.45.0
- Python version: 3.7.5

### Additional context

N/A

**Comment by jonathanunderwood** [comment]
Digging in to this a bit more, I can see that FastAPI merely exposes the Starlette lifecycle events and doesn't do anything special about them. 

In addition, this issue has been [raised previously against Starlette](https://github.com/encode/starlette/issues/649).

Since it's deemed out-of-scope by Starlette developers, I think the only action here would be to document this in the FastAPI docs i.e. call out explicitly that sub-application event handlers are ignored.

**Comment by dmontagu** [comment]
I also think it would be good to document this.

PR welcome!

**Comment by tiangolo** [comment]
Thanks for the investigation and for reporting back @jonathanunderwood , yep, it makes sense to have it documented.

**Comment by ehenry09** [comment]
Anyone find a way to handle this within the fast api app code?

I am using Google Cloud Run to deploy new revisions to the app. My current solution is to add a step to my CI to handle start up events which are not getting triggered by the `app.on_event("startup")` decorator.

**Comment by ClericPy** [comment]
I found this issue this days, so what should I do to trigger subapp's start_up callbacks?
It seems that fastapi.APIRouter's on_startup param has a similar feature.

**Comment by tiangolo** [comment]
@ClericPy it would have to be implemented in Starlette: https://github.com/encode/starlette/issues/649

**Comment by tiangolo** [comment]
This was documented in https://github.com/tiangolo/fastapi/pull/1554 by @amacfie :rocket:

**Comment by jonathanunderwood** [comment]
As an update, looks like there's activity upstream in Starlette to bring this capability in: https://github.com/encode/starlette/pull/1988

**Comment by devamin** [comment]
some updates about this feature, sometimes it is required specially when dealing with non-fastapi ASGI apps like socketio one https://github.com/miguelgrinberg/python-socketio/blob/main/src/socketio/asgi.py

**Comment by OmegAshEnr01n** [comment]
Yes, But there is an easy work around for this for now. 
Make a function that is responsible for the start up event for your sub app and call it in the main app startup function.

```
# Main app
@app.on_event("startup")
def spawn_children():
    model_sub_app.startup_function()

# Sub app
def startup_function():
    # Load model
    pass
```

I find this super useful for certain cases. For example if I am making an app which has one AI model loaded on each router I wouldnt be able to add features to them like socketio. So for now it appears that having a fastapi instance for such use cases and mounting it is ideal. Paired with the above mentioned startup function hack and its doable...

**Comment by dhilst** [comment]
What I did was to create a function to mount my application and register my event handlers in the parent app

```python
def mount_app(parent_app: FastAPI, path: str) -> None:
    parent_app.on_event("startup")(app_startup)
    parent_app.on_event("shutdown")(app_shutdown)
    parent_app.mount(path, app)
```

**Comment by unights** [comment]
I did something similar. Provide a reference for others.

```python
from contextlib import AsyncExitStack, asynccontextmanager

from fastapi import FastAPI
from starlette.routing import Mount


@asynccontextmanager
async def lifespan(app: FastAPI):
    async with AsyncExitStack() as stack:
        for route in app.routes:
            if isinstance(route, Mount) and isinstance(route.app, FastAPI):
                await stack.enter_async_context(
                    route.app.router.lifespan_context(route.app),  # noqa
                )
        yield

```
