### ISSUE TITLE
how to pass a custom logger to the fastapi app

### ISSUE THREAD

**Issue by BinNong** [tiangolo/fastapi#834]
### First check

* [ ] I used the GitHub search to find a similar issue and didn't find it.
* [ ] I searched the FastAPI documentation, with the integrated search.
* [ ] I already searched in Google "How to X in FastAPI" and didn't find any information.

### Description
Great! The performance of fastApi is impressive. I am going to deploy it. And I want to custom a  logger. Can I pass it to the app?

**Comment by Slyfoxy** [comment]
You can use logger like [loguru](https://github.com/Delgan/loguru). It has `InterceptHandler` that can help you to customize all logs.

Also you can see configuration example [here](https://github.com/mirumon/mirumon-backend/blob/master/app/common/config.py)

**Comment by tiangolo** [comment]
Yep, what @Slyfoxy said.

You can get the logger with:

```Python
import logging

logger = logging.getLogger("fastapi")
```
