### ISSUE TITLE
[FEATURE]: Add all parameters to the 'info' section of the OpenAPI specification

### ISSUE THREAD

**Issue by ka-zo** [tiangolo/fastapi#843]
### Is your feature request related to a problem
I cannot display the author details, license details, etc. nicely in the automatically generated documentation and in the OpenAPI specification. I want to be able to do this, when I call the app = FastAPI() statement.

### The solution you would like

I want to see this additional metadata in the info section of the generated OpenAPI specification. In order to achieve this, I need the FastAPI() call to support additional parameters, like termsOfService, contact and license.

### Describe alternatives you've considered

no alternatives.

### Additional context

Check OpenAPI specification.

**Comment by ka-zo** [comment]
I found the answer to my own question / request. It is possible to extend the generated OpenAPI specification with new fields, if you follow the guideline described in this link: https://fastapi.tiangolo.com/tutorial/extending-openapi/

This ticket can be closed, unless the developer team wants the FastAPI() call to support all the info parameters described here: https://swagger.io/specification/#infoObject

**Comment by tiangolo** [comment]
Thanks @ka-zo for reporting back your solution.

I think we could add an additional parameter to the `FastAPI` class to take the extra OpenAPI data. But I'm not sure yet about names, how many, and structure. And as this has not been commonly requested, it hasn't had a high priority.

I would accept a PR with it if someone was interested in it, though.

With respect to this issue, I think that for now we can take it as a question and close it. And if this comes up later and more people are requesting it and the current method is too cumbersome, we can think of adding it.

**Comment by ka-zo** [comment]
Agreed, and the solution described in the aforementioned link (https://fastapi.tiangolo.com/tutorial/extending-openapi/) is already satisfactory.

**Comment by tiangolo** [comment]
There's direct support for this now in FastAPI `0.68.0` 🔖🎉

https://fastapi.tiangolo.com/tutorial/metadata/
