### ISSUE TITLE
ExampleDontWorkInColab

### ISSUE THREAD

**Issue by profermarquez** [tiangolo/fastapi#9213]
### Privileged issue

- [ ] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content
when i try to create or read a client fails, part of the api works

The example (https://fastapi.tiangolo.com/tutorial/sql-databases/) don't work in google colab (https://colab.research.google.com/drive/1aKwxcAwgnCCpR00MPK4f1Ys77Cyx1QOT?usp=sharing).

Stack from the error:

INFO:     Started server process [138]

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)

**Comment by n8sty** [comment]
Google Colab isn't necessarily the environment you want to try and run FastAPI applications from. My understanding is that Colab is more around creating a shared notebook environment, which often means analysis and machine learning style workflows. Regardless, this isn't an issue with FastAPI per se. Try closing the issue and opening a discussion or asking on a forum that's more aligned with Colab.

**Comment by Kludex** [comment]
Hey there, although you checked that box, it seems you're not @tiangolo, and he didn't ask you to create this issue. :sweat_smile:

So, please open a GitHub Discussion following all the template step by step. That will allow me or others to properly help you. :coffee:

Given that, I'm going to close this one.
