### ISSUE TITLE
[QUESTION] Miss field value after validation

### ISSUE THREAD

**Issue by ysanchezl** [tiangolo/fastapi#934]
Hi, I had a field that its values depends of another, but also has a default value:

`class A(BaseModel):
attributes: List[str] = Field(None)
score: str = Field(None, alias="freq")

the behavior a need is the following:
score_field = score_field_default
    valid_score_fields = []
    if "score_field" in request:
        sf = req["score_field"]
        if sf in score_fields:
            score_field = sf
        else:
            raise ValueError("No valid score field received. Use one of {}".format(score_fields_valid),
                             "error")
    else:
        if "attributes" in request:           
                result_fields = request["attributes"]
                for field in result_fields:
                    if field in score_fields_getProfiles_map:
                        valid_score_fields.append(field)
                if len(valid_score_fields) > 0:
                    msg.append({"msg": "Valid score fields received: {}.".format(valid_score_fields),
                                "level": "warning"})
                    score_field = valid_score_fields
        msg.append({"msg": "Score field not received. Using default: '{}'.".format(score_field),
                    "level": "warning"})`

How can I do this with validators? I tried this:

  `@validator('score_field', pre=True, always=True)
    def set_default_score_field_value(cls, v, values):
        if v is None and "attributes" in values and values["attributes"] is not None:
            valid_score_fields = []
            for field in values["attributes"]:
                if field in score_fields_getProfiles_map:
                    valid_score_fields.append(field)
            if len(valid_score_fields) > 0:
                v = valid_score_fields                    
                values["msg"].append({"msg": "Valid score fields received: {}.".format(v),
                            "level": "warning"})    
        return v or score_field_default
`
values collection contains the msg value but not the score_field value:
{'msg': [{'msg': "Valid score fields received: ['attributes', 'importances'].", 'level': 'warning'}],  'attributes': ['attributes', 'importances']}

What I doing wrong?
thanks a lot!!!

**Comment by phy25** [comment]
This is more of a pydantic question rather than a fastapi one? Could you please try formatting your code correctly by using "Insert code" in the toolbar?

I am not sure if modifying `values` with a validator against one field is OK. You may want to look at the docs:
https://pydantic-docs.helpmanual.io/usage/validators/#root-validators

**Comment by ysanchezl** [comment]
Thanks , for the fast replay....Your are right , this is a pydantic question. Finally, I redefined the validation and divided it in two.

**Comment by phy25** [comment]
If this is resolved you can close your issue :-)

**Comment by tiangolo** [comment]
Thanks for the help @phy25 ! :cake: :bowing_man: 

Thanks @ysanchezl for reporting back and closing the issue :+1:
