### ISSUE TITLE
[BUG][DOC] Typo/Raw Markup in tutorial middleware documentation

### ISSUE THREAD

**Issue by blep** [tiangolo/fastapi#937]
### Describe the bug

In the tutorial documentation on middleware (`docs/tutorial/middleware.md`), just before section `Before and after the response`, there is some raw Markdown appearing in the doc:

- https://github.com/tiangolo/fastapi/blob/master/docs/tutorial/middleware.md#before-and-after-the-response
- https://fastapi.tiangolo.com/tutorial/middleware/#before-and-after-the-response

See text around `](cors.md){.internal-link target=_blank}) using the parameter expose_headers documented in Starlette's CORS docs.`. 

Might just be the newline in middle of link inside the quote confusing the parser.

**Comment by phy25** [comment]
Please see #933.

**Comment by phy25** [comment]
Should be fixed by #893.

**Comment by blep** [comment]
Fixed in master.

**Comment by tiangolo** [comment]
Thanks for the help here @phy25 ! :cake: :bowing_man: 

Thanks @blep for reporting back and closing the issue :+1:
