### ISSUE TITLE
[FEATURE] Add docs about redirections

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/fastapi#961]
### Is your feature request related to a problem

Is your feature request related to a problem?

It's still not documented how to do redirections.

### The solution you would like

We need a short section in the docs, in the Advanced User Guide, about how to do redirections.

It would have to explain how to use [Starlette's `RedirectResponse`](https://www.starlette.io/responses/#redirectresponse)

### Describe alternatives you've considered

Searching in answers in GitHub issues or reading all the docs in Starlette...

**Comment by jtmiclat** [comment]
Interested doing this!

**Comment by ByK95** [comment]
@jtmiclat are you working on this

**Comment by tiangolo** [comment]
We now have docs about redirect responses: https://fastapi.tiangolo.com/advanced/custom-response/#redirectresponse :tada:
