### ISSUE TITLE
FastAPI with Pydantic v2

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/fastapi#9710]
Is FastAPI with support for Pydantic v2 working for you (`0.100.0-beta1`)?

~Let me know **in this discussion** on the link: https://github.com/tiangolo/fastapi/discussions/9709~

~(don't comment in this issue, please go to the discussions and follow the instructions there)~

As FastAPI now supports Pydantic v2, any problems are not about the beta (as it's already released 😅), so let's keep the normal workflow.

If you are having problems, please create a new Discussion question following the template! 🙏  https://github.com/tiangolo/fastapi/discussions/new?category=questions

**Comment by iamjosejimenez** [comment]
Hi! I just updated my project to fastapi **v0.100.0-beta1** and pydantic **v2.0b2** and I'm getting the following error:

```
pydantic.errors.PydanticImportError: pydantic:BaseSettings has been removed in V2.

For further information visit https://errors.pydantic.dev/2.0b2/u/import-error

```
Is there any official migration guide from pydantic v1 to pydantic v2?

**Comment by Kludex** [comment]
Yes. There is: https://docs.pydantic.dev/dev-v2/migration/

**Comment by aradkdj** [comment]
Parsing of `Literal` types seems to be broken with Pydantic v2.

Take this example:
```python
from typing import Literal

from pydantic import BaseModel


class Health(BaseModel):
    status: Literal["ok", "error"]
```

Doing `print(Health.model_json_schema())` seems to return the right thing (`{'properties': {'status': {'enum': ['ok', 'error'], 'title': 'Status'}}, 'required': ['status'], 'title': 'Health', 'type': 'object'}`

However, if I use it as the return model for a path operation, the schema is broken in the swagger docs. Weirdly the examples do use one of the values.

![image](https://github.com/tiangolo/fastapi/assets/47002300/c2c40fbb-33c5-46bc-868c-39cdcf0779c7)

![image](https://github.com/tiangolo/fastapi/assets/47002300/d0cd0f95-fb7f-4484-842b-ef9ddc65f54e)

Here is a pastebin with the generated openapi.json: https://pastebin.com/a95Tujah

**Comment by tiangolo** [comment]
@aradkdj please check the instructions on the discussion and comment there: https://github.com/tiangolo/fastapi/discussions/9709

**Comment by micaelmalta** [comment]
@tiangolo this is not working with a basic setup:

```
from fastapi import FastAPI

app = FastAPI()


@app.get("/")
async def root():
    return "hello world"


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
    ```

```
(.venv) ➜  fastapi_pydantic pdm run main.py
Traceback (most recent call last):
  File "/Users/xxxdevelopment/fastapi_pydantic/main.py", line 1, in <module>
    from fastapi import FastAPI
  File "/Users/xxx/development/fastapi_pydantic/.venv/lib/python3.11/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/Users/xxx/development/fastapi_pydantic/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/Users/xxx/development/fastapi_pydantic/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/Users/xxx/development/fastapi_pydantic/.venv/lib/python3.11/site-packages/fastapi/params.py", line 6, in <module>
    from ._compat import PYDANTIC_V2, Undefined
  File "/Users/xxx/development/fastapi_pydantic/.venv/lib/python3.11/site-packages/fastapi/_compat.py", line 50, in <module>
    from pydantic._internal._fields import Undefined as Undefined
ImportError: cannot import name 'Undefined' from 'pydantic._internal._fields' (/Users/xxx/development/fastapi_pydantic/.venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py)
```

```
dependencies = [
    "fastapi==0.100.0-beta1",
    "uvicorn"
]
```

**Comment by sylvainmouquet** [comment]
Why not move to release 1.X ?

**Comment by trabem** [comment]
> Why not move FastAPI to release 1.X ?

I think it depends on starlette. Thats core dependency for FastAPI, and still doesn't provide major release. Starlette can change internal behavior without backward compatibility (like dropping support for graphql in version 0.17) but that unacceptable for stable major version. That's why FastAPI also in minor release cycle like starlette

**Comment by Kludex** [comment]
Even if Starlette release 1.0, FastAPI will not follow immediately. I think Sebastián has some changes planned before 1.0.

**Comment by sylvainmouquet** [comment]
It's not a problem, if there is a breaking change, the version can be a version 2 and next, ...
FastAPI is mature, lot of projects use it in production, it's time to release a version 1.X

**Comment by EdgyNortal** [comment]
Going through pydantic docs to try to discover the root cause of an issue I am seeing.

Previously you could do 
```
def dict(self, *args, **kwargs):
   kwargs["exclude_none"] = True
   return super().dict(*args, **kwargs)
```

According to pydantic v2 docs `dict` -> `model_dump` and it still supports exclude_none etc.

But in fastapi responses I am now seeing the keys with None values appearing, and I can't track down where the disconnect between myself, fastapi and pydantic v2 lies.

I've tried overloading every method I can detect that is called during fastapi serialization to see if any of them are called, but it seems to not be hitting any of the pydantic methods.

Despite the following code, the endpoint returns as if nothing has gone wrong.

```

    def model_dump(self, *args: ..., **kwargs: ...) -> str:
        raise Exception
        kwargs["exclude_none"] = True
        return super().model_dump(*args, **kwargs)

    def model_dump_json(self, *args: ..., **kwargs: ...) -> str:
        raise Exception
        kwargs["exclude_none"] = True
        return super().model_dump_json(*args, **kwargs)

    def to_python(self, *args: ..., **kwargs: ...) -> str:
        raise Exception
        kwargs["exclude_none"] = True
        return super().to_python(*args, **kwargs)

    def dump_python(self, *args: ..., **kwargs: ...) -> str:
        raise Exception
        kwargs["exclude_none"] = True
        return super().dump_python(*args, **kwargs)

    def dict(self, *args: ..., **kwargs: ...) -> str:
        raise Exception
        kwargs["exclude_none"] = True
        return super().dict(*args, **kwargs)
```

Any assistance would be great, looking forward to upgrading our systems to fastapi with pydantic v2, but can't seem to get past this one on my own.

**Comment by EdgyNortal** [comment]
Minimum example

```
import fastapi
import pydantic

app = fastapi.FastAPI()


class Model(pydantic.BaseModel):
    data: str | None

    def model_dump(self, *args: ..., **kwargs: ...) -> str:
        raise Exception
        kwargs["exclude_none"] = True
        return super().model_dump(*args, **kwargs)

    def model_dump_json(self, *args: ..., **kwargs: ...) -> str:
        raise Exception
        kwargs["exclude_none"] = True
        return super().model_dump_json(*args, **kwargs)

    def to_python(self, *args: ..., **kwargs: ...) -> str:
        raise Exception
        kwargs["exclude_none"] = True
        return super().to_python(*args, **kwargs)

    def dump_python(self, *args: ..., **kwargs: ...) -> str:
        raise Exception
        kwargs["exclude_none"] = True
        return super().dump_python(*args, **kwargs)

    def dict(self, *args: ..., **kwargs: ...) -> str:
        raise Exception
        kwargs["exclude_none"] = True
        return super().dict(*args, **kwargs)


@app.get("/")
async def root() -> Model:
    return Model(data=None)
```

```
$ curl 127.0.0.1:8000
> {"data":null}
```

**Comment by tiangolo** [comment]
@EdgyNortal please report it in the discussion from the link above, not here, that way it's easier to track the conversation: https://github.com/tiangolo/fastapi/discussions/9709

**Comment by woosal1337** [comment]
While integrating MongoDB, which uses BSON instead of the JSON type of data makes the retrieved data not possible to iterate over, forcing the BSON serialization to String (Only the _id of the inserted items are BSON).

FastAPI `0.99.1`
Pydantic `1.10.11` 

With these versions of libraries, it was possible to make such a serialization with the following line of code:

pydantic.json.ENCODERS_BY_TYPE[ObjectId] = str

while importing the bson object, which is not separately installed but came with the pymongo[srv] installation alongside.

from bson import ObjectId


Sadly, this conversion is completely broken by both @pydantic and @fastapi with their latest releases.

**Comment by tiangolo** [comment]
@woosal1337 given your versions, this is not related to Pydantic v2.

Please create a new question in GitHub Discussions following the template.

**Comment by woosal1337** [comment]
Is it [#9709](https://github.com/tiangolo/fastapi/discussions/9709)? On it.

**Comment by woosal1337** [comment]
> @woosal1337 given your versions, this is not related to Pydantic v2.
> 
> Please create a new question in GitHub Discussions following the template.

Is it [#9709](https://github.com/tiangolo/fastapi/discussions/9709)? On it.

**Comment by wenkesj** [comment]
> Yes. This was already reported: https://github.com/tiangolo/fastapi/discussions/9709#discussioncomment-6396226.

Thanks for the reference! I'll do a more thorough search next time 😄

**Comment by AlexanderPodorov** [comment]
Issue 1. Seems like the `pydantic` issue, since the it is generating the following signature:
`<Signature (*args: 'Any', **kwargs: 'Any') -> 'None'>`. Whereas the stdlib dataclasses generate the signature as expected.

**Comment by Kludex** [comment]
> @tiangolo , after upgrade to `fastapi==0.100.0` and `pydantic==2.0.2` I got following issues below. Both worked fine with `fastapi<0.100.0` and `pydantic==1.10.11`. See MRE:
> 
> ```python
> from collections.abc import Sequence
> from typing import Annotated, Any, Generic, TypeVar
> 
> from fastapi import Depends, FastAPI
> from pydantic import BaseModel, TypeAdapter
> from pydantic.dataclasses import dataclass as pydantic_dc
> 
> api = FastAPI()
> 
> 
> fake_items_db = [{"item_name": "Foo"}, {"item_name": "Bar"}, {"item_name": "Baz"}]
> 
> 
> T = TypeVar('T')
> 
> 
> class ItemOut(BaseModel):
>     item_name: str
> 
> 
> class PaginationOut(BaseModel, Generic[T]):
>     page: int
>     per_page: int
>     pages: int
>     total: int
>     items: Sequence[T]
> 
>     @classmethod
>     def model_parametrized_name(cls, params: tuple[type[Any], ...]) -> str:
>         return f'{params[0].__name__.removesuffix("Out")}{cls.__name__}'
> 
> 
> @pydantic_dc()
> class CommonQueryParams:
>     q: str | None = None
>     skip: int = 0
>     limit: int = 100
> 
> 
> @api.get("/items/")
> async def read_items(
>     commons: Annotated[CommonQueryParams, Depends(CommonQueryParams)]
> ) -> PaginationOut[ItemOut]:
>     pagination = PaginationOut[ItemOut](
>         page=1,
>         per_page=1,
>         pages=1,
>         total=1,
>         items=TypeAdapter(list[ItemOut]).validate_python(fake_items_db)
>     )
>     return PaginationOut[ItemOut].model_validate(pagination)
> ```
> 
> 1. Query parameters turned into `args` and `kwargs`:
>    ![image](https://user-images.githubusercontent.com/54511144/252431920-b78cd172-ced1-4fea-af5a-389738858d90.png)
> 2. Incorrect definition for `PaginationOut[ItemOut]` model. The name should be `ItemPaginationOut` (the class defined `model_parametrized_name`) and pagination attributes should be of proper type instead of `any`:
>    ![image](https://user-images.githubusercontent.com/54511144/252432757-6670bbf6-eeb2-433d-ab7d-8618c2a4b3f8.png)
>    Thanks!

What's the compatible code for V1?

**Comment by Kludex** [comment]
> Issue 1. Seems like the `pydantic` issue, since the it is generating the following signature: `<Signature (*args: 'Any', **kwargs: 'Any') -> 'None'>`. Whereas the stdlib dataclasses generate the signature as expected.

Right. I'm going to take a look.

**Comment by AlexanderPodorov** [comment]
@Kludex , thank you!
@tiangolo , to give you some context why I'm using pydantic dataclasses instead of stdlib dataclasses (this was intentionally omitted for simplicity sake):

```python
from pydantic.dataclasses import dataclass. # import pydantic dataclass
from ... import model_config  # config dict for parent BaseModel, having alias_generator

@dataclass(config=model_config)
class PaginationGet(BaseParameters):
    page: Annotated[int, Query(gt=0)] = 1
    per_page: Annotated[PerPage, Query()] = PerPage.VALUE_025
    all_items: Annotated[bool, Query()] = False
```
This allows to automatically generate aliases for `Query` parameters, without needing to set `alias` for each `Query` explicitly. The same approach can be used to generate aliases for  `Path`, `Form` or `File` parameters as well (as long as they are "wrapped" into pydantic dataclass). I think it should be a legit use case.

**Comment by Kludex** [comment]
I'll lock this issue. As @tiangolo said, the idea of this issue was to redirect people to the discussion on #9709. 👀 

It's easier to organize the issues if everything is over there. 😅 

If you have an issue with FastAPI + Pydantic V2, please post it on #9709, or create a new discussion. 🙏
