### ISSUE TITLE
[BUG] Websocket Routes Only Work on FastAPI, not APIRouter

### ISSUE THREAD

**Issue by iwoloschin** [tiangolo/fastapi#98]
**Describe the bug**
Websocket routes appear to only work on the main FastAPI object, not on APIRouter objects.  When the same function is copied from a FastAPI object to an APIRouter object instead of working properly it just throws a 403.

**To Reproduce**
1. The following works as expected:
```python
from fastapi import FastAPI
app = FastAPI()

@app.websocket_route("/hello")
async def hello(websocket):
    await websocket.accept()
    await websocket.send_text("Hello!")
    response = await websocket.receive_text()
    print(response)
    await websocket.close()
    print("Closed")
```
2. Moving `hello` to an APIRouter fails:
```python
# main.py
from fastapi import FastAPI
import other
app = FastAPI()
app.include_router(other.router)
```

```python
# other.py
from fastapi import APIRouter
router = APIRouter()

@router.websocket_route("/routerhello")
async def hello(websocket):
    await websocket.accept()
    await websocket.send_text("Router Hello!")
    response = await websocket.receive_text()
    print(response)
    await websocket.close()
    print("Router Closed")
```
**Expected behavior**
I expect a websocket route to work on both a FastAPI and APIRouter object.

**Screenshots**
Not applicable.

**Environment:**
 - OS: macOS 10.14.3
 - FastAPI Version: 0.9.0

- Python version, get it with: 3.7.2

**Additional context**
Testing websocket client side with `websocat`.

**Comment by tiangolo** [comment]
Thanks for the report!

It was fixed by @euri10 in PR https://github.com/tiangolo/fastapi/pull/100.

It is available in FastAPI verson `0.10.0`. :tada: :rocket:

**Comment by iwoloschin** [comment]
Just tested it out!  I'm impressed at how quickly that was fixed, thanks!

**Comment by tiangolo** [comment]
Awesome! Kudos to @euri10 for his work 😀🍰🌮

Thanks @iwoloschin for reporting back and closing the issue.

**Comment by brunopcarv** [comment]
Is there a chance that something brought this issue back? Or it might be related to Python 3.6.8?

I find the same bug in this minimal example where only the second websocket fails:
```python
from fastapi import FastAPI
from fastapi.testclient import TestClient
from fastapi.websockets import WebSocket
from fastapi import APIRouter 

app = FastAPI()
router = APIRouter(prefix="/test")
app.include_router(router)


@app.websocket_route("/ws")
async def websocket(websocket: WebSocket):
    await websocket.accept()
    await websocket.send_json({"msg": "Hello WebSocket"})
    await websocket.close()


@router.websocket_route("/ws")
async def websocket(websocket: WebSocket):
    await websocket.accept()
    await websocket.send_json({"msg": "Hello WebSocket 2"})
    await websocket.close()


def test_websocket():
    client = TestClient(app)
    with client.websocket_connect("/ws") as websocket:
        data = websocket.receive_json()
        assert data == {"msg": "Hello WebSocket"}


def test_websocket2():
    client = TestClient(app)
    with client.websocket_connect("/test/ws") as websocket:
        data = websocket.receive_json()
        assert data == {"msg": "Hello WebSocket 2"}

```

Error log:
```
def test_websocket2():
        client = TestClient(app)
>      with client.websocket_connect("/test/ws") as websocket:

/opt/conda/envs/build_env/envs/run_env/lib/python3.6/site-packages/starlette/testclient.py:444: in websocket_connect
super().request("GET", url, **kwargs)
/opt/conda/envs/build_env/envs/run_env/lib/python3.6/site-packages/requests/sessions.py:542: in request
resp = self.send(prep, **send_kwargs)
/opt/conda/envs/build_env/envs/run_env/lib/python3.6/site-packages/requests/sessions.py:655: in send
r = adapter.send(request, **kwargs)
/opt/conda/envs/build_env/envs/run_env/lib/python3.6/site-packages/starlette/testclient.py:145: in send
session = WebSocketTestSession(self.app, scope)
/opt/conda/envs/build_env/envs/run_env/lib/python3.6/site-packages/starlette/testclient.py:278: in __init__
self._raise_on_close(message)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <starlette.testclient.WebSocketTestSession object at 0x7f7cbc689c50>
message = {'code': 1000, 'type': 'websocket.close'}
def _raise_on_close(self, message: Message) -> None:
        if message["type"] == "websocket.close":
>           raise WebSocketDisconnect(message.get("code", 1000))
E           starlette.websockets.WebSocketDisconnect: 1000

```

Environment:
 - OS: Amazon Linux Workspace

 - FastAPI Version: 0.63.0

 - Python version: 3.6.8

Thank you for the attention.

**Comment by Kludex** [comment]
@brunopcarv This is a 2 years old issue... You'll have better chances of getting help if you create a new one. :kissing:

**Comment by Udayaprasad** [comment]
@euri10  @tiangolo 

Looks like this bug again comes in the `0.67.0  - latest` version. Could you please check once?

APIRouter prefix is not getting utilized in `@router.websocket('/')` endpoint definition. I am getting `403` error.

![image](https://user-images.githubusercontent.com/8266316/127117803-c52ad720-9c79-45ab-834f-2e44fbd4d604.png)

**Comment by ChrisScarred** [comment]
> @euri10 @tiangolo
> 
> Looks like this bug again comes in the `0.67.0 - latest` version. Could you please check once?
> 
> APIRouter prefix is not getting utilized in `@router.websocket('/')` endpoint definition. I am getting `403` error.
> 
> ```
> router = APIRouter(
>     prefix="/substructures",
>     tags=["Substructures"],
>     responses={404: {"description": "Not found"}},
> )
> 
> @router.websocket('/')
> async def websocket_execute(websocket: WebSocket):
>     ....
> ```
> 
> ![image](https://user-images.githubusercontent.com/8266316/127117803-c52ad720-9c79-45ab-834f-2e44fbd4d604.png)

the same bug is present in version 0.65.1

**Comment by farlabjavier** [comment]
same error in  0.68.1

**Comment by nanacnote** [comment]
I have the same issue at the moment  if i set the prefix param in APIRoute() and try to connect to said route it raises 403 however if i drop the prefix it connects successfully. Thank you.

server
`
router = APIRouter(prefix="/service", tags=["service"])

@router.websocket("/data/market")
async def market_data(websocket: WebSocket):
    await websocket.accept()
    while True:
        data = await websocket.receive_text()
        await websocket.send_text(f"Message text was: {data}")
`

client
`
const s = new WebSocket("ws://localhost:5000/service/data/market")  //---> not working 
const s = new WebSocket("ws://localhost:5000/data/market")  //--->  working
`

**Comment by mntolia** [comment]
I am also facing the exact same issue. I am getting a 403 error for websockets under routers with prefix. It works without the prefix.

**Comment by smb-h** [comment]
still happening in 0.70.0

**Comment by hd10180** [comment]
for those appear problem: `('127.0.0.1', 50527) - "WebSocket /ws/1639xxxx" 403`
if you follow the documentation from [fastapi websocket](https://fastapi.tiangolo.com/advanced/websockets/#handling-disconnections-and-multiple-clients)，try check your ws url in html file, if the url not match, will get the 403 error;
i just face the same problem too.
i'm using `fastapi 0.70.0` too

**Comment by XCanG** [comment]
Still getting this issue on `fastapi==0.73.0`.

**Comment by xiki808** [comment]
Same issue as @nanacnote reported, with version 0.73.0. 

Websocket created on APIRouter with prefix, but connection only works if the prefix is not included in the URL

**Comment by lokaimoma** [comment]
Same issue in fastapi==0.73.0
![image](https://user-images.githubusercontent.com/46226886/154799609-e40a56f6-b021-46e1-affc-41596e53fcea.png)

**Comment by fujiawei-dev** [comment]
Same issue in fastapi==0.74.0

**Comment by mosynaq** [comment]
Applying [this](https://github.com/tiangolo/fastapi/pull/3735/commits/d95dbfca98b8f1888447d79f22a0f992dc08e1b3) (read monkey patching) saved my day. Waiting for @tiangolo to accept this PR.

**Comment by dnilosek** [comment]
Running into same issue, can that fix be included soon?

**Comment by sandiandian** [comment]
Same issue in fastapi==0.75.1

**Comment by tiangolo** [comment]
Hey all! Some of you might have been experiencing a similar issue related to `APIRouter`s with `prefix`. That was reported here: https://github.com/tiangolo/fastapi/issues/2639

It was fixed by @Kludex here: https://github.com/tiangolo/fastapi/pull/2640

And that fix will be available in FastAPI version `0.75.2`, released in a couple of hours. :rocket:

**Comment by philipokiokio** [comment]
Hi everyone thanks for the help and for fixing this issue. 

Truthfully the WebSocket fix works in development, however in production it reverted to the FastAPI base Route.

I just wanted to be bring that everyone's notice.

**Comment by philipokiokio** [comment]
Another thing I noticed is that the WebSocket does not reflect in the Docs. Although the OpenAPI doc added is the 3.0 version which should be able to document websocket endpoints.

**Comment by philipokiokio** [comment]
@Kludex  I don't get the reason you are sending emojis such as the down thumb and all. it's better to ignore than act funny.

**Comment by Kludex** [comment]
I sent emojis to show how I feel about your comments. I didn't mean to offend you.

Let me explain why:

> Truthfully the WebSocket fix works in development (Uvicorn server), however, in production (Ubuntu environment) the websocket did not connect to the APIRouter specified.

There can't be a possible scenario on which it has a different behavior depending on the environment (prod vs dev) because of **this issue**. It can be because of other factors, but not because of this one.

> Another thing I noticed is that the WebSocket does not reflect in the Docs. Although the OpenAPI doc added is the 3.0 version which should be able to document websocket endpoints.

This comment is not true. OpenAPI docs doesn't support `WebSocket`s. On OpenAPI 3.1 [`Webhooks` were added](https://www.openapis.org/blog/2021/02/18/openapi-specification-3-1-released), but there was never support for `WebSocket`s. [`AsyncAPI`](https://www.asyncapi.com/docs/specifications/v2.3.0) is an alternative for `WebSocket`s, but FastAPI doesn't support it.

**Comment by philipokiokio** [comment]
@Kludex Thanks for your explanation. 

To be fair I was not even pointing to this issue, and I agree that it could be something else. I was just bringing it forward (hoping) someone had experienced that and there is a fix to it. 

With regards to OpenAPI documentation, thank you for clarifying that, I read it somewhere and I believed it (I also saw the OpenAPI swagger package on PyPI that suggested something along that line). 

Thank you for your reply and all you do in the FastAPI community.

Continue to have an awesome day.

**Comment by Hyperx837** [comment]
same issue in `fastapi==0.79.0`

**Comment by philipokiokio** [comment]
Hey @Hyperx837  yeah. You should consider creating another instance of the FastAPI application, create a WebSocket with the newly created app instance and then mount it on the Base App where the core application routers live.

**Comment by hscspring** [comment]
same issue in fastapi==0.88.0

i should use FastAPI instead of APIRouter

**Comment by Lopofsky** [comment]
> same issue in fastapi==0.88.0
> 
> i should use FastAPI instead of APIRouter....
> 
> update
> 
> ok, it works, well in two files.
> 
> If all in one file, should like this order:
> 
> ```python
> router = APIRouter(prefix="/ws")
> 
> @router.websocket("/asr")
> async def websocket_a(ws_a: WebSocket):...
> 
> app = FastAPI()
> app.include_router(router)
> ```
> 
> not this:
> 
> ```python
> router = APIRouter(prefix="/ws")
> app = FastAPI()
> app.include_router(router)
> 
> 
> @router.websocket("/asr")
> async def websocket_a(ws_a: WebSocket):...
> ```
> 
> @Hyperx837 u could have a try

Btw that was the solution for me: replaced `@router.websocket_route` with `@router.websocket` and just added a `prefix` to the `APIRouter` and ws worked again.

**Comment by papapumpnz** [comment]
@Lopofsky what FastAPI version are you using? This is not working for me with 0.97.0. Getting the 403 error with websocket endpoints defined in other routes files. Using `@router.websocket` as well.

**Comment by Lopofsky** [comment]
@papapumpnz `fastapi==0.95.2`

**Comment by usenet506** [comment]
after update 0.95 to 0.100.1, I fix this problem

**Comment by AntonOfTheWoods** [comment]
I'm still getting this with 0.101.0.

**Comment by lewisjr** [comment]
I confirm with @AntonOfTheWoods . Currently (22 Aug 2023 at 17:20 UTC) the latest version of FastAPI is `0.101.1` which is the version I am using. I updated from `0.97.1` which I was using where I was not able to add a websocket via router. Here is how I have it working in `v0.101.1` (barebones):

**chat_ws.py**  
```python
from fastapi import APIRouter, WebSocket

chat_socket = APIRouter()

@chat_socket .websocket("/chat")
async def handle_ws(ws: WebSocket):
    await ws.accept()

    while True:
        string = await ws.receive_text()
        await websocket.send_text(string)
```

**main.py**  
```python
from fastapi import FastAPI
from . import chat_socket

app = FastAPI()

app.add_websocket_route("/ws", chat_socket)
```

**Comment by annisat** [comment]
Reporting this issue with version==0.103.2.
Following @lewisjr 's instruction I changed the route to the same. But postman still says it cannot connect to the url.

**Comment by AleksaMCode** [comment]
I had the same error when using Python `v3.10.7` with FastAPI `v0.104.1`. Replacing `@router.websocket_route` with `@router.websocket` fixed the issue for me. Here is a sample code that works:
- websocket method in *ws/ws.py*
```python3
from fastapi import WebSocket, APIRouter

router = APIRouter(
    prefix="/ws"
)

@router.websocket("/pub/{channel_id}")
async def ws_endpoint(websocket: WebSocket):
    # ...
```
- main
```python3
import uvicorn
from fastapi import FastAPI
from ws import ws

app = FastAPI()
app.include_router(ws.router)

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)

```

**Comment by Kludex** [comment]
This was solved years ago.
