### ISSUE TITLE
multi-environment configuration

### ISSUE THREAD

**Issue by mht2953658596** [tiangolo/fastapi#9888]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

How can we implement multi-environment configuration in FastAPI, like in Spring Boot? Can we use YAML or property files to achieve multi-environment configuration?

**Comment by mht2953658596** [comment]
I would like to know some official solutions.

**Comment by Kludex** [comment]
Please create a discussion following the [official template](https://github.com/tiangolo/fastapi/discussions/new/choose).

>  I'm @tiangolo or he asked me directly to create an issue here.

Also... You are not @tiangolo, neither he asked you to create this... 😅
