### ISSUE TITLE
Dependency override websocket broken

### ISSUE THREAD

**Issue by teucer** [tiangolo/fastapi#998]
### Describe the bug

Dependency override does not work for websockets. 

The function `add_api_websocket_route` does not add `dependency_overrides_provider` to `APIWebSocketRoute`.

### To Reproduce

Create a simple app with websockets and test it with override.

### Expected behavior

The overrides should be taken into account, but the test uses the original dependency. 

### Environment

- OS: Windows
- FastAPI version: 0.49.0
- Python version: 3.6.8

**Comment by amitlissack** [comment]
`APIRouter.add_api_websocket_route` should be modified to construct the `APIWebSocketRoute` like this:
```
route = APIWebSocketRoute(
            path,
            endpoint=endpoint,
            name=name,
            dependency_overrides_provider=self.dependency_overrides_provider,
        )
```

**Comment by tiangolo** [comment]
Thanks for the report @teucer !

This should be fixed in https://github.com/tiangolo/fastapi/pull/1122 by @amitlissack , in the latest version.

I'm gonna re-open this issue to let you confirm and close it.

**Comment by teucer** [comment]
Thank you for the quick turn-around!
